/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

/* Auto register */
#if !defined(BROOKESIA_SERVICE_HTTP_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_SERVICE_HTTP_ENABLE_AUTO_REGISTER  CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_SERVICE_HTTP_ENABLE_AUTO_REGISTER  (0)
#   endif
#endif

/* Plugin symbol */
#if BROOKESIA_SERVICE_HTTP_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_SERVICE_HTTP_PLUGIN_SYMBOL)
#       define BROOKESIA_SERVICE_HTTP_PLUGIN_SYMBOL  service_http_symbol
#   endif
#endif

#define BROOKESIA_SERVICE_HTTP_LOG_TAG "SvcHTTP"

#if !defined(BROOKESIA_SERVICE_HTTP_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_HTTP_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_HTTP_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_HTTP_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_SERVICE_HTTP_SERVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_SERVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_HTTP_SERVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_HTTP_SERVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_HTTP_SERVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_HTTP_STATE_MACHINE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_STATE_MACHINE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_HTTP_STATE_MACHINE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_HTTP_STATE_MACHINE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_HTTP_STATE_MACHINE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_ENABLE_WORKER)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_WORKER)
#       define BROOKESIA_SERVICE_HTTP_ENABLE_WORKER  CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_WORKER
#   else
#       define BROOKESIA_SERVICE_HTTP_ENABLE_WORKER  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_HTTP_ENABLE_WORKER
#   if !defined(BROOKESIA_SERVICE_HTTP_WORKER_NAME)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_NAME)
#           define BROOKESIA_SERVICE_HTTP_WORKER_NAME  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_NAME
#       else
#           define BROOKESIA_SERVICE_HTTP_WORKER_NAME  "SvcHttpWorker"
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_HTTP_WORKER_PRIORITY)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_PRIORITY)
#           define BROOKESIA_SERVICE_HTTP_WORKER_PRIORITY  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_PRIORITY
#       else
#           define BROOKESIA_SERVICE_HTTP_WORKER_PRIORITY  (5)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_HTTP_WORKER_STACK_SIZE)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_STACK_SIZE)
#           define BROOKESIA_SERVICE_HTTP_WORKER_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_STACK_SIZE
#       else
#           define BROOKESIA_SERVICE_HTTP_WORKER_STACK_SIZE  (12288)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_HTTP_WORKER_STACK_IN_EXT)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_STACK_IN_EXT)
#           define BROOKESIA_SERVICE_HTTP_WORKER_STACK_IN_EXT  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_STACK_IN_EXT
#       else
#           define BROOKESIA_SERVICE_HTTP_WORKER_STACK_IN_EXT  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_HTTP_WORKER_POLL_INTERVAL_MS)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_POLL_INTERVAL_MS)
#           define BROOKESIA_SERVICE_HTTP_WORKER_POLL_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_POLL_INTERVAL_MS
#       else
#           define BROOKESIA_SERVICE_HTTP_WORKER_POLL_INTERVAL_MS  (10)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_HTTP_WORKER_NUM)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_NUM)
#           define BROOKESIA_SERVICE_HTTP_WORKER_NUM  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_NUM
#       else
#           define BROOKESIA_SERVICE_HTTP_WORKER_NUM  (2)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_HTTP_WORKER_0_CORE_ID)
#       if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_0_CORE_ID)
#           define BROOKESIA_SERVICE_HTTP_WORKER_0_CORE_ID  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_0_CORE_ID
#       else
#           define BROOKESIA_SERVICE_HTTP_WORKER_0_CORE_ID  (-1)
#       endif
#   endif
#   if BROOKESIA_SERVICE_HTTP_WORKER_NUM >= 2
#       if !defined(BROOKESIA_SERVICE_HTTP_WORKER_1_CORE_ID)
#           if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_1_CORE_ID)
#               define BROOKESIA_SERVICE_HTTP_WORKER_1_CORE_ID  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_1_CORE_ID
#           else
#               define BROOKESIA_SERVICE_HTTP_WORKER_1_CORE_ID  (-1)
#           endif
#       endif
#   endif
#   if BROOKESIA_SERVICE_HTTP_WORKER_NUM >= 3
#       if !defined(BROOKESIA_SERVICE_HTTP_WORKER_2_CORE_ID)
#           if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_2_CORE_ID)
#               define BROOKESIA_SERVICE_HTTP_WORKER_2_CORE_ID  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_2_CORE_ID
#           else
#               define BROOKESIA_SERVICE_HTTP_WORKER_2_CORE_ID  (-1)
#           endif
#       endif
#   endif
#   if BROOKESIA_SERVICE_HTTP_WORKER_NUM >= 4
#       if !defined(BROOKESIA_SERVICE_HTTP_WORKER_3_CORE_ID)
#           if defined(CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_3_CORE_ID)
#               define BROOKESIA_SERVICE_HTTP_WORKER_3_CORE_ID  CONFIG_BROOKESIA_SERVICE_HTTP_WORKER_3_CORE_ID
#           else
#               define BROOKESIA_SERVICE_HTTP_WORKER_3_CORE_ID  (-1)
#           endif
#       endif
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_ENABLE_HTTP)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_HTTP)
#       define BROOKESIA_SERVICE_HTTP_ENABLE_HTTP  CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_HTTP
#   else
#       define BROOKESIA_SERVICE_HTTP_ENABLE_HTTP  (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_ENABLE_HTTPS)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_HTTPS)
#       define BROOKESIA_SERVICE_HTTP_ENABLE_HTTPS  CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_HTTPS
#   else
#       define BROOKESIA_SERVICE_HTTP_ENABLE_HTTPS  (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_REQUIRE_TLS_VERIFY)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_REQUIRE_TLS_VERIFY)
#       define BROOKESIA_SERVICE_HTTP_REQUIRE_TLS_VERIFY  CONFIG_BROOKESIA_SERVICE_HTTP_REQUIRE_TLS_VERIFY
#   else
#       define BROOKESIA_SERVICE_HTTP_REQUIRE_TLS_VERIFY  (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_REQUIRE_TIME_SYNC)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_REQUIRE_TIME_SYNC)
#       define BROOKESIA_SERVICE_HTTP_REQUIRE_TIME_SYNC  CONFIG_BROOKESIA_SERVICE_HTTP_REQUIRE_TIME_SYNC
#   elif defined(CONFIG_BROOKESIA_SERVICE_HTTP_ENABLE_HTTPS)
#       define BROOKESIA_SERVICE_HTTP_REQUIRE_TIME_SYNC  (0)
#   else
#       define BROOKESIA_SERVICE_HTTP_REQUIRE_TIME_SYNC  BROOKESIA_SERVICE_HTTP_ENABLE_HTTPS
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_TIME_SYNC_POLL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_TIME_SYNC_POLL_MS)
#       define BROOKESIA_SERVICE_HTTP_TIME_SYNC_POLL_MS  CONFIG_BROOKESIA_SERVICE_HTTP_TIME_SYNC_POLL_MS
#   else
#       define BROOKESIA_SERVICE_HTTP_TIME_SYNC_POLL_MS  (1000)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_MAX_CONCURRENT_REQUESTS)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_MAX_CONCURRENT_REQUESTS)
#       define BROOKESIA_SERVICE_HTTP_MAX_CONCURRENT_REQUESTS  CONFIG_BROOKESIA_SERVICE_HTTP_MAX_CONCURRENT_REQUESTS
#   else
#       define BROOKESIA_SERVICE_HTTP_MAX_CONCURRENT_REQUESTS  (2)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_MAX_MEMORY_BODY_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_MAX_MEMORY_BODY_SIZE)
#       define BROOKESIA_SERVICE_HTTP_MAX_MEMORY_BODY_SIZE  CONFIG_BROOKESIA_SERVICE_HTTP_MAX_MEMORY_BODY_SIZE
#   else
#       define BROOKESIA_SERVICE_HTTP_MAX_MEMORY_BODY_SIZE  (32768)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_MAX_DOWNLOAD_FILE_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_MAX_DOWNLOAD_FILE_SIZE)
#       define BROOKESIA_SERVICE_HTTP_MAX_DOWNLOAD_FILE_SIZE  CONFIG_BROOKESIA_SERVICE_HTTP_MAX_DOWNLOAD_FILE_SIZE
#   else
#       define BROOKESIA_SERVICE_HTTP_MAX_DOWNLOAD_FILE_SIZE  (4194304)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_DEFAULT_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_DEFAULT_TIMEOUT_MS)
#       define BROOKESIA_SERVICE_HTTP_DEFAULT_TIMEOUT_MS  CONFIG_BROOKESIA_SERVICE_HTTP_DEFAULT_TIMEOUT_MS
#   else
#       define BROOKESIA_SERVICE_HTTP_DEFAULT_TIMEOUT_MS  (10000)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_SYNC_WAIT_EXTRA_MS)
#   define BROOKESIA_SERVICE_HTTP_SYNC_WAIT_EXTRA_MS  (5000)
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_DEFAULT_RETRY_COUNT)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_DEFAULT_RETRY_COUNT)
#       define BROOKESIA_SERVICE_HTTP_DEFAULT_RETRY_COUNT  CONFIG_BROOKESIA_SERVICE_HTTP_DEFAULT_RETRY_COUNT
#   else
#       define BROOKESIA_SERVICE_HTTP_DEFAULT_RETRY_COUNT  (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_BUFFER_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_BUFFER_SIZE)
#       define BROOKESIA_SERVICE_HTTP_BUFFER_SIZE  CONFIG_BROOKESIA_SERVICE_HTTP_BUFFER_SIZE
#   else
#       define BROOKESIA_SERVICE_HTTP_BUFFER_SIZE  (1024)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_FILE_IO_THREAD_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_FILE_IO_THREAD_STACK_SIZE)
#       define BROOKESIA_SERVICE_HTTP_FILE_IO_THREAD_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_HTTP_FILE_IO_THREAD_STACK_SIZE
#   else
#       define BROOKESIA_SERVICE_HTTP_FILE_IO_THREAD_STACK_SIZE  (8192)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_HTTP_PROGRESS_PUBLISH_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_HTTP_PROGRESS_PUBLISH_INTERVAL_MS)
#       define BROOKESIA_SERVICE_HTTP_PROGRESS_PUBLISH_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_HTTP_PROGRESS_PUBLISH_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_HTTP_PROGRESS_PUBLISH_INTERVAL_MS  (100)
#   endif
#endif
