/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#if !defined(BROOKESIA_SERVICE_AUDIO_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_SERVICE_AUDIO_ENABLE_AUTO_REGISTER  CONFIG_BROOKESIA_SERVICE_AUDIO_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_SERVICE_AUDIO_ENABLE_AUTO_REGISTER  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_AUDIO_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_SERVICE_AUDIO_PLAYBACK_PLUGIN_SYMBOL)
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_PLUGIN_SYMBOL  service_audio_playback_symbol
#   endif
#   if !defined(BROOKESIA_SERVICE_AUDIO_ENCODER_PLUGIN_SYMBOL_0)
#       define BROOKESIA_SERVICE_AUDIO_ENCODER_PLUGIN_SYMBOL_0  service_audio_encoder_symbol_0
#   endif
#   if !defined(BROOKESIA_SERVICE_AUDIO_DECODER_PLUGIN_SYMBOL_0)
#       define BROOKESIA_SERVICE_AUDIO_DECODER_PLUGIN_SYMBOL_0  service_audio_decoder_symbol_0
#   endif
#endif

/**
 * @brief Default log tag used by the audio service component.
 */
#define BROOKESIA_SERVICE_AUDIO_LOG_TAG "SvcAudio"

#if !defined(BROOKESIA_SERVICE_AUDIO_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_AUDIO_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_AUDIO_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_AUDIO_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Worker /////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER)
#       define BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER  CONFIG_BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER
#   else
#       define BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER  (0)
#   endif
#endif // BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////// Playback Control //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_AUDIO_PLAYBACK_ENABLE_AUTO_LOAD_DATA)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_ENABLE_AUTO_LOAD_DATA)
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_ENABLE_AUTO_LOAD_DATA \
            CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_ENABLE_AUTO_LOAD_DATA
#   else
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_ENABLE_AUTO_LOAD_DATA  (1)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_AUDIO_PLAYBACK_KV_ERASE_DATA_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_KV_ERASE_DATA_TIMEOUT_MS)
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_KV_ERASE_DATA_TIMEOUT_MS \
            CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_KV_ERASE_DATA_TIMEOUT_MS
#   else
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_KV_ERASE_DATA_TIMEOUT_MS  (20)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_DEFAULT)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_DEFAULT)
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_DEFAULT  CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_DEFAULT
#   else
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_DEFAULT  (75)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MIN)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MIN)
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MIN  CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MIN
#   else
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MIN  (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MAX)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MAX)
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MAX  CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MAX
#   else
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_VOLUME_MAX  (100)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_AUDIO_PLAYBACK_DEFAULT_MUTE)
#   if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_DEFAULT_MUTE)
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_DEFAULT_MUTE  CONFIG_BROOKESIA_SERVICE_AUDIO_PLAYBACK_DEFAULT_MUTE
#   else
#       define BROOKESIA_SERVICE_AUDIO_PLAYBACK_DEFAULT_MUTE  (0)
#   endif
#endif
#if BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER
#   if !defined(BROOKESIA_SERVICE_AUDIO_WORKER_NAME)
#      if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_NAME)
#          define BROOKESIA_SERVICE_AUDIO_WORKER_NAME  CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_NAME
#      else
#          define BROOKESIA_SERVICE_AUDIO_WORKER_NAME  "SvcAudioWorker"
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_AUDIO_WORKER_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_CORE_ID)
#          define BROOKESIA_SERVICE_AUDIO_WORKER_CORE_ID  CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_CORE_ID
#      else
#          define BROOKESIA_SERVICE_AUDIO_WORKER_CORE_ID  (-1)
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_AUDIO_WORKER_PRIORITY)
#      if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_PRIORITY)
#          define BROOKESIA_SERVICE_AUDIO_WORKER_PRIORITY  CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_PRIORITY
#      else
#          define BROOKESIA_SERVICE_AUDIO_WORKER_PRIORITY  (5)
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_AUDIO_WORKER_STACK_SIZE)
#      if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_STACK_SIZE)
#          define BROOKESIA_SERVICE_AUDIO_WORKER_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_STACK_SIZE
#      else
#          define BROOKESIA_SERVICE_AUDIO_WORKER_STACK_SIZE  (5120)
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_AUDIO_WORKER_STACK_IN_EXT)
#      if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_STACK_IN_EXT)
#          define BROOKESIA_SERVICE_AUDIO_WORKER_STACK_IN_EXT  CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_STACK_IN_EXT
#      else
#          define BROOKESIA_SERVICE_AUDIO_WORKER_STACK_IN_EXT  (0)
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_AUDIO_WORKER_POLL_INTERVAL_MS)
#      if defined(CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_POLL_INTERVAL_MS)
#          define BROOKESIA_SERVICE_AUDIO_WORKER_POLL_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_AUDIO_WORKER_POLL_INTERVAL_MS
#      else
#          define BROOKESIA_SERVICE_AUDIO_WORKER_POLL_INTERVAL_MS  (10)
#      endif
#   endif
#endif // BROOKESIA_SERVICE_AUDIO_ENABLE_WORKER
