#
# PC Platform
#
set(COMPONENT_LIB brookesia_lib_utils_impl)
set(component_pc_config_compile_definitions "")

if(EMSCRIPTEN)
    set(BROOKESIA_LIB_UTILS_WASM_SINGLE_THREAD_SCHEDULER ON CACHE BOOL
        "Use browser single-thread TaskScheduler backend" FORCE)
    list(REMOVE_ITEM COMPONENT_SRCS_CPP "${COMPONENT_SRC_DIR}/task_scheduler.cpp")
    list(APPEND COMPONENT_SRCS_CPP "${COMPONENT_DIR}/wasm_shims/task_scheduler_wasm.cpp")
    list(APPEND COMPONENT_SRCS_CPP "${COMPONENT_DIR}/wasm_shims/boost_json_wasm.cpp")
else()
    find_package(Boost REQUIRED COMPONENTS thread system chrono json)
endif()

option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_ENABLE_DEBUG_LOG
    "Default value of CONFIG_BROOKESIA_UTILS_ENABLE_DEBUG_LOG on PC"
    OFF
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_MEMORY_PROFILER_ENABLE_DEBUG_LOG
    "Default value of CONFIG_BROOKESIA_UTILS_MEMORY_PROFILER_ENABLE_DEBUG_LOG on PC"
    OFF
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_STATIC_MACHINE_ENABLE_DEBUG_LOG
    "Default value of CONFIG_BROOKESIA_UTILS_STATIC_MACHINE_ENABLE_DEBUG_LOG on PC"
    OFF
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_TASK_SCHEDULER_ENABLE_DEBUG_LOG
    "Default value of CONFIG_BROOKESIA_UTILS_TASK_SCHEDULER_ENABLE_DEBUG_LOG on PC"
    OFF
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_ENABLE_DEBUG_LOG
    "Default value of CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_ENABLE_DEBUG_LOG on PC"
    OFF
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_PROFILER_ENABLE_DEBUG_LOG
    "Default value of CONFIG_BROOKESIA_UTILS_THREAD_PROFILER_ENABLE_DEBUG_LOG on PC"
    OFF
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_TIME_PROFILER_ENABLE_DEBUG_LOG
    "Default value of CONFIG_BROOKESIA_UTILS_TIME_PROFILER_ENABLE_DEBUG_LOG on PC"
    OFF
)
set(
    BROOKESIA_LIB_UTILS_PC_CONFIG_CHECK_HANDLE_METHOD
    1
    CACHE STRING "Default value of CONFIG_BROOKESIA_UTILS_CHECK_HANDLE_METHOD on PC"
)
set_property(
    CACHE BROOKESIA_LIB_UTILS_PC_CONFIG_CHECK_HANDLE_METHOD
    PROPERTY STRINGS 0 1 2
)
set(
    BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_IMPL_TYPE
    0
    CACHE STRING "Default value of CONFIG_BROOKESIA_UTILS_LOG_IMPL_TYPE on PC"
)
set_property(
    CACHE BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_IMPL_TYPE
    PROPERTY STRINGS 0 1
)
set(
    BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_LEVEL
    2
    CACHE STRING "Default value of CONFIG_BROOKESIA_UTILS_LOG_LEVEL on PC"
)
set_property(
    CACHE BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_LEVEL
    PROPERTY STRINGS 0 1 2 3 4 5
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_ENABLE_THREAD_NAME
    "Default value of CONFIG_BROOKESIA_UTILS_LOG_ENABLE_THREAD_NAME on PC"
    OFF
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_ENABLE_FILE_AND_LINE
    "Default value of CONFIG_BROOKESIA_UTILS_LOG_ENABLE_FILE_AND_LINE on PC"
    ON
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_ENABLE_FUNCTION_NAME
    "Default value of CONFIG_BROOKESIA_UTILS_LOG_ENABLE_FUNCTION_NAME on PC"
    ON
)
set(
    BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_NAME
    "Thread"
    CACHE STRING "Default value of CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_NAME on PC"
)
set(
    BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_CORE_ID
    -1
    CACHE STRING "Default value of CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_CORE_ID on PC"
)
set(
    BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_PRIORITY
    5
    CACHE STRING "Default value of CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_PRIORITY on PC"
)
set(
    BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_STACK_SIZE
    4096
    CACHE STRING "Default value of CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_STACK_SIZE on PC"
)
option(
    BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_STACK_IN_EXT
    "Default value of CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_STACK_IN_EXT on PC"
    OFF
)

if(BROOKESIA_LIB_UTILS_PC_CONFIG_ENABLE_DEBUG_LOG)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_ENABLE_DEBUG_LOG=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_ENABLE_DEBUG_LOG=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_MEMORY_PROFILER_ENABLE_DEBUG_LOG)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_MEMORY_PROFILER_ENABLE_DEBUG_LOG=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_MEMORY_PROFILER_ENABLE_DEBUG_LOG=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_STATIC_MACHINE_ENABLE_DEBUG_LOG)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_STATIC_MACHINE_ENABLE_DEBUG_LOG=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_STATIC_MACHINE_ENABLE_DEBUG_LOG=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_TASK_SCHEDULER_ENABLE_DEBUG_LOG)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_TASK_SCHEDULER_ENABLE_DEBUG_LOG=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_TASK_SCHEDULER_ENABLE_DEBUG_LOG=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_ENABLE_DEBUG_LOG)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_ENABLE_DEBUG_LOG=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_ENABLE_DEBUG_LOG=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_PROFILER_ENABLE_DEBUG_LOG)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_THREAD_PROFILER_ENABLE_DEBUG_LOG=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_THREAD_PROFILER_ENABLE_DEBUG_LOG=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_TIME_PROFILER_ENABLE_DEBUG_LOG)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_TIME_PROFILER_ENABLE_DEBUG_LOG=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_TIME_PROFILER_ENABLE_DEBUG_LOG=0)
endif()

list(APPEND component_pc_config_compile_definitions
    CONFIG_BROOKESIA_UTILS_CHECK_HANDLE_METHOD=${BROOKESIA_LIB_UTILS_PC_CONFIG_CHECK_HANDLE_METHOD}
    CONFIG_BROOKESIA_UTILS_LOG_IMPL_TYPE=${BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_IMPL_TYPE}
    CONFIG_BROOKESIA_UTILS_LOG_LEVEL=${BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_LEVEL}
    "CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_NAME=\"${BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_NAME}\""
    CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_CORE_ID=${BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_CORE_ID}
    CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_PRIORITY=${BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_PRIORITY}
    CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_STACK_SIZE=${BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_STACK_SIZE}
)

if(BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_ENABLE_THREAD_NAME)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_LOG_ENABLE_THREAD_NAME=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_LOG_ENABLE_THREAD_NAME=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_ENABLE_FILE_AND_LINE)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_LOG_ENABLE_FILE_AND_LINE=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_LOG_ENABLE_FILE_AND_LINE=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_LOG_ENABLE_FUNCTION_NAME)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_LOG_ENABLE_FUNCTION_NAME=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_LOG_ENABLE_FUNCTION_NAME=0)
endif()

if(BROOKESIA_LIB_UTILS_PC_CONFIG_THREAD_CONFIG_STACK_IN_EXT)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_STACK_IN_EXT=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_UTILS_THREAD_CONFIG_STACK_IN_EXT=0)
endif()
if(BROOKESIA_LIB_UTILS_WASM_SINGLE_THREAD_SCHEDULER)
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_LIB_UTILS_WASM_SINGLE_THREAD_SCHEDULER=1)
else()
    list(APPEND component_pc_config_compile_definitions CONFIG_BROOKESIA_LIB_UTILS_WASM_SINGLE_THREAD_SCHEDULER=0)
endif()

add_library(${COMPONENT_LIB} STATIC
    ${COMPONENT_SRCS_C}
    ${COMPONENT_SRCS_CPP}
)

target_compile_features(${COMPONENT_LIB} PUBLIC cxx_std_20)
target_include_directories(${COMPONENT_LIB}
    PUBLIC
        $<$<BOOL:${EMSCRIPTEN}>:${COMPONENT_DIR}/wasm_shims>
        ${COMPONENT_INCLUDE_DIRS}
    PRIVATE
        ${COMPONENT_PRIVATE_INCLUDE_DIRS}
)
if(Boost_INCLUDE_DIRS)
    target_include_directories(${COMPONENT_LIB} PUBLIC ${Boost_INCLUDE_DIRS})
endif()

if(EMSCRIPTEN)
    target_link_options(${COMPONENT_LIB}
        PUBLIC
            -sUSE_BOOST_HEADERS=1
    )
else()
    target_link_libraries(${COMPONENT_LIB}
        PUBLIC
            Boost::thread
            Boost::system
            Boost::chrono
            Boost::json
    )
endif()

target_compile_definitions(${COMPONENT_LIB}
    PUBLIC
        ${component_pc_config_compile_definitions}
)

if(DEFINED BROOKESIA_LIB_UTILS_PC_COMPILE_DEFINITIONS AND
    NOT "${BROOKESIA_LIB_UTILS_PC_COMPILE_DEFINITIONS}" STREQUAL "")
    target_compile_definitions(${COMPONENT_LIB}
        PUBLIC
            ${BROOKESIA_LIB_UTILS_PC_COMPILE_DEFINITIONS}
    )
endif()

if(DEFINED BROOKESIA_LIB_UTILS_PC_COMPILE_OPTIONS AND
    NOT "${BROOKESIA_LIB_UTILS_PC_COMPILE_OPTIONS}" STREQUAL "")
    target_compile_options(${COMPONENT_LIB}
        PUBLIC
            ${BROOKESIA_LIB_UTILS_PC_COMPILE_OPTIONS}
    )
endif()

add_library(brookesia::lib_utils ALIAS ${COMPONENT_LIB})
