// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

// esp-brookesia: changed
#include "ui.h"

// esp-brookesia: changed
#if !defined(ESP_BROOKESIA_SQ1_4_1_LV8_3_11)
    #define _ui_screen_change(target, fademode, spd, delay, target_init) lv_scr_load_anim(*target, fademode, spd, delay, false)
#endif

///////////////////// VARIABLES ////////////////////
void upanim_Animation(lv_obj_t * TargetObject, int delay);
void hour_Animation(lv_obj_t * TargetObject, int delay);
void min_Animation(lv_obj_t * TargetObject, int delay);
void sec_Animation(lv_obj_t * TargetObject, int delay);
void scrolldot_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_SmartGadgetSplash
void ui_SmartGadgetSplash_screen_init(void);
void ui_event_SmartGadgetSplash(lv_event_t * e);
lv_obj_t * ui_SmartGadgetSplash;
lv_obj_t * ui_SmartGadgetSplash_Small_label_Demo;
lv_obj_t * ui_SmartGadgetSplash_Small_label_Smart_Gadget;
lv_obj_t * ui_SmartGadgetSplash_Image_SLS_Logo;


// SCREEN: ui_SmartGadgetClock
void ui_SmartGadgetClock_screen_init(void);
void ui_event_SmartGadgetClock(lv_event_t * e);
lv_obj_t * ui_SmartGadgetClock;
lv_obj_t * ui_SmartGadgetClock_Panel_Clock_Panel;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot1;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot2;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot3;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot4;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot5;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot6;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot7;
lv_obj_t * ui_SmartGadgetClock_Clock_dot_Dot8;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number1;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number2;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number3;
lv_obj_t * ui_SmartGadgetClock_Small_label_Clock_Number4;
lv_obj_t * ui_SmartGadgetClock_Image_Min;
lv_obj_t * ui_SmartGadgetClock_Image_Hour;
lv_obj_t * ui_SmartGadgetClock_Image_Sec;
lv_obj_t * ui_SmartGadgetClock_Panel_Clock_Center;
lv_obj_t * ui_SmartGadgetClock_Label_Clock_Number;
lv_obj_t * ui_SmartGadgetClock_Small_label_Date;
lv_obj_t * ui_SmartGadgetClock_Scrolldots_Scrolldots;


// SCREEN: ui_SmartGadgetCall
void ui_SmartGadgetCall_screen_init(void);
void ui_event_SmartGadgetCall(lv_event_t * e);
lv_obj_t * ui_SmartGadgetCall;
lv_obj_t * ui_SmartGadgetCall_Small_label_Elena;
lv_obj_t * ui_SmartGadgetCall_Small_label_Incoming;
lv_obj_t * ui_SmartGadgetCall_Panel_Call_Incon1;
lv_obj_t * ui_SmartGadgetCall_Image_Phone1;
lv_obj_t * ui_SmartGadgetCall_Panel_Call_Incon2;
lv_obj_t * ui_SmartGadgetCall_Image_Phone2;
lv_obj_t * ui_SmartGadgetCall_Image_Avatar;
lv_obj_t * ui_SmartGadgetCall_Scrolldots_Scrolldots1;


// SCREEN: ui_SmartGadgetChat
void ui_SmartGadgetChat_screen_init(void);
void ui_event_SmartGadgetChat(lv_event_t * e);
lv_obj_t * ui_SmartGadgetChat;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_container;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat_date;
lv_obj_t * ui_SmartGadgetChat_Panel_C1;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_Panel1;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat1;
lv_obj_t * ui_SmartGadgetChat_Image_Chat_Icon1;
lv_obj_t * ui_SmartGadgetChat_Panel_C2;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_Panel2;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat2;
lv_obj_t * ui_SmartGadgetChat_Image_Chat_Icon2;
lv_obj_t * ui_SmartGadgetChat_Small_label_Delifered;
lv_obj_t * ui_SmartGadgetChat_Panel_C3;
lv_obj_t * ui_SmartGadgetChat_Panel_Chat_Panel3;
lv_obj_t * ui_SmartGadgetChat_Small_label_Chat3;
lv_obj_t * ui_SmartGadgetChat_Image_Chat_Icon3;
lv_obj_t * ui_SmartGadgetChat_Scrolldots_Scrolldots2;


// SCREEN: ui_SmartGadgetMusicPlayer
void ui_SmartGadgetMusicPlayer_screen_init(void);
void ui_event_SmartGadgetMusicPlayer(lv_event_t * e);
lv_obj_t * ui_SmartGadgetMusicPlayer;
lv_obj_t * ui_SmartGadgetMusicPlayer_Small_label_Music_Title;
lv_obj_t * ui_SmartGadgetMusicPlayer_Small_label_Author;
lv_obj_t * ui_SmartGadgetMusicPlayer_Panel_Play_btn;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Play;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Album;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Backward;
lv_obj_t * ui_SmartGadgetMusicPlayer_Image_Forward;
lv_obj_t * ui_SmartGadgetMusicPlayer_Scrolldots_Scrolldots3;


// SCREEN: ui_SmartGadgetWeather
void ui_SmartGadgetWeather_screen_init(void);
void ui_event_SmartGadgetWeather(lv_event_t * e);
lv_obj_t * ui_SmartGadgetWeather;
lv_obj_t * ui_SmartGadgetWeather_Small_label_Pary_Cloud;
lv_obj_t * ui_SmartGadgetWeather_Small_label_New_York;
lv_obj_t * ui_SmartGadgetWeather_Image_Cloud;
lv_obj_t * ui_SmartGadgetWeather_Label_Celsius;
lv_obj_t * ui_SmartGadgetWeather_Panel_Weather_Icons;
lv_obj_t * ui_SmartGadgetWeather_Image_w1;
lv_obj_t * ui_SmartGadgetWeather_Image_w2;
lv_obj_t * ui_SmartGadgetWeather_Image_w3;
lv_obj_t * ui_SmartGadgetWeather_Small_label_W1_Num;
lv_obj_t * ui_SmartGadgetWeather_Small_label_W2_Num;
lv_obj_t * ui_SmartGadgetWeather_Small_label_W3_Num;
lv_obj_t * ui_SmartGadgetWeather_Scrolldots_Scrolldots4;


// SCREEN: ui_SmartGadgetAlarm
void ui_SmartGadgetAlarm_screen_init(void);
void ui_event_SmartGadgetAlarm(lv_event_t * e);
lv_obj_t * ui_SmartGadgetAlarm;
lv_obj_t * ui_SmartGadgetAlarm_Panel_Alarm_container;
lv_obj_t * ui_SmartGadgetAlarm_Small_label_Set_alarm;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp1;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp2;
lv_obj_t * ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp3;
lv_obj_t * ui_SmartGadgetAlarm_Scrolldots_Scrolldots5;
const lv_img_dsc_t * ui_imgset_chatbox[1] = {&ui_img_chatbox2_png};
const lv_img_dsc_t * ui_imgset_weather_[3] = {&ui_img_weather_1_png, &ui_img_weather_2_png, &ui_img_weather_3_png};

///////////////////// ANIMATIONS ////////////////////
// esp-brookesia: changed

///////////////////// FUNCTIONS ////////////////////
void ui_event_SmartGadgetSplash(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetSplash_Image_SLS_Logo, 100);
        upanim_Animation(ui_SmartGadgetSplash_Small_label_Smart_Gadget, 200);
        upanim_Animation(ui_SmartGadgetSplash_Small_label_Demo, 300);
        _ui_screen_change(&ui_SmartGadgetClock, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1400, &ui_SmartGadgetClock_screen_init);
    }
}
void ui_event_SmartGadgetClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        upanim_Animation(ui_SmartGadgetClock_Panel_Clock_Panel, 100);
        upanim_Animation(ui_SmartGadgetClock_Label_Clock_Number, 300);
        upanim_Animation(ui_SmartGadgetClock_Small_label_Date, 200);
        scrolldot_Animation(ui_SmartGadgetClock_Scrolldots_Scrolldots, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetCall, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_SmartGadgetCall_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetAlarm_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        hour_Animation(ui_SmartGadgetClock_Image_Hour, 200);
        min_Animation(ui_SmartGadgetClock_Image_Min, 400);
    }
}
void ui_event_SmartGadgetCall(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetCall_Image_Avatar, 100);
        upanim_Animation(ui_SmartGadgetCall_Small_label_Elena, 200);
        upanim_Animation(ui_SmartGadgetCall_Small_label_Incoming, 300);
        upanim_Animation(ui_SmartGadgetCall_Panel_Call_Incon1, 200);
        upanim_Animation(ui_SmartGadgetCall_Panel_Call_Incon2, 300);
        scrolldot_Animation(ui_SmartGadgetCall_Scrolldots_Scrolldots1, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetChat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetChat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetClock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetClock_screen_init);
    }
}
void ui_event_SmartGadgetChat(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetChat_Small_label_Chat_date, 100);
        upanim_Animation(ui_SmartGadgetChat_Panel_C1, 200);
        upanim_Animation(ui_SmartGadgetChat_Panel_C2, 300);
        upanim_Animation(ui_SmartGadgetChat_Panel_C3, 400);
        scrolldot_Animation(ui_SmartGadgetChat_Scrolldots_Scrolldots2, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetCall, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetCall_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetMusicPlayer, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetMusicPlayer_screen_init);
    }
}
void ui_event_SmartGadgetMusicPlayer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetMusicPlayer_Image_Album, 100);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Small_label_Music_Title, 200);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Small_label_Author, 300);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Panel_Play_btn, 200);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Image_Forward, 300);
        upanim_Animation(ui_SmartGadgetMusicPlayer_Image_Backward, 400);
        scrolldot_Animation(ui_SmartGadgetMusicPlayer_Scrolldots_Scrolldots3, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetChat, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetChat_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetWeather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetWeather_screen_init);
    }
}
void ui_event_SmartGadgetWeather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetWeather_Image_Cloud, 100);
        upanim_Animation(ui_SmartGadgetWeather_Small_label_Pary_Cloud, 200);
        upanim_Animation(ui_SmartGadgetWeather_Label_Celsius, 300);
        upanim_Animation(ui_SmartGadgetWeather_Small_label_New_York, 400);
        upanim_Animation(ui_SmartGadgetWeather_Panel_Weather_Icons, 300);
        scrolldot_Animation(ui_SmartGadgetWeather_Scrolldots_Scrolldots4, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetMusicPlayer, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetMusicPlayer_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetAlarm, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetAlarm_screen_init);
    }
}
void ui_event_SmartGadgetAlarm(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        upanim_Animation(ui_SmartGadgetAlarm_Small_label_Set_alarm, 100);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp, 200);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp1, 300);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp2, 400);
        upanim_Animation(ui_SmartGadgetAlarm_Alarm_comp_Alarm_Comp3, 500);
        scrolldot_Animation(ui_SmartGadgetAlarm_Scrolldots_Scrolldots5, 0);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetWeather, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetWeather_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SmartGadgetClock, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SmartGadgetClock_screen_init);
    }
}
void ui_event_Startevents____initial_actions0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        sec_Animation(ui_SmartGadgetClock_Image_Sec, 0);
    }
}

///////////////////// SCREENS ////////////////////

// esp-brookesia: changed
void phone_app_squareline_ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_basic_init(dispp);
    lv_disp_set_theme(dispp, theme);
    ui_SmartGadgetSplash_screen_init();
    ui_SmartGadgetClock_screen_init();
    ui_SmartGadgetCall_screen_init();
    ui_SmartGadgetChat_screen_init();
    ui_SmartGadgetMusicPlayer_screen_init();
    ui_SmartGadgetWeather_screen_init();
    ui_SmartGadgetAlarm_screen_init();
    lv_disp_load_scr(ui_SmartGadgetSplash);
}
