// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t * ui_Screen_watch_digital = NULL;
lv_obj_t * ui_watch_digital_Label_label_min = NULL;
lv_obj_t * ui_watch_digital_Label_label_hour = NULL;
lv_obj_t * ui_watch_digital_Label_year1 = NULL;
lv_obj_t * ui_watch_digital_Label_month1 = NULL;
lv_obj_t * ui_watch_digital_Label_day1 = NULL;
lv_obj_t * ui_watch_digital_Panel_battery_group2 = NULL;
lv_obj_t * ui_watch_digital_Image_flash1 = NULL;
lv_obj_t * ui_watch_digital_Label_battery_percent1 = NULL;
lv_obj_t * ui_watch_digital_Panel_step_group1 = NULL;
lv_obj_t * ui_watch_digital_Image_step1 = NULL;
lv_obj_t * ui_watch_digital_Label_step_label1 = NULL;
lv_obj_t * ui_watch_digital_Panel_daily_mission_group2 = NULL;
lv_obj_t * ui_watch_digital_Label_mission_percent1 = NULL;
lv_obj_t * ui_watch_digital_Image_daily_mission_image1 = NULL;
lv_obj_t * ui_watch_digital_Arc_daily_mission_arc1 = NULL;
lv_obj_t * ui_watch_digital_Image_sec_dot = NULL;
// event funtions
void ui_event_watch_digital_Arc_daily_mission_arc1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_watch_digital_Label_mission_percent1, target, "", "%");
    }
}

// build funtions

void ui_Screen_watch_digital_screen_init(void)
{
    ui_Screen_watch_digital = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_watch_digital, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_watch_digital, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_watch_digital, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Label_label_min = lv_label_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Label_label_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Label_label_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Label_label_min, 210);
    lv_obj_set_y(ui_watch_digital_Label_label_min, 140);
    lv_label_set_text(ui_watch_digital_Label_label_min, "27");
    lv_obj_set_style_text_color(ui_watch_digital_Label_label_min, lv_color_hex(0xEE1E1E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_label_min, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_label_min, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_watch_digital_Label_label_min, 400, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Label_label_hour = lv_label_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Label_label_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Label_label_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Label_label_hour, 100);
    lv_obj_set_y(ui_watch_digital_Label_label_hour, 120);
    lv_label_set_text(ui_watch_digital_Label_label_hour, "03");
    lv_obj_set_style_text_color(ui_watch_digital_Label_label_hour, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_label_hour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_label_hour, &lv_font_montserrat_40,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_scale(ui_watch_digital_Label_label_hour, 500, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Label_year1 = lv_label_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Label_year1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Label_year1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Label_year1, 90);
    lv_obj_set_y(ui_watch_digital_Label_year1, -78);
    lv_obj_set_align(ui_watch_digital_Label_year1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_digital_Label_year1, "2022");
    lv_obj_set_style_text_color(ui_watch_digital_Label_year1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_year1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_year1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Label_month1 = lv_label_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Label_month1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Label_month1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Label_month1, 20);
    lv_obj_set_y(ui_watch_digital_Label_month1, -80);
    lv_obj_set_align(ui_watch_digital_Label_month1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_digital_Label_month1, "18 FEB");
    lv_obj_set_style_text_color(ui_watch_digital_Label_month1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_month1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_month1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Label_day1 = lv_label_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Label_day1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Label_day1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Label_day1, -70);
    lv_obj_set_y(ui_watch_digital_Label_day1, -80);
    lv_obj_set_align(ui_watch_digital_Label_day1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_digital_Label_day1, "MON");
    lv_obj_set_style_text_color(ui_watch_digital_Label_day1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_day1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_day1, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Panel_battery_group2 = lv_obj_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Panel_battery_group2, 77);
    lv_obj_set_height(ui_watch_digital_Panel_battery_group2, 22);
    lv_obj_set_x(ui_watch_digital_Panel_battery_group2, 0);
    lv_obj_set_y(ui_watch_digital_Panel_battery_group2, 20);
    lv_obj_set_align(ui_watch_digital_Panel_battery_group2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_watch_digital_Panel_battery_group2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_watch_digital_Panel_battery_group2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_watch_digital_Panel_battery_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_digital_Panel_battery_group2, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_digital_Panel_battery_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_digital_Panel_battery_group2, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_digital_Panel_battery_group2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_digital_Panel_battery_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_watch_digital_Panel_battery_group2, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_watch_digital_Panel_battery_group2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Image_flash1 = lv_image_create(ui_watch_digital_Panel_battery_group2);
    lv_image_set_src(ui_watch_digital_Image_flash1, &ui_img_flash_png);
    lv_obj_set_width(ui_watch_digital_Image_flash1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Image_flash1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_digital_Image_flash1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_digital_Image_flash1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_digital_Image_flash1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_watch_digital_Label_battery_percent1 = lv_label_create(ui_watch_digital_Panel_battery_group2);
    lv_obj_set_width(ui_watch_digital_Label_battery_percent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Label_battery_percent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_digital_Label_battery_percent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_digital_Label_battery_percent1, "86%");
    lv_obj_set_style_text_color(ui_watch_digital_Label_battery_percent1, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_battery_percent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_battery_percent1, &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Panel_step_group1 = lv_obj_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Panel_step_group1, 100);
    lv_obj_set_height(ui_watch_digital_Panel_step_group1, 26);
    lv_obj_set_x(ui_watch_digital_Panel_step_group1, 0);
    lv_obj_set_y(ui_watch_digital_Panel_step_group1, -40);
    lv_obj_set_align(ui_watch_digital_Panel_step_group1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_watch_digital_Panel_step_group1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_watch_digital_Panel_step_group1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_watch_digital_Panel_step_group1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_digital_Panel_step_group1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_digital_Panel_step_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_digital_Panel_step_group1, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_digital_Panel_step_group1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_digital_Panel_step_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_watch_digital_Panel_step_group1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_watch_digital_Panel_step_group1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Image_step1 = lv_image_create(ui_watch_digital_Panel_step_group1);
    lv_image_set_src(ui_watch_digital_Image_step1, &ui_img_step_png);
    lv_obj_set_width(ui_watch_digital_Image_step1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Image_step1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_digital_Image_step1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_digital_Image_step1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_digital_Image_step1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_watch_digital_Label_step_label1 = lv_label_create(ui_watch_digital_Panel_step_group1);
    lv_obj_set_width(ui_watch_digital_Label_step_label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Label_step_label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Label_step_label1, 2);
    lv_obj_set_y(ui_watch_digital_Label_step_label1, -4);
    lv_obj_set_align(ui_watch_digital_Label_step_label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_digital_Label_step_label1, "1526");
    lv_obj_set_style_text_color(ui_watch_digital_Label_step_label1, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_step_label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_step_label1, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Panel_daily_mission_group2 = lv_obj_create(ui_Screen_watch_digital);
    lv_obj_set_width(ui_watch_digital_Panel_daily_mission_group2, 283);
    lv_obj_set_height(ui_watch_digital_Panel_daily_mission_group2, 185);
    lv_obj_set_align(ui_watch_digital_Panel_daily_mission_group2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_watch_digital_Panel_daily_mission_group2,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_digital_Panel_daily_mission_group2, lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_digital_Panel_daily_mission_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_digital_Panel_daily_mission_group2, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_digital_Panel_daily_mission_group2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_digital_Panel_daily_mission_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Label_mission_percent1 = lv_label_create(ui_watch_digital_Panel_daily_mission_group2);
    lv_obj_set_width(ui_watch_digital_Label_mission_percent1, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_watch_digital_Label_mission_percent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Label_mission_percent1, 85);
    lv_obj_set_y(ui_watch_digital_Label_mission_percent1, -70);
    lv_obj_set_align(ui_watch_digital_Label_mission_percent1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_watch_digital_Label_mission_percent1, "87%");
    lv_obj_set_style_text_color(ui_watch_digital_Label_mission_percent1, lv_color_hex(0xB0E14A),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_digital_Label_mission_percent1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_digital_Label_mission_percent1, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_digital_Image_daily_mission_image1 = lv_image_create(ui_watch_digital_Panel_daily_mission_group2);
    lv_image_set_src(ui_watch_digital_Image_daily_mission_image1, &ui_img_daily_mission_png);
    lv_obj_set_width(ui_watch_digital_Image_daily_mission_image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Image_daily_mission_image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Image_daily_mission_image1, -57);
    lv_obj_set_y(ui_watch_digital_Image_daily_mission_image1, 16);
    lv_obj_set_align(ui_watch_digital_Image_daily_mission_image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_digital_Image_daily_mission_image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_digital_Image_daily_mission_image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_watch_digital_Image_daily_mission_image1, -120);

    ui_watch_digital_Arc_daily_mission_arc1 = lv_arc_create(ui_watch_digital_Panel_daily_mission_group2);
    lv_obj_set_width(ui_watch_digital_Arc_daily_mission_arc1, 330);
    lv_obj_set_height(ui_watch_digital_Arc_daily_mission_arc1, 330);
    lv_obj_set_x(ui_watch_digital_Arc_daily_mission_arc1, 33);
    lv_obj_set_y(ui_watch_digital_Arc_daily_mission_arc1, -87);
    lv_obj_set_align(ui_watch_digital_Arc_daily_mission_arc1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_digital_Arc_daily_mission_arc1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_arc_set_value(ui_watch_digital_Arc_daily_mission_arc1, 87);
    lv_arc_set_bg_angles(ui_watch_digital_Arc_daily_mission_arc1, 88, 170);
    lv_obj_set_style_arc_color(ui_watch_digital_Arc_daily_mission_arc1, lv_color_hex(0x303030),
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_watch_digital_Arc_daily_mission_arc1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_watch_digital_Arc_daily_mission_arc1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_watch_digital_Arc_daily_mission_arc1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_watch_digital_Arc_daily_mission_arc1, lv_color_hex(0xB0E14A),
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_watch_digital_Arc_daily_mission_arc1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_watch_digital_Arc_daily_mission_arc1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_watch_digital_Arc_daily_mission_arc1, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_watch_digital_Arc_daily_mission_arc1, lv_color_hex(0xFFFFFF),
                              LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_digital_Arc_daily_mission_arc1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_watch_digital_Image_sec_dot = lv_image_create(ui_Screen_watch_digital);
    lv_image_set_src(ui_watch_digital_Image_sec_dot, &ui_img_sec_dot_png);
    lv_obj_set_width(ui_watch_digital_Image_sec_dot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_digital_Image_sec_dot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_digital_Image_sec_dot, 10);
    lv_obj_set_y(ui_watch_digital_Image_sec_dot, 15);
    lv_obj_set_align(ui_watch_digital_Image_sec_dot, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_digital_Image_sec_dot, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_digital_Image_sec_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_watch_digital_Image_sec_dot, 4, 194);

    lv_obj_add_event_cb(ui_watch_digital_Arc_daily_mission_arc1, ui_event_watch_digital_Arc_daily_mission_arc1,
                        LV_EVENT_ALL, NULL);

}

void ui_Screen_watch_digital_screen_destroy(void)
{
    if(ui_Screen_watch_digital) lv_obj_del(ui_Screen_watch_digital);

    // NULL screen variables
    ui_Screen_watch_digital = NULL;
    ui_watch_digital_Label_label_min = NULL;
    ui_watch_digital_Label_label_hour = NULL;
    ui_watch_digital_Label_year1 = NULL;
    ui_watch_digital_Label_month1 = NULL;
    ui_watch_digital_Label_day1 = NULL;
    ui_watch_digital_Panel_battery_group2 = NULL;
    ui_watch_digital_Image_flash1 = NULL;
    ui_watch_digital_Label_battery_percent1 = NULL;
    ui_watch_digital_Panel_step_group1 = NULL;
    ui_watch_digital_Image_step1 = NULL;
    ui_watch_digital_Label_step_label1 = NULL;
    ui_watch_digital_Panel_daily_mission_group2 = NULL;
    ui_watch_digital_Label_mission_percent1 = NULL;
    ui_watch_digital_Image_daily_mission_image1 = NULL;
    ui_watch_digital_Arc_daily_mission_arc1 = NULL;
    ui_watch_digital_Image_sec_dot = NULL;

}
