// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef UI_SCREEN_WATCH_ANALOG_H
#define UI_SCREEN_WATCH_ANALOG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_watch_analog
extern void ui_Screen_watch_analog_screen_init(void);
extern void ui_Screen_watch_analog_screen_destroy(void);
extern lv_obj_t * ui_Screen_watch_analog;
extern lv_obj_t * ui_watch_analog_Label_clock;
extern lv_obj_t * ui_watch_analog_Panel_battery_group3;
extern lv_obj_t * ui_watch_analog_Image_flash2;
extern lv_obj_t * ui_watch_analog_Label_battery_percent2;
extern lv_obj_t * ui_watch_analog_Panel_date_group2;
extern lv_obj_t * ui_watch_analog_Label_day2;
extern lv_obj_t * ui_watch_analog_Label_month2;
extern lv_obj_t * ui_watch_analog_Label_year2;
extern lv_obj_t * ui_watch_analog_Panel_step_group3;
extern lv_obj_t * ui_watch_analog_Image_step2;
extern lv_obj_t * ui_watch_analog_Label_step_label2;
extern lv_obj_t * ui_watch_analog_Panel_daily_mission_group3;
extern lv_obj_t * ui_watch_analog_Label_mission_percent2;
extern lv_obj_t * ui_watch_analog_Image_daily_mission_image2;
extern void ui_event_watch_analog_Arc_daily_mission_arc2(lv_event_t * e);
extern lv_obj_t * ui_watch_analog_Arc_daily_mission_arc2;
extern lv_obj_t * ui_watch_analog_Panel_clock_group;
extern lv_obj_t * ui_watch_analog_Image_sec;
extern lv_obj_t * ui_watch_analog_Image_min;
extern lv_obj_t * ui_watch_analog_Image_hour;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

