// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#include "../ui.h"

lv_obj_t * ui_Screen_watch_analog = NULL;
lv_obj_t * ui_watch_analog_Label_clock = NULL;
lv_obj_t * ui_watch_analog_Panel_battery_group3 = NULL;
lv_obj_t * ui_watch_analog_Image_flash2 = NULL;
lv_obj_t * ui_watch_analog_Label_battery_percent2 = NULL;
lv_obj_t * ui_watch_analog_Panel_date_group2 = NULL;
lv_obj_t * ui_watch_analog_Label_day2 = NULL;
lv_obj_t * ui_watch_analog_Label_month2 = NULL;
lv_obj_t * ui_watch_analog_Label_year2 = NULL;
lv_obj_t * ui_watch_analog_Panel_step_group3 = NULL;
lv_obj_t * ui_watch_analog_Image_step2 = NULL;
lv_obj_t * ui_watch_analog_Label_step_label2 = NULL;
lv_obj_t * ui_watch_analog_Panel_daily_mission_group3 = NULL;
lv_obj_t * ui_watch_analog_Label_mission_percent2 = NULL;
lv_obj_t * ui_watch_analog_Image_daily_mission_image2 = NULL;
lv_obj_t * ui_watch_analog_Arc_daily_mission_arc2 = NULL;
lv_obj_t * ui_watch_analog_Panel_clock_group = NULL;
lv_obj_t * ui_watch_analog_Image_sec = NULL;
lv_obj_t * ui_watch_analog_Image_min = NULL;
lv_obj_t * ui_watch_analog_Image_hour = NULL;
// event funtions
void ui_event_watch_analog_Arc_daily_mission_arc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_watch_analog_Label_mission_percent2, target, "", "%");
    }
}

// build funtions

void ui_Screen_watch_analog_screen_init(void)
{
    ui_Screen_watch_analog = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_watch_analog, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_watch_analog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_watch_analog, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Label_clock = lv_label_create(ui_Screen_watch_analog);
    lv_obj_set_width(ui_watch_analog_Label_clock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Label_clock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Label_clock, 0);
    lv_obj_set_y(ui_watch_analog_Label_clock, 75);
    lv_obj_set_align(ui_watch_analog_Label_clock, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_watch_analog_Label_clock, "03   27");
    lv_obj_set_style_text_color(ui_watch_analog_Label_clock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_analog_Label_clock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_analog_Label_clock, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Panel_battery_group3 = lv_obj_create(ui_Screen_watch_analog);
    lv_obj_set_width(ui_watch_analog_Panel_battery_group3, 77);
    lv_obj_set_height(ui_watch_analog_Panel_battery_group3, 22);
    lv_obj_set_x(ui_watch_analog_Panel_battery_group3, 0);
    lv_obj_set_y(ui_watch_analog_Panel_battery_group3, 20);
    lv_obj_set_align(ui_watch_analog_Panel_battery_group3, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_watch_analog_Panel_battery_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_watch_analog_Panel_battery_group3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_watch_analog_Panel_battery_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_analog_Panel_battery_group3, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog_Panel_battery_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_analog_Panel_battery_group3, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_analog_Panel_battery_group3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_analog_Panel_battery_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_watch_analog_Panel_battery_group3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_watch_analog_Panel_battery_group3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Image_flash2 = lv_image_create(ui_watch_analog_Panel_battery_group3);
    lv_image_set_src(ui_watch_analog_Image_flash2, &ui_img_flash_png);
    lv_obj_set_width(ui_watch_analog_Image_flash2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Image_flash2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_analog_Image_flash2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_analog_Image_flash2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_analog_Image_flash2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_watch_analog_Label_battery_percent2 = lv_label_create(ui_watch_analog_Panel_battery_group3);
    lv_obj_set_width(ui_watch_analog_Label_battery_percent2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Label_battery_percent2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_analog_Label_battery_percent2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_analog_Label_battery_percent2, "86%");
    lv_obj_set_style_text_color(ui_watch_analog_Label_battery_percent2, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_analog_Label_battery_percent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_analog_Label_battery_percent2, &lv_font_montserrat_24,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Panel_date_group2 = lv_obj_create(ui_Screen_watch_analog);
    lv_obj_set_width(ui_watch_analog_Panel_date_group2, 100);
    lv_obj_set_height(ui_watch_analog_Panel_date_group2, 130);
    lv_obj_set_x(ui_watch_analog_Panel_date_group2, 88);
    lv_obj_set_y(ui_watch_analog_Panel_date_group2, 134);
    lv_obj_set_align(ui_watch_analog_Panel_date_group2, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_watch_analog_Panel_date_group2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_watch_analog_Panel_date_group2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_watch_analog_Panel_date_group2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_analog_Panel_date_group2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog_Panel_date_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_analog_Panel_date_group2, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_analog_Panel_date_group2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_analog_Panel_date_group2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Label_day2 = lv_label_create(ui_watch_analog_Panel_date_group2);
    lv_obj_set_width(ui_watch_analog_Label_day2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Label_day2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_analog_Label_day2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_analog_Label_day2, "MON");
    lv_obj_set_style_text_color(ui_watch_analog_Label_day2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_analog_Label_day2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_analog_Label_day2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Label_month2 = lv_label_create(ui_watch_analog_Panel_date_group2);
    lv_obj_set_width(ui_watch_analog_Label_month2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Label_month2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_analog_Label_month2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_analog_Label_month2, "18 FEB");
    lv_obj_set_style_text_color(ui_watch_analog_Label_month2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_analog_Label_month2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_analog_Label_month2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Label_year2 = lv_label_create(ui_watch_analog_Panel_date_group2);
    lv_obj_set_width(ui_watch_analog_Label_year2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Label_year2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Label_year2, -7);
    lv_obj_set_y(ui_watch_analog_Label_year2, 0);
    lv_obj_set_align(ui_watch_analog_Label_year2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_analog_Label_year2, "2022");
    lv_obj_set_style_text_color(ui_watch_analog_Label_year2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_analog_Label_year2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_analog_Label_year2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Panel_step_group3 = lv_obj_create(ui_Screen_watch_analog);
    lv_obj_set_width(ui_watch_analog_Panel_step_group3, 100);
    lv_obj_set_height(ui_watch_analog_Panel_step_group3, 26);
    lv_obj_set_x(ui_watch_analog_Panel_step_group3, 0);
    lv_obj_set_y(ui_watch_analog_Panel_step_group3, -40);
    lv_obj_set_align(ui_watch_analog_Panel_step_group3, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_watch_analog_Panel_step_group3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_watch_analog_Panel_step_group3, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_watch_analog_Panel_step_group3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_analog_Panel_step_group3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog_Panel_step_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_analog_Panel_step_group3, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_analog_Panel_step_group3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_analog_Panel_step_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_watch_analog_Panel_step_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_watch_analog_Panel_step_group3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Image_step2 = lv_image_create(ui_watch_analog_Panel_step_group3);
    lv_image_set_src(ui_watch_analog_Image_step2, &ui_img_step_png);
    lv_obj_set_width(ui_watch_analog_Image_step2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Image_step2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_watch_analog_Image_step2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_analog_Image_step2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_analog_Image_step2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_watch_analog_Label_step_label2 = lv_label_create(ui_watch_analog_Panel_step_group3);
    lv_obj_set_width(ui_watch_analog_Label_step_label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Label_step_label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Label_step_label2, 2);
    lv_obj_set_y(ui_watch_analog_Label_step_label2, -4);
    lv_obj_set_align(ui_watch_analog_Label_step_label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_watch_analog_Label_step_label2, "1526");
    lv_obj_set_style_text_color(ui_watch_analog_Label_step_label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_analog_Label_step_label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_analog_Label_step_label2, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Panel_daily_mission_group3 = lv_obj_create(ui_Screen_watch_analog);
    lv_obj_set_width(ui_watch_analog_Panel_daily_mission_group3, 283);
    lv_obj_set_height(ui_watch_analog_Panel_daily_mission_group3, 185);
    lv_obj_set_align(ui_watch_analog_Panel_daily_mission_group3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_watch_analog_Panel_daily_mission_group3,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_analog_Panel_daily_mission_group3, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog_Panel_daily_mission_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_analog_Panel_daily_mission_group3, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_analog_Panel_daily_mission_group3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_analog_Panel_daily_mission_group3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Label_mission_percent2 = lv_label_create(ui_watch_analog_Panel_daily_mission_group3);
    lv_obj_set_width(ui_watch_analog_Label_mission_percent2, LV_SIZE_CONTENT);   /// 90
    lv_obj_set_height(ui_watch_analog_Label_mission_percent2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Label_mission_percent2, 85);
    lv_obj_set_y(ui_watch_analog_Label_mission_percent2, -70);
    lv_obj_set_align(ui_watch_analog_Label_mission_percent2, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_watch_analog_Label_mission_percent2, "87%");
    lv_obj_set_style_text_color(ui_watch_analog_Label_mission_percent2, lv_color_hex(0xB0E14A),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_watch_analog_Label_mission_percent2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_watch_analog_Label_mission_percent2, &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Image_daily_mission_image2 = lv_image_create(ui_watch_analog_Panel_daily_mission_group3);
    lv_image_set_src(ui_watch_analog_Image_daily_mission_image2, &ui_img_daily_mission_png);
    lv_obj_set_width(ui_watch_analog_Image_daily_mission_image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Image_daily_mission_image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Image_daily_mission_image2, -57);
    lv_obj_set_y(ui_watch_analog_Image_daily_mission_image2, 16);
    lv_obj_set_align(ui_watch_analog_Image_daily_mission_image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_analog_Image_daily_mission_image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_analog_Image_daily_mission_image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_watch_analog_Image_daily_mission_image2, -120);

    ui_watch_analog_Arc_daily_mission_arc2 = lv_arc_create(ui_watch_analog_Panel_daily_mission_group3);
    lv_obj_set_width(ui_watch_analog_Arc_daily_mission_arc2, 330);
    lv_obj_set_height(ui_watch_analog_Arc_daily_mission_arc2, 330);
    lv_obj_set_x(ui_watch_analog_Arc_daily_mission_arc2, 33);
    lv_obj_set_y(ui_watch_analog_Arc_daily_mission_arc2, -87);
    lv_obj_set_align(ui_watch_analog_Arc_daily_mission_arc2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_analog_Arc_daily_mission_arc2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_arc_set_value(ui_watch_analog_Arc_daily_mission_arc2, 87);
    lv_arc_set_bg_angles(ui_watch_analog_Arc_daily_mission_arc2, 88, 170);
    lv_obj_set_style_arc_color(ui_watch_analog_Arc_daily_mission_arc2, lv_color_hex(0x303030),
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_watch_analog_Arc_daily_mission_arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_watch_analog_Arc_daily_mission_arc2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_watch_analog_Arc_daily_mission_arc2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_watch_analog_Arc_daily_mission_arc2, lv_color_hex(0xB0E14A),
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_watch_analog_Arc_daily_mission_arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_watch_analog_Arc_daily_mission_arc2, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_rounded(ui_watch_analog_Arc_daily_mission_arc2, true, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_watch_analog_Arc_daily_mission_arc2, lv_color_hex(0xFFFFFF),
                              LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog_Arc_daily_mission_arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_watch_analog_Panel_clock_group = lv_obj_create(ui_Screen_watch_analog);
    lv_obj_set_width(ui_watch_analog_Panel_clock_group, 350);
    lv_obj_set_height(ui_watch_analog_Panel_clock_group, 350);
    lv_obj_set_align(ui_watch_analog_Panel_clock_group, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_watch_analog_Panel_clock_group, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_watch_analog_Panel_clock_group, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_watch_analog_Panel_clock_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_watch_analog_Panel_clock_group, lv_color_hex(0x000000),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_watch_analog_Panel_clock_group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_watch_analog_Panel_clock_group, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_watch_analog_Image_sec = lv_image_create(ui_watch_analog_Panel_clock_group);
    lv_image_set_src(ui_watch_analog_Image_sec, &ui_img_clockwise_sec_png);
    lv_obj_set_width(ui_watch_analog_Image_sec, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Image_sec, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Image_sec, 0);
    lv_obj_set_y(ui_watch_analog_Image_sec, -67);
    lv_obj_set_align(ui_watch_analog_Image_sec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_analog_Image_sec, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_analog_Image_sec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_watch_analog_Image_sec, 15, 155);
    lv_image_set_rotation(ui_watch_analog_Image_sec, 12000);

    ui_watch_analog_Image_min = lv_image_create(ui_watch_analog_Panel_clock_group);
    lv_image_set_src(ui_watch_analog_Image_min, &ui_img_clockwise_min_png);
    lv_obj_set_width(ui_watch_analog_Image_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Image_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Image_min, 0);
    lv_obj_set_y(ui_watch_analog_Image_min, -75);
    lv_obj_set_align(ui_watch_analog_Image_min, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_analog_Image_min, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_analog_Image_min, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_watch_analog_Image_min, 9, 153);

    ui_watch_analog_Image_hour = lv_image_create(ui_watch_analog_Panel_clock_group);
    lv_image_set_src(ui_watch_analog_Image_hour, &ui_img_clockwise_hour_png);
    lv_obj_set_width(ui_watch_analog_Image_hour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_watch_analog_Image_hour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_watch_analog_Image_hour, 0);
    lv_obj_set_y(ui_watch_analog_Image_hour, -45);
    lv_obj_set_align(ui_watch_analog_Image_hour, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_watch_analog_Image_hour, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_watch_analog_Image_hour, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_watch_analog_Image_hour, 9, 93);

    lv_obj_add_event_cb(ui_watch_analog_Arc_daily_mission_arc2, ui_event_watch_analog_Arc_daily_mission_arc2, LV_EVENT_ALL,
                        NULL);

}

void ui_Screen_watch_analog_screen_destroy(void)
{
    if(ui_Screen_watch_analog) lv_obj_del(ui_Screen_watch_analog);

    // NULL screen variables
    ui_Screen_watch_analog = NULL;
    ui_watch_analog_Label_clock = NULL;
    ui_watch_analog_Panel_battery_group3 = NULL;
    ui_watch_analog_Image_flash2 = NULL;
    ui_watch_analog_Label_battery_percent2 = NULL;
    ui_watch_analog_Panel_date_group2 = NULL;
    ui_watch_analog_Label_day2 = NULL;
    ui_watch_analog_Label_month2 = NULL;
    ui_watch_analog_Label_year2 = NULL;
    ui_watch_analog_Panel_step_group3 = NULL;
    ui_watch_analog_Image_step2 = NULL;
    ui_watch_analog_Label_step_label2 = NULL;
    ui_watch_analog_Panel_daily_mission_group3 = NULL;
    ui_watch_analog_Label_mission_percent2 = NULL;
    ui_watch_analog_Image_daily_mission_image2 = NULL;
    ui_watch_analog_Arc_daily_mission_arc2 = NULL;
    ui_watch_analog_Panel_clock_group = NULL;
    ui_watch_analog_Image_sec = NULL;
    ui_watch_analog_Image_min = NULL;
    ui_watch_analog_Image_hour = NULL;

}
