/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"

void ui_screen_chat_screen_init(void)
{
    ui_screen_chat = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_screen_chat, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_screen_chat, &ui_img_pattern_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_tiled(ui_screen_chat, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_panel_chat_container = lv_obj_create(ui_screen_chat);
    lv_obj_set_width(ui_chat_panel_chat_container, lv_pct(100));
    lv_obj_set_height(ui_chat_panel_chat_container, lv_pct(100));
    lv_obj_set_align(ui_chat_panel_chat_container, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_chat_panel_chat_container, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chat_panel_chat_container, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_small_label_chat_date = ui_label_small_label_create(ui_chat_panel_chat_container);
    lv_obj_set_x(ui_chat_small_label_chat_date, 0);
    lv_obj_set_y(ui_chat_small_label_chat_date, 17);
    lv_obj_set_align(ui_chat_small_label_chat_date, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_chat_small_label_chat_date, "Yesterday 07:25 PM");
    lv_obj_set_style_text_color(ui_chat_small_label_chat_date, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chat_small_label_chat_date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_panel_c1 = lv_obj_create(ui_chat_panel_chat_container);
    lv_obj_set_height(ui_chat_panel_c1, 100);
    lv_obj_set_width(ui_chat_panel_c1, lv_pct(100));
    lv_obj_set_x(ui_chat_panel_c1, 0);
    lv_obj_set_y(ui_chat_panel_c1, 60);
    lv_obj_remove_flag(ui_chat_panel_c1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chat_panel_c1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chat_panel_c1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chat_panel_c1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chat_panel_c1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chat_panel_c1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chat_panel_c1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_panel_chat_panel1 = lv_obj_create(ui_chat_panel_c1);
    lv_obj_set_width(ui_chat_panel_chat_panel1, 169);
    lv_obj_set_height(ui_chat_panel_chat_panel1, 81);
    lv_obj_remove_flag(ui_chat_panel_chat_panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_chat_panel_chat_panel1, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chat_panel_chat_panel1, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chat_panel_chat_panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chat_panel_chat_panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chat_panel_chat_panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chat_panel_chat_panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chat_panel_chat_panel1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_small_label_chat1 = ui_label_small_label_create(ui_chat_panel_chat_panel1);
    lv_obj_set_width(ui_chat_small_label_chat1, lv_pct(100));
    lv_obj_set_height(ui_chat_small_label_chat1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chat_small_label_chat1, 0);
    lv_obj_set_y(ui_chat_small_label_chat1, 0);
    lv_obj_set_align(ui_chat_small_label_chat1, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_chat_small_label_chat1, "Let's get some dinner, how about pizza?");
    lv_obj_set_style_text_color(ui_chat_small_label_chat1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chat_small_label_chat1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_image_chat_icon1 = lv_image_create(ui_chat_panel_c1);
    lv_image_set_src(ui_chat_image_chat_icon1, &ui_img_chatbox_png);
    lv_obj_set_width(ui_chat_image_chat_icon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chat_image_chat_icon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chat_image_chat_icon1, 0);
    lv_obj_set_y(ui_chat_image_chat_icon1, 80);
    lv_obj_add_flag(ui_chat_image_chat_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_chat_image_chat_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_chat_image_chat_icon1, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_chat_image_chat_icon1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_panel_c2 = lv_obj_create(ui_chat_panel_chat_container);
    lv_obj_set_height(ui_chat_panel_c2, 100);
    lv_obj_set_width(ui_chat_panel_c2, lv_pct(100));
    lv_obj_set_x(ui_chat_panel_c2, 0);
    lv_obj_set_y(ui_chat_panel_c2, 160);
    lv_obj_remove_flag(ui_chat_panel_c2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chat_panel_c2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chat_panel_c2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chat_panel_c2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chat_panel_c2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chat_panel_c2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chat_panel_c2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_panel_chat_panel2 = lv_obj_create(ui_chat_panel_c2);
    lv_obj_set_width(ui_chat_panel_chat_panel2, 169);
    lv_obj_set_height(ui_chat_panel_chat_panel2, 81);
    lv_obj_set_align(ui_chat_panel_chat_panel2, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_chat_panel_chat_panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_chat_panel_chat_panel2, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chat_panel_chat_panel2, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chat_panel_chat_panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chat_panel_chat_panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chat_panel_chat_panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chat_panel_chat_panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chat_panel_chat_panel2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_small_label_chat2 = ui_label_small_label_create(ui_chat_panel_chat_panel2);
    lv_obj_set_width(ui_chat_small_label_chat2, lv_pct(100));
    lv_obj_set_height(ui_chat_small_label_chat2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chat_small_label_chat2, 0);
    lv_obj_set_y(ui_chat_small_label_chat2, 0);
    lv_obj_set_align(ui_chat_small_label_chat2, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_chat_small_label_chat2, "Sounds good! What about James?");
    lv_obj_set_style_text_color(ui_chat_small_label_chat2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chat_small_label_chat2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_image_chat_icon2 = lv_image_create(ui_chat_panel_c2);
    lv_image_set_src(ui_chat_image_chat_icon2, &ui_img_chatbox2_png);
    lv_obj_set_width(ui_chat_image_chat_icon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chat_image_chat_icon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chat_image_chat_icon2, 0);
    lv_obj_set_y(ui_chat_image_chat_icon2, 80);
    lv_obj_set_align(ui_chat_image_chat_icon2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_chat_image_chat_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_chat_image_chat_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_chat_image_chat_icon2, lv_color_hex(0x293062), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_chat_image_chat_icon2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_small_label_delifered = ui_label_small_label_create(ui_chat_panel_c2);
    lv_obj_set_x(ui_chat_small_label_delifered, 47);
    lv_obj_set_y(ui_chat_small_label_delifered, 83);
    lv_obj_set_align(ui_chat_small_label_delifered, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_chat_small_label_delifered, "Delivered");
    lv_obj_set_style_text_color(ui_chat_small_label_delifered, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chat_small_label_delifered, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_panel_c3 = lv_obj_create(ui_chat_panel_chat_container);
    lv_obj_set_height(ui_chat_panel_c3, 100);
    lv_obj_set_width(ui_chat_panel_c3, lv_pct(100));
    lv_obj_set_x(ui_chat_panel_c3, 0);
    lv_obj_set_y(ui_chat_panel_c3, 270);
    lv_obj_remove_flag(ui_chat_panel_c3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_chat_panel_c3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chat_panel_c3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chat_panel_c3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chat_panel_c3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chat_panel_c3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chat_panel_c3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_panel_chat_panel3 = lv_obj_create(ui_chat_panel_c3);
    lv_obj_set_width(ui_chat_panel_chat_panel3, 169);
    lv_obj_set_height(ui_chat_panel_chat_panel3, 81);
    lv_obj_remove_flag(ui_chat_panel_chat_panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_chat_panel_chat_panel3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_chat_panel_chat_panel3, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_chat_panel_chat_panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_chat_panel_chat_panel3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_chat_panel_chat_panel3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_chat_panel_chat_panel3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_chat_panel_chat_panel3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_small_label_chat3 = ui_label_small_label_create(ui_chat_panel_chat_panel3);
    lv_obj_set_width(ui_chat_small_label_chat3, lv_pct(100));
    lv_obj_set_height(ui_chat_small_label_chat3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chat_small_label_chat3, 0);
    lv_obj_set_y(ui_chat_small_label_chat3, 0);
    lv_obj_set_align(ui_chat_small_label_chat3, LV_ALIGN_TOP_LEFT);
    lv_label_set_text(ui_chat_small_label_chat3, "He likes it too! Where do we meet?");
    lv_obj_set_style_text_color(ui_chat_small_label_chat3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_chat_small_label_chat3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_image_chat_icon3 = lv_image_create(ui_chat_panel_c3);
    lv_image_set_src(ui_chat_image_chat_icon3, &ui_img_chatbox_png);
    lv_obj_set_width(ui_chat_image_chat_icon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_chat_image_chat_icon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_chat_image_chat_icon3, 0);
    lv_obj_set_y(ui_chat_image_chat_icon3, 80);
    lv_obj_add_flag(ui_chat_image_chat_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_chat_image_chat_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_chat_image_chat_icon3, lv_color_hex(0x9C9CD9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_chat_image_chat_icon3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_chat_scrolldots_scrolldots2 = ui_panel_scrolldots_create(ui_screen_chat);
    lv_obj_set_x(ui_chat_scrolldots_scrolldots2, 0);
    lv_obj_set_y(ui_chat_scrolldots_scrolldots2, -8);

    lv_obj_set_width(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);
    lv_obj_set_height(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D1), 4);

    lv_obj_set_x(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 10);
    lv_obj_set_y(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D2), 0);

    lv_obj_set_width(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 8);
    lv_obj_set_height(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 8);
    lv_obj_set_x(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 21);
    lv_obj_set_y(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 0);
    lv_obj_set_style_bg_color(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3),
                              lv_color_hex(0x101C52), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_comp_get_child(ui_chat_scrolldots_scrolldots2, UI_COMP_PANEL_SCROLLDOTS_PANEL_D3), 255,
                            LV_PART_MAIN | LV_STATE_DEFAULT);





    lv_obj_add_event_cb(ui_screen_chat, ui_event_screen_chat, LV_EVENT_ALL, NULL);

}
