/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN_LOGIN_H
#define UI_SCREEN_LOGIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_Login
extern void ui_Screen_Login_screen_init(void);
extern void ui_Screen_Login_screen_destroy(void);
extern lv_obj_t *ui_Screen_Login;
extern lv_obj_t *ui_Login_Image_Image2;
extern lv_obj_t *ui_Login_Keyboard_Keyboard1;
extern lv_obj_t *ui_Login_Textarea_TextArea2;
extern lv_obj_t *ui_Login_Textarea_TextArea3;
extern lv_obj_t *ui_Login_Button_Button1;
extern lv_obj_t *ui_Login_Label_Label1;
// CUSTOM VARIABLES

void ui_Screen_Login_apply_language(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
