/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"
#include "../ui_display.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "rainmaker_app_backend.h"

#define UI_LOGIN_CRED_BUF_LEN 256
static char s_login_email_buf[UI_LOGIN_CRED_BUF_LEN];
static char s_login_password_buf[UI_LOGIN_CRED_BUF_LEN];

lv_obj_t *ui_Screen_Login = NULL; lv_obj_t *ui_Login_Image_Image2 = NULL; lv_obj_t *ui_Login_Keyboard_Keyboard1 = NULL; lv_obj_t *ui_Login_Textarea_TextArea2 = NULL; lv_obj_t *ui_Login_Textarea_TextArea3 = NULL; lv_obj_t *ui_Login_Button_Button1 = NULL; lv_obj_t *ui_Login_Label_Label1 = NULL;
// event functions

static int32_t s_login_ui_shift_y = 0;
/** Column: logo + fields — translated together when keyboard opens (replaces per-widget SquareLine offsets). */
static lv_obj_t *s_login_form = NULL;
static lv_obj_t *s_login_lang_label = NULL;

/* Forward declarations (avoid implicit declarations under -Werror) */
static void ui_login_hide_keyboard(void);
static void ui_login_language_btn_cb(lv_event_t *e);

/**
 * Run after a short lv_timer delay (same pattern as Home refresh) so the busy overlay is
 * flushed to the panel before rm_app_backend_* blocks the LVGL task.
 */
static void ui_login_backend_timer_cb(lv_timer_t *t)
{
    if (t) {
        lv_timer_del(t);
    }

    const char *err_reason = NULL;

    esp_err_t ret = rm_app_backend_init();
    if (ret != ESP_OK) {
        ui_hide_busy();
        ui_show_msgbox(ui_str(UI_STR_MSGBOX_ERROR), ui_str(UI_STR_FAILED_INIT_RM));
        return;
    }

    bool ok = rm_app_backend_login(s_login_email_buf, s_login_password_buf, &err_reason);
    ui_hide_busy();

    if (ok) {
        if (ui_Screen_Home) {
            ui_Screen_Home_refresh_from_backend();
            lv_disp_load_scr(ui_Screen_Home);
        }
        return;
    }

    ui_show_msgbox(ui_str_by_id(UI_STR_MSGBOX_ERROR), err_reason);
    free((char *)err_reason);
}

static void ui_login_button_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code != LV_EVENT_CLICKED) {
        return;
    }

    /* Stop bubbling so the screen click handler won't close/reset unexpectedly */
    lv_event_stop_bubbling(e);

    const char *email = ui_Login_Textarea_TextArea2 ? lv_textarea_get_text(ui_Login_Textarea_TextArea2) : "";
    const char *password = ui_Login_Textarea_TextArea3 ? lv_textarea_get_text(ui_Login_Textarea_TextArea3) : "";

    /* Hide keyboard before navigating or showing dialogs */
    ui_login_hide_keyboard();

    strncpy(s_login_email_buf, email, sizeof(s_login_email_buf) - 1);
    s_login_email_buf[sizeof(s_login_email_buf) - 1] = '\0';
    strncpy(s_login_password_buf, password, sizeof(s_login_password_buf) - 1);
    s_login_password_buf[sizeof(s_login_password_buf) - 1] = '\0';

    ui_show_busy(ui_str(UI_STR_LOGIN_PLEASE_WAIT));
    /* Defer blocking work: lv_async_call can run in the same tick before DMA flush completes. */
    (void)lv_timer_create(ui_login_backend_timer_cb, 20, NULL);
}

static void ui_login_set_shift_y(int32_t shift_y)
{
    /* shift_y > 0 means moving form up so focused field stays above keyboard */
    s_login_ui_shift_y = shift_y;
    if (s_login_form) {
        lv_obj_set_style_translate_y(s_login_form, -s_login_ui_shift_y, 0);
    }
}

static void ui_login_hide_keyboard(void)
{
    if (ui_Login_Keyboard_Keyboard1 == NULL) {
        return;
    }
    lv_obj_add_flag(ui_Login_Keyboard_Keyboard1, LV_OBJ_FLAG_HIDDEN);
    lv_keyboard_set_textarea(ui_Login_Keyboard_Keyboard1, NULL);
    ui_login_set_shift_y(0);
}

static void ui_login_language_btn_cb(lv_event_t *e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) {
        return;
    }
    lv_event_stop_bubbling(e);
    ui_login_hide_keyboard();
    ui_show_language_picker();
}

static void ui_login_adjust_for_keyboard(lv_obj_t *ta, lv_obj_t *kb)
{
    if (ta == NULL || kb == NULL) {
        return;
    }

    /* Ensure the keyboard is laid out at the bottom before querying coordinates */
    lv_obj_update_layout(kb);
    lv_obj_update_layout(ta);

    lv_area_t kb_a;
    lv_area_t ta_a;
    lv_obj_get_coords(kb, &kb_a);
    lv_obj_get_coords(ta, &ta_a);

    /* If textarea bottom is below keyboard top, shift UI up */
    const int32_t margin = 8;
    int32_t overlap = ta_a.y2 - (kb_a.y1 - margin);
    if (overlap < 0) {
        overlap = 0;
    }

    /* Avoid shifting too much (cap to screen height) */
    lv_disp_t *disp = lv_disp_get_default();
    int32_t max_shift = 120;
    if (disp) {
        max_shift = lv_disp_get_ver_res(disp);
    }
    if (overlap > max_shift) {
        overlap = max_shift;
    }

    ui_login_set_shift_y(overlap);
}

static void ui_login_bg_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code != LV_EVENT_CLICKED) {
        return;
    }
    /* If the click bubbled up from a child, ignore it. The child callback will handle it. */
    lv_obj_t *target = lv_event_get_target(e);
    lv_obj_t *current_target = lv_event_get_current_target(e);
    if (target != current_target) {
        return;
    }

    ui_login_hide_keyboard();
}

static void ui_login_textarea_value_changed_cb(lv_event_t *e)
{
    lv_obj_t *ta = lv_event_get_target(e);
    const char *name = (const char *)lv_event_get_user_data(e);
    const char *txt = lv_textarea_get_text(ta);
    (void)ta;

    /* Print current input to serial console (email/password) */
    if (name == NULL) {
        name = "input";
    }
    if (txt == NULL) {
        txt = "";
    }
}

static void ui_login_textarea_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t *ta = lv_event_get_target(e);
    lv_obj_t *kb = (lv_obj_t *)lv_event_get_user_data(e);
    lv_obj_t *other_ta = NULL;

    if (ta == ui_Login_Textarea_TextArea2) {
        other_ta = ui_Login_Textarea_TextArea3;
    } else if (ta == ui_Login_Textarea_TextArea3) {
        other_ta = ui_Login_Textarea_TextArea2;
    }

    if (kb == NULL) {
        return;
    }

    if (code == LV_EVENT_CLICKED) {
        /* Click should only focus the textarea. The actual keyboard/show/shift is handled on FOCUSED.
         * This avoids double handling (CLICKED + FOCUSED) which would otherwise shift and then
         * immediately reset to 0 due to the second callback run.
         */
        lv_event_stop_bubbling(e);
        return;
    }

    if (code == LV_EVENT_FOCUSED) {
        /* Prevent the event from bubbling to the screen and closing the keyboard */
        lv_event_stop_bubbling(e);

        /* Ensure only one textarea looks focused (cursor shown) */
        if (other_ta) {
            lv_obj_clear_state(other_ta, LV_STATE_FOCUSED);
        }
        /* Ensure cursor is visible even when the textarea text is empty */
        lv_textarea_set_cursor_pos(ta, LV_TEXTAREA_CURSOR_LAST);

        lv_keyboard_set_textarea(kb, ta);
        lv_obj_clear_flag(kb, LV_OBJ_FLAG_HIDDEN);

        /* Put the keyboard above other widgets and dock it to the bottom */
        lv_obj_set_align(kb, LV_ALIGN_BOTTOM_MID);
        lv_obj_set_y(kb, -ui_display_scale_px(30));
        lv_obj_move_foreground(kb);

        ui_login_adjust_for_keyboard(ta, kb);
        return;
    }
}

static void ui_login_keyboard_event_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if (code == LV_EVENT_READY || code == LV_EVENT_CANCEL) {
        ui_login_hide_keyboard();
    }
}

// build functions

void ui_Screen_Login_screen_init(void)
{
    ui_Screen_Login = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen_Login, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_Screen_Login, lv_color_hex(0xF5F8FF), 0);
    lv_obj_add_event_cb(ui_Screen_Login, ui_login_bg_event_cb, LV_EVENT_CLICKED, NULL);

    /* Centered form: logo + fields + button (language is a separate top-aligned row, see below). */
    s_login_form = lv_obj_create(ui_Screen_Login);
    lv_obj_clear_flag(s_login_form, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_width(s_login_form, lv_pct(88));
    lv_obj_set_style_max_width(s_login_form, ui_display_scale_px(440), 0);
    lv_obj_set_height(s_login_form, LV_SIZE_CONTENT);
    lv_obj_align(s_login_form, LV_ALIGN_CENTER, 0, 0);
    lv_obj_set_flex_flow(s_login_form, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(s_login_form, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_row(s_login_form, ui_display_scale_px(14), 0);
    lv_obj_set_style_pad_top(s_login_form, ui_display_scale_px(12), 0);
    /* Space below the login button only (inside the form). Keeps the button above the gesture/home bar without shifting the whole column upward. */
    lv_obj_set_style_pad_bottom(s_login_form, ui_display_scale_px(32), 0);
    lv_obj_set_style_bg_opa(s_login_form, LV_OPA_0, 0);
    lv_obj_set_style_border_width(s_login_form, 0, 0);

    ui_Login_Image_Image2 = lv_img_create(s_login_form);
    lv_img_set_src(ui_Login_Image_Image2, &ui_img_logo_png);
    lv_obj_set_width(ui_Login_Image_Image2, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Login_Image_Image2, LV_SIZE_CONTENT);
    lv_obj_add_flag(ui_Login_Image_Image2, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_Login_Image_Image2, LV_OBJ_FLAG_SCROLLABLE);

    /* Keyboard must exist before textarea event callbacks are registered. */
    ui_Login_Keyboard_Keyboard1 = lv_keyboard_create(ui_Screen_Login);
    lv_obj_set_width(ui_Login_Keyboard_Keyboard1, lv_pct(100));
    lv_obj_set_height(ui_Login_Keyboard_Keyboard1, ui_display_scale_px(120));
    lv_obj_add_flag(ui_Login_Keyboard_Keyboard1, LV_OBJ_FLAG_FLOATING);
    lv_obj_set_align(ui_Login_Keyboard_Keyboard1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_Login_Keyboard_Keyboard1, 0);
    lv_obj_add_flag(ui_Login_Keyboard_Keyboard1, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_event_cb(ui_Login_Keyboard_Keyboard1, ui_login_keyboard_event_cb, LV_EVENT_ALL, NULL);

    const int32_t ta_h = ui_display_scale_px(40);

    ui_Login_Textarea_TextArea2 = lv_textarea_create(s_login_form);
    lv_obj_set_width(ui_Login_Textarea_TextArea2, lv_pct(100));
    lv_obj_set_height(ui_Login_Textarea_TextArea2, ta_h);
    lv_textarea_set_text(ui_Login_Textarea_TextArea2, "");
    lv_textarea_set_placeholder_text(ui_Login_Textarea_TextArea2, ui_str(UI_STR_EMAIL));
    lv_obj_set_style_text_font(ui_Login_Textarea_TextArea2, ui_font_body(), 0);
    lv_obj_add_flag(ui_Login_Textarea_TextArea2, LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_obj_add_event_cb(ui_Login_Textarea_TextArea2, ui_login_textarea_event_cb, LV_EVENT_ALL, ui_Login_Keyboard_Keyboard1);
    lv_obj_add_event_cb(ui_Login_Textarea_TextArea2, ui_login_textarea_value_changed_cb, LV_EVENT_VALUE_CHANGED, (void *)"Email");

    ui_Login_Textarea_TextArea3 = lv_textarea_create(s_login_form);
    lv_obj_set_width(ui_Login_Textarea_TextArea3, lv_pct(100));
    lv_obj_set_height(ui_Login_Textarea_TextArea3, ta_h);
    lv_textarea_set_text(ui_Login_Textarea_TextArea3, "");
    lv_textarea_set_placeholder_text(ui_Login_Textarea_TextArea3, ui_str(UI_STR_PASSWORD));
    lv_obj_set_style_text_font(ui_Login_Textarea_TextArea3, ui_font_body(), 0);
    lv_obj_add_flag(ui_Login_Textarea_TextArea3, LV_OBJ_FLAG_CLICK_FOCUSABLE);
    lv_textarea_set_password_mode(ui_Login_Textarea_TextArea3, true);
    /* CJK bitmap font may lack U+2022 bullet; LVGL would then draw tofu. Force ASCII "*". */
    lv_textarea_set_password_bullet(ui_Login_Textarea_TextArea3, "*");
    lv_obj_add_event_cb(ui_Login_Textarea_TextArea3, ui_login_textarea_event_cb, LV_EVENT_ALL, ui_Login_Keyboard_Keyboard1);
    lv_obj_add_event_cb(ui_Login_Textarea_TextArea3, ui_login_textarea_value_changed_cb, LV_EVENT_VALUE_CHANGED, (void *)"Password");

    ui_Login_Button_Button1 = lv_btn_create(s_login_form);
    lv_obj_set_width(ui_Login_Button_Button1, lv_pct(100));
    lv_obj_set_height(ui_Login_Button_Button1, ui_display_scale_px(44));
    lv_obj_add_flag(ui_Login_Button_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_Login_Button_Button1, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_Login_Button_Button1, ui_login_button_event_cb, LV_EVENT_CLICKED, NULL);

    ui_Login_Label_Label1 = lv_label_create(ui_Login_Button_Button1);
    lv_label_set_text(ui_Login_Label_Label1, ui_str(UI_STR_LOGIN));
    lv_obj_set_style_text_font(ui_Login_Label_Label1, ui_font_body(), 0);
    lv_obj_center(ui_Login_Label_Label1);

    /* Language row: sibling of the centered form so only this control sits below the window top (PC/chrome); form stays vertically centered. */
    lv_obj_t *lang_row = lv_obj_create(ui_Screen_Login);
    lv_obj_clear_flag(lang_row, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_width(lang_row, lv_pct(100));
    lv_obj_set_height(lang_row, LV_SIZE_CONTENT);
    lv_obj_set_style_bg_opa(lang_row, LV_OPA_0, 0);
    lv_obj_set_style_border_width(lang_row, 0, 0);
    lv_obj_set_style_pad_all(lang_row, 0, 0);
    lv_obj_set_flex_flow(lang_row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(lang_row, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_align(lang_row, LV_ALIGN_TOP_MID, 0, ui_display_scale_px(12));

    lv_obj_t *lang_btn = lv_btn_create(lang_row);
    lv_obj_set_width(lang_btn, LV_SIZE_CONTENT);
    lv_obj_set_height(lang_btn, ui_display_scale_px(36));
    lv_obj_add_event_cb(lang_btn, ui_login_language_btn_cb, LV_EVENT_CLICKED, NULL);
    s_login_lang_label = lv_label_create(lang_btn);
    lv_label_set_text(s_login_lang_label, ui_str(UI_STR_LANGUAGE));
    lv_obj_set_style_text_font(s_login_lang_label, ui_font_body(), 0);
    lv_obj_center(s_login_lang_label);
    lv_obj_move_foreground(lang_row);
}

void ui_Screen_Login_apply_language(void)
{
    if (s_login_lang_label) {
        lv_label_set_text(s_login_lang_label, ui_str(UI_STR_LANGUAGE));
        lv_obj_set_style_text_font(s_login_lang_label, ui_font_body(), 0);
    }
    if (ui_Login_Textarea_TextArea2) {
        lv_textarea_set_placeholder_text(ui_Login_Textarea_TextArea2, ui_str(UI_STR_EMAIL));
        lv_obj_set_style_text_font(ui_Login_Textarea_TextArea2, ui_font_body(), 0);
    }
    if (ui_Login_Textarea_TextArea3) {
        lv_textarea_set_placeholder_text(ui_Login_Textarea_TextArea3, ui_str(UI_STR_PASSWORD));
        lv_obj_set_style_text_font(ui_Login_Textarea_TextArea3, ui_font_body(), 0);
        lv_textarea_set_password_bullet(ui_Login_Textarea_TextArea3, "*");
    }
    if (ui_Login_Label_Label1) {
        lv_label_set_text(ui_Login_Label_Label1, ui_str(UI_STR_LOGIN));
        lv_obj_set_style_text_font(ui_Login_Label_Label1, ui_font_body(), 0);
    }
}

void ui_Screen_Login_screen_destroy(void)
{
    if (ui_Screen_Login) {
        lv_obj_del(ui_Screen_Login);
    }
    ui_Screen_Login = NULL;
    ui_Login_Image_Image2 = NULL;
    ui_Login_Keyboard_Keyboard1 = NULL;
    ui_Login_Textarea_TextArea2 = NULL;
    ui_Login_Textarea_TextArea3 = NULL;
    ui_Login_Button_Button1 = NULL;
    ui_Login_Label_Label1 = NULL;
    s_login_form = NULL;
    s_login_lang_label = NULL;
}
