/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN_HOME_H
#define UI_SCREEN_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stddef.h>
#include "lvgl.h"
#include "rainmaker_app_backend.h"

// SCREEN: ui_Screen_Home
extern void ui_Screen_Home_screen_init(void);
extern void ui_Screen_Home_screen_destroy(void);
extern lv_obj_t *ui_Screen_Home;
extern lv_obj_t *ui_Home_Label_HomeName;
extern lv_obj_t *ui_Home_Cont_DeviceGrid;
// CUSTOM VARIABLES

void ui_Screen_Home_set_home_name(const char *home_name);
void ui_Screen_Home_refresh_from_backend(void);
void ui_Screen_Home_update_device_card(rm_device_item_handle_t device);
/** Reload device cards from current g_devices_list / current group (no API refresh). */
void ui_Screen_Home_reload_device_cards(void);
void ui_Screen_Home_apply_language(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
