/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"


// COMPONENT Clock Dot

lv_obj_t *ui_panel_clock_dot_create(lv_obj_t *comp_parent)
{

    lv_obj_t *cui_panel_clock_dot;
    cui_panel_clock_dot = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_panel_clock_dot, 6);
    lv_obj_set_height(cui_panel_clock_dot, 6);
    lv_obj_set_x(cui_panel_clock_dot, -10);
    lv_obj_set_y(cui_panel_clock_dot, 50);
    lv_obj_set_align(cui_panel_clock_dot, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(cui_panel_clock_dot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_panel_clock_dot, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_panel_clock_dot, lv_color_hex(0xB3B4E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_panel_clock_dot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL_CLOCK_DOT_NUM);
    children[UI_COMP_PANEL_CLOCK_DOT_PANEL_CLOCK_DOT] = cui_panel_clock_dot;
    lv_obj_add_event_cb(cui_panel_clock_dot, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_panel_clock_dot, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_panel_clock_dot_create_hook(cui_panel_clock_dot);
    return cui_panel_clock_dot;
}
