/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#ifndef _UI_COMP__H
#define _UI_COMP__H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

#include "ui_comp_alarm_comp.h"
#include "ui_comp_clock_dot.h"
#include "ui_comp_scrolldots.h"
#include "ui_comp_small_label.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
