/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"

void ui_comp_Panel_Alarm_Comp_create_hook(lv_obj_t *comp)
{
}

void ui_comp_Panel_Clock_Dot_create_hook(lv_obj_t *comp)
{
}

void ui_comp_Panel_Scrolldots_create_hook(lv_obj_t *comp)
{
}

void ui_comp_Label_Small_Label_create_hook(lv_obj_t *comp)
{
}

void ui_comp_panel_alarm_comp_create_hook(lv_obj_t *comp)
{
}

void ui_comp_panel_clock_dot_create_hook(lv_obj_t *comp)
{
}

void ui_comp_panel_scrolldots_create_hook(lv_obj_t *comp)
{
}

void ui_comp_label_small_label_create_hook(lv_obj_t *comp)
{
}
