/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#include "../ui.h"


// COMPONENT Small Label

lv_obj_t *ui_label_small_label_create(lv_obj_t *comp_parent)
{

    lv_obj_t *cui_label_small_label;
    cui_label_small_label = lv_label_create(comp_parent);
    lv_obj_set_width(cui_label_small_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_label_small_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_label_small_label, 0);
    lv_obj_set_y(cui_label_small_label, 72);
    lv_obj_set_align(cui_label_small_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_label_small_label, "12");
    lv_obj_set_style_text_color(cui_label_small_label, lv_color_hex(0x000746), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_label_small_label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_label_small_label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t **children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_LABEL_SMALL_LABEL_NUM);
    children[UI_COMP_LABEL_SMALL_LABEL_LABEL_SMALL_LABEL] = cui_label_small_label;
    lv_obj_add_event_cb(cui_label_small_label, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_label_small_label, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_label_small_label_create_hook(cui_label_small_label);
    return cui_label_small_label;
}
