/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#ifndef _UI_COMP_ALARM_COMP_H
#define _UI_COMP_ALARM_COMP_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Alarm Comp
#define UI_COMP_PANEL_ALARM_COMP_PANEL_ALARM_COMP 0
#define UI_COMP_PANEL_ALARM_COMP_LABEL_ALARM_NUM2 1
#define UI_COMP_PANEL_ALARM_COMP_SMALL_LABEL_PERIOD 2
#define UI_COMP_PANEL_ALARM_COMP_SWITCH_SWITCH1 3
#define _UI_COMP_PANEL_ALARM_COMP_NUM 4
lv_obj_t *ui_panel_alarm_comp_create(lv_obj_t *comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
