/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

/**
 * @file example_macros.h
 * @brief Per-example compile gating for the JSON-UI example suite.
 *
 * Every example body and its plugin registration are wrapped in
 * `#if BROOKESIA_GUI_INTERFACE_EXAMPLE_<ID>`. Each switch resolves, in order:
 *   1. A pre-defined macro (manual override).
 *   2. `CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_<ID>` from Kconfig (ESP) or
 *      a `-DCONFIG_...` definition from `pc_platform.cmake` (PC).
 *   3. The master switch @ref BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES (default on).
 */

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES)
#       define BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES CONFIG_BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   else
#       define BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES (1)
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ROOT)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ROOT)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ROOT CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ROOT
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ROOT BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_VARIANTS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_VARIANTS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_VARIANTS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_VARIANTS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_VARIANTS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ENVIRONMENT)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ENVIRONMENT)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ENVIRONMENT CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ENVIRONMENT
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_ENVIRONMENT BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_CONSTANTS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_CONSTANTS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_CONSTANTS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_CONSTANTS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_DOCUMENT_CONSTANTS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_CONSTANT)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_CONSTANT)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_CONSTANT CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_CONSTANT
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_CONSTANT BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_STYLESET)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_STYLESET)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_STYLESET CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_STYLESET
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_STYLESET BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_THEME)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_THEME)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_THEME CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_THEME
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_THEME BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_TEMPLATE)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_TEMPLATE)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_TEMPLATE CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_TEMPLATE
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_ASSETS_TEMPLATE BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SCREEN)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SCREEN)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SCREEN CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SCREEN
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SCREEN BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CONTAINER)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CONTAINER)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CONTAINER CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CONTAINER
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CONTAINER BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LABEL)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LABEL)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LABEL CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LABEL
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LABEL BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_BUTTON)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_BUTTON)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_BUTTON CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_BUTTON
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_BUTTON BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_IMAGE)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_IMAGE)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_IMAGE CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_IMAGE
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_IMAGE BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TEXT_INPUT)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TEXT_INPUT)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TEXT_INPUT CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TEXT_INPUT
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TEXT_INPUT BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SLIDER)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SLIDER)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SLIDER CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SLIDER
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SLIDER BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SWITCH)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SWITCH)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SWITCH CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SWITCH
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SWITCH BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CHECKBOX)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CHECKBOX)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CHECKBOX CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CHECKBOX
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CHECKBOX BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_DROPDOWN)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_DROPDOWN)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_DROPDOWN CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_DROPDOWN
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_DROPDOWN BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_PROGRESS_BAR)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_PROGRESS_BAR)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_PROGRESS_BAR CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_PROGRESS_BAR
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_PROGRESS_BAR BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SPINNER)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SPINNER)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SPINNER CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SPINNER
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_SPINNER BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_ARC)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_ARC)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_ARC CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_ARC
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_ARC BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LINE)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LINE)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LINE CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LINE
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_LINE BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TABLE)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TABLE)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TABLE CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TABLE
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_TABLE BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_KEYBOARD)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_KEYBOARD)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_KEYBOARD CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_KEYBOARD
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_KEYBOARD BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CANVAS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CANVAS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CANVAS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CANVAS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_CANVAS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_FRAME_VIEW)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_FRAME_VIEW)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_FRAME_VIEW CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_FRAME_VIEW
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_VIEW_FRAME_VIEW BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_FLEX)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_FLEX)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_FLEX CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_FLEX
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_FLEX BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_GRID)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_GRID)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_GRID CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_GRID
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_GRID BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_PLACEMENT)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_PLACEMENT)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_PLACEMENT CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_PLACEMENT
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_PLACEMENT BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STATE_STYLES)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STATE_STYLES)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STATE_STYLES CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STATE_STYLES
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STATE_STYLES BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE_REFS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE_REFS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE_REFS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE_REFS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_STYLING_STYLE_REFS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EVENTS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EVENTS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EVENTS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EVENTS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EVENTS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_BINDINGS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_BINDINGS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_BINDINGS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_BINDINGS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_BINDINGS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_ANIMATIONS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_ANIMATIONS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_ANIMATIONS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_ANIMATIONS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_ANIMATIONS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EFFECTS)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EFFECTS)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EFFECTS CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EFFECTS
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_EFFECTS BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_SCREEN_FLOW)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_SCREEN_FLOW)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_SCREEN_FLOW CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_SCREEN_FLOW
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_INTERACTION_SCREEN_FLOW BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_THEME_LANGUAGE)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_THEME_LANGUAGE)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_THEME_LANGUAGE CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_THEME_LANGUAGE
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_THEME_LANGUAGE BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATES)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATES)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATES CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATES
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATES BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_ANIMATION_API)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_ANIMATION_API)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_ANIMATION_API CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_ANIMATION_API
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_ANIMATION_API BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATE)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATE)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATE CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATE
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_TEMPLATE BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif

#if !defined(BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_MOUNT_STACK)
#   if defined(CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_MOUNT_STACK)
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_MOUNT_STACK CONFIG_BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_MOUNT_STACK
#   else
#       define BROOKESIA_GUI_INTERFACE_EXAMPLE_RUNTIME_MOUNT_STACK BROOKESIA_GUI_INTERFACE_ENABLE_EXAMPLES
#   endif
#endif
