/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

// esp-brookesia: changed
#include "ui.h"
#include "rainmaker_app_backend.h"

#if !defined(ESP_BROOKESIA_SQ1_4_1_LV8_3_11)
#define _ui_screen_change(target, fademode, spd, delay, target_init) lv_scr_load_anim(*target, fademode, spd, delay, false)
#endif

///////////////////// VARIABLES ////////////////////

lv_obj_t *ui_Startevents____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
#error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// FUNCTIONS ////////////////////

void phone_app_rainmaker_ui_init(void)
{
    lv_disp_t *dispp = lv_disp_get_default();
    ui_display_init(dispp);
    ui_i18n_init();
#if LVGL_VERSION_MAJOR >= 9
    lv_theme_t *theme = lv_theme_simple_init(dispp);
#else
    lv_theme_t *theme = lv_theme_basic_init(dispp);
#endif
    lv_disp_set_theme(dispp, theme);
    ui_init_all_screens();
    ui_refresh_all_texts();
    esp_err_t ret = rm_app_backend_init();
    if (ret != ESP_OK) {
        printf("Failed to init RainMaker backend, %s\r\n", esp_err_to_name(ret));
        return;
    }
    bool is_logged_in = rm_app_backend_is_logged_in();
    if (is_logged_in) {
        ui_Screen_Home_refresh_from_backend();
        lv_disp_load_scr(ui_Screen_Home);
    } else {
        printf("Not logged in, showing Login screen\r\n");
        lv_disp_load_scr(ui_Screen_Login);
    }
}

void phone_app_rainmaker_ui_set_language(ui_lang_t lang)
{
    ui_i18n_set_lang(lang);
    ui_refresh_all_texts();
}

void phone_app_rainmaker_ui_soft_restart(void)
{
    phone_app_rainmaker_ui_deinit();
    phone_app_rainmaker_ui_init();
}

void phone_app_rainmaker_ui_deinit(void)
{
    ui_deinit_all_screens();
    rm_app_backend_deinit();
}
