/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

// esp-brookesia: changed
#include "lvgl.h"
#include "ui_lv_compat.h"
#include "esp_brookesia.h"
#include "ui_i18n.h"
#include "ui_display.h"


///////////////////// SCREENS ////////////////////
#ifndef RM_HOST_BUILD
#include "screens/ui_Screen_Login.h"
#include "screens/ui_Screen_Home.h"
#include "screens/ui_Screen_Schedules.h"
#include "screens/ui_Screen_CreateSchedule.h"
#include "screens/ui_Screen_CreateScene.h"
#include "screens/ui_Screen_SelectDevices.h"
#include "screens/ui_Screen_SelectActions.h"
#include "screens/ui_Screen_Scenes.h"
#include "screens/ui_Screen_User.h"
#include "screens/ui_Screen_Light_Detail.h"
#include "screens/ui_Screen_Switch_Details.h"
#include "screens/ui_Screen_Fan_Details.h"
#include "screens/ui_Screen_Device_Setting.h"
#include "screens/ui_Screen_Automations.h"
#else
/* PC SDL build: align screen declarations with firmware side to reuse shared UI helpers. */
#include "screens/ui_Screen_Login.h"
#include "screens/ui_Screen_Home.h"
#include "screens/ui_Screen_Schedules.h"
#include "screens/ui_Screen_CreateSchedule.h"
#include "screens/ui_Screen_CreateScene.h"
#include "screens/ui_Screen_SelectDevices.h"
#include "screens/ui_Screen_SelectActions.h"
#include "screens/ui_Screen_Scenes.h"
#include "screens/ui_Screen_User.h"
#include "screens/ui_Screen_Light_Detail.h"
#include "screens/ui_Screen_Switch_Details.h"
#include "screens/ui_Screen_Fan_Details.h"
#include "screens/ui_Screen_Device_Setting.h"
LV_IMG_DECLARE(ui_img_home_png);
LV_IMG_DECLARE(ui_img_light_3_power_off_png);
LV_IMG_DECLARE(ui_img_light_3_power_on_png);
LV_IMG_DECLARE(ui_img_switch_power_off_png);
LV_IMG_DECLARE(ui_img_switch_power_on_png);
LV_IMG_DECLARE(ui_img_fan_power_off_png);
LV_IMG_DECLARE(ui_img_fan_power_on_png);
#endif

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_logo_png);   // assets/logo.png
#ifndef RM_HOST_BUILD
LV_IMG_DECLARE( ui_img_home_png);   // assets/home.png
LV_IMG_DECLARE( ui_img_light_3_power_off_png);   // assets/light_3_power_off.png
LV_IMG_DECLARE( ui_img_light_3_power_on_png);   // assets/light_3_power_on.png
LV_IMG_DECLARE( ui_img_switch_power_off_png);   // assets/switch_power_off.png
LV_IMG_DECLARE( ui_img_switch_power_on_png);   // assets/switch_power_on.png
LV_IMG_DECLARE( ui_img_fan_power_off_png);   // assets/fan_power_off.png
LV_IMG_DECLARE( ui_img_fan_power_on_png);   // assets/fan_power_on.png
#endif

// esp-brookesia: changed
void phone_app_rainmaker_ui_init(void);
void phone_app_rainmaker_ui_deinit(void);
/** Rebuild UI and backend without resetting the chip (deinit + init). */
void phone_app_rainmaker_ui_soft_restart(void);
void ui_show_msgbox(const char *title, const char *text);
/** Show language picker (English / Chinese); persists via ui_i18n and refreshes all screens. */
void ui_show_language_picker(void);
/** Close the language picker if open (e.g. before destroying screens). */
void ui_language_picker_close(void);
/** Modal overlay with spinner + message (e.g. during login). message NULL uses UI_STR_LOGIN_PLEASE_WAIT. */
void ui_show_busy(const char *message);
void ui_hide_busy(void);
/** Apply a font to all labels inside a msgbox (recursive). */
void ui_msgbox_apply_font(lv_obj_t *mbox, const lv_font_t *font);
/** Apply ui_font_body() to all labels inside a msgbox (needed for Chinese glyphs). */
void ui_msgbox_apply_body_font(lv_obj_t *mbox);
/** Center msgbox on backdrop, set width/padding/radius from screen scale, title/body fonts. */
void ui_msgbox_apply_common_layout(lv_obj_t *mbox);
/** Refresh translated strings on all screens (after ui_i18n_set_lang). */
void ui_refresh_all_texts(void);
/** Initialize all app screens in a consistent order. */
void ui_init_all_screens(void);
/** Destroy all app screens in reverse-consistent order. */
void ui_deinit_all_screens(void);
/** Switch UI language and refresh all registered screens. */
void phone_app_rainmaker_ui_set_language(ui_lang_t lang);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
