/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#define BROOKESIA_RUNTIME_MANAGER_LOG_TAG "RtMgr"

#if !defined(BROOKESIA_RUNTIME_MANAGER_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_RUNTIME_MANAGER_ENABLE_DEBUG_LOG)
#       define BROOKESIA_RUNTIME_MANAGER_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_RUNTIME_MANAGER_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_RUNTIME_MANAGER_ENABLE_DEBUG_LOG (0)
#   endif
#endif

#if BROOKESIA_RUNTIME_MANAGER_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_RUNTIME_MANAGER_CORE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_RUNTIME_MANAGER_CORE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_RUNTIME_MANAGER_CORE_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_RUNTIME_MANAGER_CORE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_RUNTIME_MANAGER_CORE_ENABLE_DEBUG_LOG (0)
#       endif
#   endif
#   if !defined(BROOKESIA_RUNTIME_MANAGER_HOST_BRIDGE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_RUNTIME_MANAGER_HOST_BRIDGE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_RUNTIME_MANAGER_HOST_BRIDGE_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_RUNTIME_MANAGER_HOST_BRIDGE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_RUNTIME_MANAGER_HOST_BRIDGE_ENABLE_DEBUG_LOG (0)
#       endif
#   endif
#   if !defined(BROOKESIA_RUNTIME_MANAGER_FUNCTION_BRIDGE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_RUNTIME_MANAGER_FUNCTION_BRIDGE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_RUNTIME_MANAGER_FUNCTION_BRIDGE_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_RUNTIME_MANAGER_FUNCTION_BRIDGE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_RUNTIME_MANAGER_FUNCTION_BRIDGE_ENABLE_DEBUG_LOG (0)
#       endif
#   endif
#endif
