/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if __has_include("sdkconfig.h")
#   include "sdkconfig.h"
#endif

#define BROOKESIA_EMULATION_NES_LOG_TAG "SvcNES"

#if !defined(BROOKESIA_EMULATION_NES_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_EMULATION_NES_ENABLE_AUTO_REGISTER  CONFIG_BROOKESIA_EMULATION_NES_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_EMULATION_NES_ENABLE_AUTO_REGISTER  (0)
#   endif
#endif

#if BROOKESIA_EMULATION_NES_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_EMULATION_NES_PLUGIN_SYMBOL)
#       define BROOKESIA_EMULATION_NES_PLUGIN_SYMBOL  emulation_nes_symbol
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_ENABLE_DEBUG_LOG)
#       define BROOKESIA_EMULATION_NES_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_EMULATION_NES_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_EMULATION_NES_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_FRAME_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_FRAME_INTERVAL_MS)
#       define BROOKESIA_EMULATION_NES_FRAME_INTERVAL_MS  CONFIG_BROOKESIA_EMULATION_NES_FRAME_INTERVAL_MS
#   else
#       define BROOKESIA_EMULATION_NES_FRAME_INTERVAL_MS  (2)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_FRAME_PERIOD_MS)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_FRAME_PERIOD_MS)
#       define BROOKESIA_EMULATION_NES_FRAME_PERIOD_MS  CONFIG_BROOKESIA_EMULATION_NES_FRAME_PERIOD_MS
#   else
#       define BROOKESIA_EMULATION_NES_FRAME_PERIOD_MS  (16)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_BASE_FRAME_SKIP)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_BASE_FRAME_SKIP)
#       define BROOKESIA_EMULATION_NES_BASE_FRAME_SKIP  CONFIG_BROOKESIA_EMULATION_NES_BASE_FRAME_SKIP
#   else
#       define BROOKESIA_EMULATION_NES_BASE_FRAME_SKIP  (0)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_AUTO_FRAME_SKIP_MAX)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_AUTO_FRAME_SKIP_MAX)
#       define BROOKESIA_EMULATION_NES_AUTO_FRAME_SKIP_MAX  CONFIG_BROOKESIA_EMULATION_NES_AUTO_FRAME_SKIP_MAX
#   else
#       define BROOKESIA_EMULATION_NES_AUTO_FRAME_SKIP_MAX  (2)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_MAX_CONSECUTIVE_FRAME_SKIP)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_MAX_CONSECUTIVE_FRAME_SKIP)
#       define BROOKESIA_EMULATION_NES_MAX_CONSECUTIVE_FRAME_SKIP \
            CONFIG_BROOKESIA_EMULATION_NES_MAX_CONSECUTIVE_FRAME_SKIP
#   else
#       define BROOKESIA_EMULATION_NES_MAX_CONSECUTIVE_FRAME_SKIP  (2)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_ENABLE_WORKER)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_ENABLE_WORKER)
#       define BROOKESIA_EMULATION_NES_ENABLE_WORKER  CONFIG_BROOKESIA_EMULATION_NES_ENABLE_WORKER
#   else
#       define BROOKESIA_EMULATION_NES_ENABLE_WORKER  (0)
#   endif
#endif

#if BROOKESIA_EMULATION_NES_ENABLE_WORKER
#if !defined(BROOKESIA_EMULATION_NES_WORKER_NAME)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_WORKER_NAME)
#       define BROOKESIA_EMULATION_NES_WORKER_NAME  CONFIG_BROOKESIA_EMULATION_NES_WORKER_NAME
#   else
#       define BROOKESIA_EMULATION_NES_WORKER_NAME  "SvcNES"
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_WORKER_PRIORITY)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_WORKER_PRIORITY)
#       define BROOKESIA_EMULATION_NES_WORKER_PRIORITY  CONFIG_BROOKESIA_EMULATION_NES_WORKER_PRIORITY
#   else
#       define BROOKESIA_EMULATION_NES_WORKER_PRIORITY  (7)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_WORKER_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_WORKER_STACK_SIZE)
#       define BROOKESIA_EMULATION_NES_WORKER_STACK_SIZE  CONFIG_BROOKESIA_EMULATION_NES_WORKER_STACK_SIZE
#   else
#       define BROOKESIA_EMULATION_NES_WORKER_STACK_SIZE  (12288)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_WORKER_STACK_IN_EXT)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_WORKER_STACK_IN_EXT)
#       define BROOKESIA_EMULATION_NES_WORKER_STACK_IN_EXT  CONFIG_BROOKESIA_EMULATION_NES_WORKER_STACK_IN_EXT
#   else
#       define BROOKESIA_EMULATION_NES_WORKER_STACK_IN_EXT  (1)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_WORKER_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_WORKER_POLL_INTERVAL_MS)
#       define BROOKESIA_EMULATION_NES_WORKER_POLL_INTERVAL_MS  CONFIG_BROOKESIA_EMULATION_NES_WORKER_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_EMULATION_NES_WORKER_POLL_INTERVAL_MS  (4)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_WORKER_0_CORE_ID)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_WORKER_0_CORE_ID)
#       define BROOKESIA_EMULATION_NES_WORKER_0_CORE_ID  CONFIG_BROOKESIA_EMULATION_NES_WORKER_0_CORE_ID
#   else
#       define BROOKESIA_EMULATION_NES_WORKER_0_CORE_ID  (0)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_WORKER_1_CORE_ID)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_WORKER_1_CORE_ID)
#       define BROOKESIA_EMULATION_NES_WORKER_1_CORE_ID  CONFIG_BROOKESIA_EMULATION_NES_WORKER_1_CORE_ID
#   else
#       define BROOKESIA_EMULATION_NES_WORKER_1_CORE_ID  (1)
#   endif
#endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_AUDIO_QUEUE_MAX_FRAMES)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_AUDIO_QUEUE_MAX_FRAMES)
#       define BROOKESIA_EMULATION_NES_AUDIO_QUEUE_MAX_FRAMES  CONFIG_BROOKESIA_EMULATION_NES_AUDIO_QUEUE_MAX_FRAMES
#   else
#       define BROOKESIA_EMULATION_NES_AUDIO_QUEUE_MAX_FRAMES  (32)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_AUDIO_FEED_MAX_CHUNKS_PER_TICK)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_AUDIO_FEED_MAX_CHUNKS_PER_TICK)
#       define BROOKESIA_EMULATION_NES_AUDIO_FEED_MAX_CHUNKS_PER_TICK \
            CONFIG_BROOKESIA_EMULATION_NES_AUDIO_FEED_MAX_CHUNKS_PER_TICK
#   else
#       define BROOKESIA_EMULATION_NES_AUDIO_FEED_MAX_CHUNKS_PER_TICK  (2)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_AUDIO_FEED_BUDGET_MS)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_AUDIO_FEED_BUDGET_MS)
#       define BROOKESIA_EMULATION_NES_AUDIO_FEED_BUDGET_MS  CONFIG_BROOKESIA_EMULATION_NES_AUDIO_FEED_BUDGET_MS
#   else
#       define BROOKESIA_EMULATION_NES_AUDIO_FEED_BUDGET_MS  (2)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_AUDIO_SAMPLE_RATE)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_AUDIO_SAMPLE_RATE)
#       define BROOKESIA_EMULATION_NES_AUDIO_SAMPLE_RATE  CONFIG_BROOKESIA_EMULATION_NES_AUDIO_SAMPLE_RATE
#   else
#       define BROOKESIA_EMULATION_NES_AUDIO_SAMPLE_RATE  (22050)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_AUDIO_STEREO)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_AUDIO_STEREO)
#       define BROOKESIA_EMULATION_NES_AUDIO_STEREO  CONFIG_BROOKESIA_EMULATION_NES_AUDIO_STEREO
#   else
#       define BROOKESIA_EMULATION_NES_AUDIO_STEREO  (0)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_LOG_BUFFER_MEMORY)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_LOG_BUFFER_MEMORY)
#       define BROOKESIA_EMULATION_NES_LOG_BUFFER_MEMORY  CONFIG_BROOKESIA_EMULATION_NES_LOG_BUFFER_MEMORY
#   else
#       define BROOKESIA_EMULATION_NES_LOG_BUFFER_MEMORY  (0)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_PERF_LOG_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_PERF_LOG_INTERVAL_MS)
#       define BROOKESIA_EMULATION_NES_PERF_LOG_INTERVAL_MS  CONFIG_BROOKESIA_EMULATION_NES_PERF_LOG_INTERVAL_MS
#   else
#       define BROOKESIA_EMULATION_NES_PERF_LOG_INTERVAL_MS  (5000)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_DRAW_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_DRAW_TIMEOUT_MS)
#       define BROOKESIA_EMULATION_NES_DRAW_TIMEOUT_MS  CONFIG_BROOKESIA_EMULATION_NES_DRAW_TIMEOUT_MS
#   else
#       define BROOKESIA_EMULATION_NES_DRAW_TIMEOUT_MS  (5000)
#   endif
#endif

#if !defined(BROOKESIA_EMULATION_NES_ENABLE_NOFRENDO)
#   if defined(CONFIG_BROOKESIA_EMULATION_NES_ENABLE_NOFRENDO)
#       define BROOKESIA_EMULATION_NES_ENABLE_NOFRENDO  CONFIG_BROOKESIA_EMULATION_NES_ENABLE_NOFRENDO
#   else
#       define BROOKESIA_EMULATION_NES_ENABLE_NOFRENDO  (1)
#   endif
#endif
