// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "esp_brookesia.h"

// SCREEN: ui_ScreenScreenAIProfile
void ui_ScreenScreenAIProfile_screen_init(void);
extern lv_obj_t *ui_ScreenScreenAIProfile;
extern lv_obj_t *ui_ScreenAIProfileTabviewTabView;
extern lv_obj_t *ui_ScreenAIProfileTabpageTabPageRole1;
extern lv_obj_t *ui_ScreenAIProfileLabelLabelRole1Name;
extern lv_obj_t *ui_ScreenAIProfileImageImageRole1;
extern lv_obj_t *ui_ScreenAIProfileLabelLabelRole1Description;
extern lv_obj_t *ui_ScreenAIProfileButtonButtonRole1Select;
extern lv_obj_t *ui_ScreenAIProfileLabelLabelButtonRole1Select;
extern lv_obj_t *ui_ScreenAIProfileImageImageRole1Select;
extern lv_obj_t *ui_ScreenAIProfileTabpageTabPageRole2;
extern lv_obj_t *ui_ScreenAIProfileImageImageRole2Select;
extern lv_obj_t *ui_ScreenAIProfileLabelLabelRole2Name;
extern lv_obj_t *ui_ScreenAIProfileImageImageRole2;
extern lv_obj_t *ui_ScreenAIProfileLabelLabelRole2Description;
extern lv_obj_t *ui_ScreenAIProfileButtonButtonRole2Select;
extern lv_obj_t *ui_ScreenAIProfileLabelLabelButtonRole2Select;
extern lv_obj_t *ui_ScreenAIProfileContainerContainerIndicator;
extern lv_obj_t *ui_ScreenAIProfilePanelPanelIndicator1;
extern lv_obj_t *ui_ScreenAIProfilePanelPanelIndicator2;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui_Startevents___initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_esp_brookesia_app_icon_doubao_112_112_png);    // assets/esp_brookesia_app_icon_doubao_112_112.png
LV_IMG_DECLARE(ui_img_image_select_png);    // assets/image_select.png
LV_IMG_DECLARE(ui_img_esp_brookesia_app_icon_dashu_112_112_png);    // assets/esp_brookesia_app_icon_dashu_112_112.png

// FONTS
#define ui_font_esp_brookesia_font_maison_neue_book_26 esp_brookesia_font_maison_neue_book_26
#define ui_font_esp_brookesia_font_maison_neue_book_18 esp_brookesia_font_maison_neue_book_18

// UI INIT
void speaker_ai_profile_ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif
