/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

/**
 * @brief Default log tag used by the component.
 */
#define BROOKESIA_GUI_LVGL_LOG_TAG "GuiLvgl"

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_FRAME_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_FRAME_TIMEOUT_MS)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_FRAME_TIMEOUT_MS \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_FRAME_TIMEOUT_MS)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_FRAME_TIMEOUT_MS  (6000)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_CORE_ID)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_CORE_ID)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_CORE_ID \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_CORE_ID)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_CORE_ID  (0)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_PRIORITY)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_PRIORITY)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_PRIORITY \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_PRIORITY)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_PRIORITY  (6)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TICK_PERIOD_MS)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TICK_PERIOD_MS)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TICK_PERIOD_MS \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TICK_PERIOD_MS)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TICK_PERIOD_MS  (5)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_MIN_DELAY_MS)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_MIN_DELAY_MS)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_MIN_DELAY_MS \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_MIN_DELAY_MS)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_MIN_DELAY_MS  (10)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_MAX_DELAY_MS)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_MAX_DELAY_MS)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_MAX_DELAY_MS \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_MAX_DELAY_MS)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_MAX_DELAY_MS  (100)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_STACK_SIZE)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_STACK_SIZE \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_STACK_SIZE)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_STACK_SIZE  (40960)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_STACK_IN_PSRAM)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_STACK_IN_PSRAM)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_STACK_IN_PSRAM \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_TASK_STACK_IN_PSRAM)
#   elif defined(ESP_PLATFORM)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_STACK_IN_PSRAM  (0)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_TASK_STACK_IN_PSRAM  (1)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_BUFFER_HEIGHT)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_BUFFER_HEIGHT)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_BUFFER_HEIGHT \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_BUFFER_HEIGHT)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_BUFFER_HEIGHT  (20)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_REQUIRE_DOUBLE_BUFFER)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_REQUIRE_DOUBLE_BUFFER)
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_REQUIRE_DOUBLE_BUFFER \
            (CONFIG_BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_REQUIRE_DOUBLE_BUFFER)
#   else
#       define BROOKESIA_GUI_LVGL_DISPLAY_SOURCE_DEFAULT_REQUIRE_DOUBLE_BUFFER  (0)
#   endif
#endif

#if !defined(BROOKESIA_GUI_LVGL_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_GUI_LVGL_ENABLE_DEBUG_LOG)
#       define BROOKESIA_GUI_LVGL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_GUI_LVGL_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_GUI_LVGL_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_GUI_LVGL_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_GUI_LVGL_BACKEND_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_GUI_LVGL_BACKEND_ENABLE_DEBUG_LOG)
#           define BROOKESIA_GUI_LVGL_BACKEND_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_GUI_LVGL_BACKEND_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_GUI_LVGL_BACKEND_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_GUI_LVGL_EVENT_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_GUI_LVGL_EVENT_ENABLE_DEBUG_LOG)
#           define BROOKESIA_GUI_LVGL_EVENT_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_GUI_LVGL_EVENT_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_GUI_LVGL_EVENT_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_GUI_LVGL_FACTORY_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_GUI_LVGL_FACTORY_ENABLE_DEBUG_LOG)
#           define BROOKESIA_GUI_LVGL_FACTORY_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_GUI_LVGL_FACTORY_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_GUI_LVGL_FACTORY_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_GUI_LVGL_LAYOUT_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_GUI_LVGL_LAYOUT_ENABLE_DEBUG_LOG)
#           define BROOKESIA_GUI_LVGL_LAYOUT_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_GUI_LVGL_LAYOUT_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_GUI_LVGL_LAYOUT_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_GUI_LVGL_PROPS_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_GUI_LVGL_PROPS_ENABLE_DEBUG_LOG)
#           define BROOKESIA_GUI_LVGL_PROPS_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_GUI_LVGL_PROPS_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_GUI_LVGL_PROPS_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_GUI_LVGL_STYLE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_GUI_LVGL_STYLE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_GUI_LVGL_STYLE_ENABLE_DEBUG_LOG \
                CONFIG_BROOKESIA_GUI_LVGL_STYLE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_GUI_LVGL_STYLE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif // BROOKESIA_GUI_LVGL_ENABLE_DEBUG_LOG
