esp_toml_version = 1.0
firmware_images_url = "https://espressif.github.io/esp-brookesia/system/super/"

supported_apps = ["espressif_esp32_p4x_function_ev"]

[espressif_esp32_p4x_function_ev]
chipsets = ["ESP32P4"]
image.esp32p4 = "super_esp32p4_espressif_esp32_p4x_function_ev.bin"
ios_app_url = ""
android_app_url = ""

