/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "sdkconfig.h"

/* Auto register */
#if !defined(BROOKESIA_AGENT_XIAOZHI_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_AGENT_XIAOZHI_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_AGENT_XIAOZHI_ENABLE_AUTO_REGISTER  CONFIG_BROOKESIA_AGENT_XIAOZHI_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_AGENT_XIAOZHI_ENABLE_AUTO_REGISTER  (0)
#   endif
#endif

/* Plugin symbol */
#if BROOKESIA_AGENT_XIAOZHI_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_AGENT_XIAOZHI_PLUGIN_SYMBOL)
#       define BROOKESIA_AGENT_XIAOZHI_PLUGIN_SYMBOL  agent_xiaozhi_symbol
#   endif
#endif

/* Debug log */
#define BROOKESIA_AGENT_XIAOZHI_LOG_TAG "AgentXiaoZhi"

#if !defined(BROOKESIA_AGENT_XIAOZHI_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_AGENT_XIAOZHI_ENABLE_DEBUG_LOG)
#       define BROOKESIA_AGENT_XIAOZHI_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_AGENT_XIAOZHI_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_AGENT_XIAOZHI_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_AGENT_XIAOZHI_GET_HTTP_INFO_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_AGENT_XIAOZHI_GET_HTTP_INFO_INTERVAL_MS)
#       define BROOKESIA_AGENT_XIAOZHI_GET_HTTP_INFO_INTERVAL_MS  CONFIG_BROOKESIA_AGENT_XIAOZHI_GET_HTTP_INFO_INTERVAL_MS
#   else
#       define BROOKESIA_AGENT_XIAOZHI_GET_HTTP_INFO_INTERVAL_MS  (15000)
#   endif
#endif

#if !defined(BROOKESIA_AGENT_XIAOZHI_WAKE_WORD)
#   if defined(CONFIG_BROOKESIA_AGENT_XIAOZHI_WAKE_WORD)
#       define BROOKESIA_AGENT_XIAOZHI_WAKE_WORD  CONFIG_BROOKESIA_AGENT_XIAOZHI_WAKE_WORD
#   else
#       define BROOKESIA_AGENT_XIAOZHI_WAKE_WORD  ("Hi,ESP")
#   endif
#endif
