// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#include "../ui.h"


// COMPONENT Scrolldots

lv_obj_t * ui_Panel_Scrolldots_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Panel_Scrolldots;
    cui_Panel_Scrolldots = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Panel_Scrolldots, 65);
    lv_obj_set_height(cui_Panel_Scrolldots, 12);
    lv_obj_set_x(cui_Panel_Scrolldots, 0);
    lv_obj_set_y(cui_Panel_Scrolldots, -8);
    lv_obj_set_align(cui_Panel_Scrolldots, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(cui_Panel_Scrolldots, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel_Scrolldots, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_Scrolldots, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_d1;
    cui_Panel_d1 = lv_obj_create(cui_Panel_Scrolldots);
    lv_obj_set_width(cui_Panel_d1, 8);
    lv_obj_set_height(cui_Panel_d1, 8);
    lv_obj_set_align(cui_Panel_d1, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel_d1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_d1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel_d1, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_d1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_d2;
    cui_Panel_d2 = lv_obj_create(cui_Panel_Scrolldots);
    lv_obj_set_width(cui_Panel_d2, 4);
    lv_obj_set_height(cui_Panel_d2, 4);
    lv_obj_set_x(cui_Panel_d2, 15);
    lv_obj_set_y(cui_Panel_d2, 0);
    lv_obj_set_align(cui_Panel_d2, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel_d2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_d2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel_d2, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_d2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_d3;
    cui_Panel_d3 = lv_obj_create(cui_Panel_Scrolldots);
    lv_obj_set_width(cui_Panel_d3, 4);
    lv_obj_set_height(cui_Panel_d3, 4);
    lv_obj_set_x(cui_Panel_d3, 25);
    lv_obj_set_y(cui_Panel_d3, 0);
    lv_obj_set_align(cui_Panel_d3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel_d3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_d3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel_d3, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_d3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_d4;
    cui_Panel_d4 = lv_obj_create(cui_Panel_Scrolldots);
    lv_obj_set_width(cui_Panel_d4, 4);
    lv_obj_set_height(cui_Panel_d4, 4);
    lv_obj_set_x(cui_Panel_d4, 35);
    lv_obj_set_y(cui_Panel_d4, 0);
    lv_obj_set_align(cui_Panel_d4, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel_d4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_d4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel_d4, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_d4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_d5;
    cui_Panel_d5 = lv_obj_create(cui_Panel_Scrolldots);
    lv_obj_set_width(cui_Panel_d5, 4);
    lv_obj_set_height(cui_Panel_d5, 4);
    lv_obj_set_x(cui_Panel_d5, 45);
    lv_obj_set_y(cui_Panel_d5, 0);
    lv_obj_set_align(cui_Panel_d5, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel_d5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_d5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel_d5, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_d5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Panel_d6;
    cui_Panel_d6 = lv_obj_create(cui_Panel_Scrolldots);
    lv_obj_set_width(cui_Panel_d6, 4);
    lv_obj_set_height(cui_Panel_d6, 4);
    lv_obj_set_x(cui_Panel_d6, 55);
    lv_obj_set_y(cui_Panel_d6, 0);
    lv_obj_set_align(cui_Panel_d6, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(cui_Panel_d6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_Panel_d6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_Panel_d6, lv_color_hex(0xB4B6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel_d6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PANEL_SCROLLDOTS_NUM);
    children[UI_COMP_PANEL_SCROLLDOTS_PANEL_SCROLLDOTS] = cui_Panel_Scrolldots;
    children[UI_COMP_PANEL_SCROLLDOTS_PANEL_D1] = cui_Panel_d1;
    children[UI_COMP_PANEL_SCROLLDOTS_PANEL_D2] = cui_Panel_d2;
    children[UI_COMP_PANEL_SCROLLDOTS_PANEL_D3] = cui_Panel_d3;
    children[UI_COMP_PANEL_SCROLLDOTS_PANEL_D4] = cui_Panel_d4;
    children[UI_COMP_PANEL_SCROLLDOTS_PANEL_D5] = cui_Panel_d5;
    children[UI_COMP_PANEL_SCROLLDOTS_PANEL_D6] = cui_Panel_d6;
    lv_obj_add_event_cb(cui_Panel_Scrolldots, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Panel_Scrolldots, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Panel_Scrolldots_create_hook(cui_Panel_Scrolldots);
    return cui_Panel_Scrolldots;
}

