// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_COMP_HOOK_H
#define _SMART_GADGET_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_Panel_Alarm_Comp_create_hook(lv_obj_t * comp);
void ui_comp_Panel_Clock_Dot_create_hook(lv_obj_t * comp);
void ui_comp_Panel_Scrolldots_create_hook(lv_obj_t * comp);
void ui_comp_Label_Small_Label_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
