// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _UI_COMP__H
#define _UI_COMP__H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

#include "ui_comp_alarm_comp.h"
#include "ui_comp_clock_dot.h"
#include "ui_comp_scrolldots.h"
#include "ui_comp_small_label.h"

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
