// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _UI_COMP_CLOCK_DOT_H
#define _UI_COMP_CLOCK_DOT_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Clock Dot
#define UI_COMP_PANEL_CLOCK_DOT_PANEL_CLOCK_DOT 0
#define _UI_COMP_PANEL_CLOCK_DOT_NUM 1
lv_obj_t * ui_Panel_Clock_Dot_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
