// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#ifndef _UI_COMP_SCROLLDOTS_H
#define _UI_COMP_SCROLLDOTS_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Scrolldots
#define UI_COMP_PANEL_SCROLLDOTS_PANEL_SCROLLDOTS 0
#define UI_COMP_PANEL_SCROLLDOTS_PANEL_D1 1
#define UI_COMP_PANEL_SCROLLDOTS_PANEL_D2 2
#define UI_COMP_PANEL_SCROLLDOTS_PANEL_D3 3
#define UI_COMP_PANEL_SCROLLDOTS_PANEL_D4 4
#define UI_COMP_PANEL_SCROLLDOTS_PANEL_D5 5
#define UI_COMP_PANEL_SCROLLDOTS_PANEL_D6 6
#define _UI_COMP_PANEL_SCROLLDOTS_NUM 7
lv_obj_t * ui_Panel_Scrolldots_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
