#
# ESP Platform
#
idf_component_register(
    SRCS ${COMPONENT_SRCS_C} ${COMPONENT_SRCS_CPP}
    INCLUDE_DIRS ${COMPONENT_INCLUDE_DIRS}
    PRIV_INCLUDE_DIRS ${COMPONENT_PRIVATE_INCLUDE_DIRS}
    REQUIRES ${COMPONENT_REQUIRES}
    PRIV_REQUIRES ${COMPONENT_PRIV_REQUIRES}
)

if(CONFIG_BROOKESIA_SERVICE_SNTP_ENABLE_AUTO_REGISTER)
    set(BROOKESIA_SERVICE_SNTP_PLUGIN_SYMBOL service_sntp_symbol)
    target_compile_definitions(${COMPONENT_LIB} PRIVATE
        BROOKESIA_SERVICE_SNTP_PLUGIN_SYMBOL=${BROOKESIA_SERVICE_SNTP_PLUGIN_SYMBOL}
    )
    target_link_libraries(${COMPONENT_LIB} PRIVATE "-u ${BROOKESIA_SERVICE_SNTP_PLUGIN_SYMBOL}")
endif()

include(package_manager)
cu_pkg_define_version(${COMPONENT_DIR})
