/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

/* Version */
#if !defined(BROOKESIA_SERVICE_MANAGER_VER_MAJOR)
#   define BROOKESIA_SERVICE_MANAGER_VER_MAJOR  (0)
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_VER_MINOR)
#   define BROOKESIA_SERVICE_MANAGER_VER_MINOR  (7)
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_VER_PATCH)
#   define BROOKESIA_SERVICE_MANAGER_VER_PATCH  (0)
#endif

/* Debug log */
#define BROOKESIA_SERVICE_MANAGER_LOG_TAG "SrvMgr"

#if !defined(BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_SERVICE_MANAGER_RPC_DATA_LINK_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_DATA_LINK_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_RPC_DATA_LINK_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_DATA_LINK_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_RPC_DATA_LINK_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif

#   if !defined(BROOKESIA_SERVICE_MANAGER_RPC_SERVER_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_SERVER_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_RPC_SERVER_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_SERVER_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_RPC_SERVER_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif

#   if !defined(BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif

#   if !defined(BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif

#   if !defined(BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif

#   if !defined(BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////////// RPC ////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_MANAGER_RPC_GLOBAL_MAX_SOCKETS)
#    if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_GLOBAL_MAX_SOCKETS)
#        define BROOKESIA_SERVICE_MANAGER_RPC_GLOBAL_MAX_SOCKETS  CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_GLOBAL_MAX_SOCKETS
#    else
#        define BROOKESIA_SERVICE_MANAGER_RPC_GLOBAL_MAX_SOCKETS  (LWIP_MAX_SOCKETS if LWIP_MAX_SOCKETS < LWIP_MAX_ACTIVE_TCP else LWIP_MAX_ACTIVE_TCP)
#    endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_RPC_SERVER_LISTEN_PORT)
#    if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_SERVER_LISTEN_PORT)
#        define BROOKESIA_SERVICE_MANAGER_RPC_SERVER_LISTEN_PORT  CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_SERVER_LISTEN_PORT
#    else
#        define BROOKESIA_SERVICE_MANAGER_RPC_SERVER_LISTEN_PORT  (65500)
#    endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_RPC_SERVER_MAX_CONNECTIONS)
#    if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_SERVER_MAX_CONNECTIONS)
#        define BROOKESIA_SERVICE_MANAGER_RPC_SERVER_MAX_CONNECTIONS  CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_SERVER_MAX_CONNECTIONS
#    else
#        define BROOKESIA_SERVICE_MANAGER_RPC_SERVER_MAX_CONNECTIONS  (2)
#    endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_CALL_FUNCTION_TIMEOUT_MS)
#    if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_CALL_FUNCTION_TIMEOUT_MS)
#        define BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_CALL_FUNCTION_TIMEOUT_MS  CONFIG_BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_CALL_FUNCTION_TIMEOUT_MS
#    else
#        define BROOKESIA_SERVICE_MANAGER_RPC_CLIENT_CALL_FUNCTION_TIMEOUT_MS  (2000)
#    endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////// Service - Server //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_MANAGER_IO_THREAD_NAME)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_NAME)
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_NAME  CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_NAME
#   else
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_NAME  ("server_io")
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_IO_THREAD_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_CORE_ID)
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_CORE_ID  CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_CORE_ID
#   else
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_CORE_ID  (-1)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_IO_THREAD_PRIORITY)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_PRIORITY)
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_PRIORITY  CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_PRIORITY
#   else
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_PRIORITY  (18)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_SIZE)
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_SIZE
#   else
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_SIZE  (10 * 1024)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_IN_EXT)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_IN_EXT)
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_IN_EXT  CONFIG_BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_IN_EXT
#   else
#       define BROOKESIA_SERVICE_MANAGER_IO_THREAD_STACK_IN_EXT  (0)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_IO_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_IO_POLL_INTERVAL_MS)
#       define BROOKESIA_SERVICE_MANAGER_IO_POLL_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_MANAGER_IO_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_MANAGER_IO_POLL_INTERVAL_MS  (5)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////// Service - Client //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_NAME)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_NAME)
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_NAME  CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_NAME
#   else
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_NAME  ("client_io")
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_CORE_ID)
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_CORE_ID  CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_CORE_ID
#   else
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_CORE_ID  (1)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_PRIORITY)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_PRIORITY)
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_PRIORITY  CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_PRIORITY
#   else
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_PRIORITY  (18)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_SIZE)
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_SIZE
#   else
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_SIZE  (5120)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_IN_EXT)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_IN_EXT)
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_IN_EXT  CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_IN_EXT
#   else
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_THREAD_STACK_IN_EXT  (0)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_CLIENT_IO_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_POLL_INTERVAL_MS)
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_POLL_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_MANAGER_CLIENT_IO_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_MANAGER_CLIENT_IO_POLL_INTERVAL_MS  (5)
#   endif
#endif
