#pragma once

#include "lvgl.h"
#include "base/assets/esp_brookesia_base_assets.h"
#include "animations/mmap_generate_boot.h"
#include "animations/mmap_generate_emotion.h"
#include "animations/mmap_generate_icon.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
// Middle (Typically 360x360)
LV_IMG_DECLARE(speaker_image_middle_app_launcher_default_112_112);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_battery_charge_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_battery_level1_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_battery_level2_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_battery_level3_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_battery_level4_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_bluetooth_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_brightness_auto_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_brightness_high_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_brightness_low_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_brightness_medium_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_lock_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_settings_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_volume_high_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_volume_low_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_volume_medium_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_volume_off_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_wifi_48_48);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_wifi_close_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_wifi_level1_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_wifi_level2_20_20);
LV_IMG_DECLARE(speaker_image_middle_quick_settings_wifi_level3_20_20);

#ifdef __cplusplus
}
#endif
