/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#include "brookesia/system_core/macro_configs.h"

#define BROOKESIA_SYSTEM_SUPER_LOG_TAG "SysSuper"
#define BROOKESIA_SYSTEM_SUPER_SYSTEM_NAME "SuperOS"
#define BROOKESIA_SYSTEM_SUPER_SYSTEM_TYPE "super"

#if !defined(BROOKESIA_SYSTEM_SUPER_RESOURCE_DIR)
#   define BROOKESIA_SYSTEM_SUPER_RESOURCE_DIR "/littlefs/system/super"
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_SHELL_RESOURCE_DIR)
#   define BROOKESIA_SYSTEM_SUPER_SHELL_RESOURCE_DIR BROOKESIA_SYSTEM_SUPER_RESOURCE_DIR "/shell"
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_DEBUG_LOG (0)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_ENABLE_PROFILE_LOG)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_PROFILE_LOG)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_PROFILE_LOG CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_PROFILE_LOG
#   else
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_PROFILE_LOG (0)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_ENABLE_STARTUP_OVERLAY)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_STARTUP_OVERLAY)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_STARTUP_OVERLAY CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_STARTUP_OVERLAY
#   else
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_STARTUP_OVERLAY (1)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_STARTUP_ROOT_JSON)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_STARTUP_ROOT_JSON)
#       define BROOKESIA_SYSTEM_SUPER_STARTUP_ROOT_JSON CONFIG_BROOKESIA_SYSTEM_SUPER_STARTUP_ROOT_JSON
#   else
#       define BROOKESIA_SYSTEM_SUPER_STARTUP_ROOT_JSON "startup/root.json"
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_ENABLE_RESOURCE_FONT_COPY)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_RESOURCE_FONT_COPY)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_RESOURCE_FONT_COPY \
            CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_RESOURCE_FONT_COPY
#   elif defined(ESP_PLATFORM)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_RESOURCE_FONT_COPY (0)
#   else
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_RESOURCE_FONT_COPY (1)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_TRANSITION)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_TRANSITION)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_TRANSITION \
            CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_TRANSITION
#   else
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_TRANSITION (1)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_ROOT_JSON)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_ROOT_JSON)
#       define BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_ROOT_JSON CONFIG_BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_ROOT_JSON
#   else
#       define BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_ROOT_JSON "app_launch/root.json"
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_ANIMATION)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_ANIMATION)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_ANIMATION \
            CONFIG_BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_ANIMATION
#   elif defined(ESP_PLATFORM)
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_ANIMATION (0)
#   else
#       define BROOKESIA_SYSTEM_SUPER_ENABLE_APP_LAUNCH_ANIMATION (1)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_POST_COMPLETE_HOLD_MS)
#   if defined(CONFIG_BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_POST_COMPLETE_HOLD_MS)
#       define BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_POST_COMPLETE_HOLD_MS \
            CONFIG_BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_POST_COMPLETE_HOLD_MS
#   else
#       define BROOKESIA_SYSTEM_SUPER_APP_LAUNCH_POST_COMPLETE_HOLD_MS (0)
#   endif
#endif
