/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#define BROOKESIA_SERVICE_DISPLAY_LOG_TAG "SvcDisplay"

#if !defined(BROOKESIA_SERVICE_DISPLAY_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_SERVICE_DISPLAY_ENABLE_AUTO_REGISTER  CONFIG_BROOKESIA_SERVICE_DISPLAY_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_SERVICE_DISPLAY_ENABLE_AUTO_REGISTER  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_DISPLAY_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_SERVICE_DISPLAY_PLUGIN_SYMBOL)
#       define BROOKESIA_SERVICE_DISPLAY_PLUGIN_SYMBOL  service_display_symbol
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_DISPLAY_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_DISPLAY_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_DISPLAY_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_DRAW_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_DRAW_TIMEOUT_MS)
#       define BROOKESIA_SERVICE_DISPLAY_DRAW_TIMEOUT_MS  CONFIG_BROOKESIA_SERVICE_DISPLAY_DRAW_TIMEOUT_MS
#   else
#       define BROOKESIA_SERVICE_DISPLAY_DRAW_TIMEOUT_MS  (5000)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MS)
#       define BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MS \
            CONFIG_BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MS  (20)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MIN_MS)
#   define BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MIN_MS  (5)
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MAX_MS)
#   define BROOKESIA_SERVICE_DISPLAY_TOUCH_POLL_INTERVAL_MAX_MS  (1000)
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////// Backlight /////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_ENABLE_AUTO_LOAD_DATA)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_ENABLE_AUTO_LOAD_DATA)
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_ENABLE_AUTO_LOAD_DATA \
            CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_ENABLE_AUTO_LOAD_DATA
#   else
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_ENABLE_AUTO_LOAD_DATA  (1)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_KV_ERASE_DATA_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_KV_ERASE_DATA_TIMEOUT_MS)
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_KV_ERASE_DATA_TIMEOUT_MS \
            CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_KV_ERASE_DATA_TIMEOUT_MS
#   else
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_KV_ERASE_DATA_TIMEOUT_MS  (20)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_DEFAULT)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_DEFAULT)
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_DEFAULT \
            CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_DEFAULT
#   else
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_DEFAULT  (90)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MIN)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MIN)
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MIN \
            CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MIN
#   else
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MIN  (20)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MAX)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MAX)
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MAX \
            CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MAX
#   else
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_BRIGHTNESS_MAX  (100)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_DEFAULT_ON)
#   if defined(CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_DEFAULT_ON)
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_DEFAULT_ON  CONFIG_BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_DEFAULT_ON
#   else
#       define BROOKESIA_SERVICE_DISPLAY_BACKLIGHT_DEFAULT_ON  (0)
#   endif
#endif
