/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

/* Debug log */
#define BROOKESIA_SERVICE_WIFI_LOG_TAG "SrvWiFi"

#if !defined(BROOKESIA_SERVICE_WIFI_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_WIFI_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_WIFI_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_WIFI_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_WIFI_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_SERVICE_WIFI_SERVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_WIFI_SERVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_WIFI_SERVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_WIFI_SERVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_WIFI_SERVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_WIFI_HAL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_WIFI_HAL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_WIFI_HAL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_WIFI_HAL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_WIFI_HAL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_SERVICE_WIFI_STATE_MACHINE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_WIFI_STATE_MACHINE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_WIFI_STATE_MACHINE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_WIFI_STATE_MACHINE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_WIFI_STATE_MACHINE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif // BROOKESIA_SERVICE_WIFI_ENABLE_DEBUG_LOG

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Task Scheduler /////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/* Task Scheduler - Worker 1 */
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_NAME)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_NAME)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_NAME  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_NAME
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_NAME  "wifi_tsc_worker1"
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_CORE_ID)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_CORE_ID  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_CORE_ID
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_CORE_ID  (0)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_PRIORITY)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_PRIORITY)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_PRIORITY  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_PRIORITY
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_PRIORITY  (5)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_SIZE)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_SIZE
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_SIZE  (10240)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_IN_EXT)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_IN_EXT)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_IN_EXT  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_IN_EXT
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER1_STACK_IN_EXT  (0)
#   endif
#endif
/* Task Scheduler - Worker 2 */
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_NAME)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_NAME)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_NAME  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_NAME
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_NAME  "wifi_tsc_worker2"
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_CORE_ID)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_CORE_ID  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_CORE_ID
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_CORE_ID  (1)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_PRIORITY)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_PRIORITY)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_PRIORITY  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_PRIORITY
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_PRIORITY  (5)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_SIZE)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_SIZE
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_SIZE  (10240)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_IN_EXT)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_IN_EXT)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_IN_EXT  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_IN_EXT
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER2_STACK_IN_EXT  (0)
#   endif
#endif
/* Task Scheduler - Worker poll interval */
#if !defined(BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS)
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_WIFI_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS  (5)
#   endif
#endif
