/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#define BROOKESIA_SYSTEM_CORE_LOG_TAG "SysCore"

#if !defined(BROOKESIA_SYSTEM_CORE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SYSTEM_CORE_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_SYSTEM_CORE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SYSTEM_CORE_ENABLE_DEBUG_LOG (0)
#   endif
#endif

#if BROOKESIA_SYSTEM_CORE_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_SYSTEM_CORE_SYSTEM_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SYSTEM_CORE_SYSTEM_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SYSTEM_CORE_SYSTEM_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_SYSTEM_CORE_SYSTEM_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SYSTEM_CORE_SYSTEM_ENABLE_DEBUG_LOG (1)
#       endif
#   endif
#   if !defined(BROOKESIA_SYSTEM_CORE_SERVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SYSTEM_CORE_SERVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SYSTEM_CORE_SERVICE_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_SYSTEM_CORE_SERVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SYSTEM_CORE_SERVICE_ENABLE_DEBUG_LOG (1)
#       endif
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_SYSTEM_ENABLE_DEBUG_LOG)
#   define BROOKESIA_SYSTEM_CORE_SYSTEM_ENABLE_DEBUG_LOG (0)
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_SERVICE_ENABLE_DEBUG_LOG)
#   define BROOKESIA_SYSTEM_CORE_SERVICE_ENABLE_DEBUG_LOG (0)
#endif

#if !defined(BROOKESIA_SYSTEM_HEAP_TRACE_APP_START)
#   if defined(CONFIG_BROOKESIA_SYSTEM_HEAP_TRACE_APP_START)
#       define BROOKESIA_SYSTEM_HEAP_TRACE_APP_START CONFIG_BROOKESIA_SYSTEM_HEAP_TRACE_APP_START
#   else
#       define BROOKESIA_SYSTEM_HEAP_TRACE_APP_START (0)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG)
#       define BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG CONFIG_BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG
#   else
#       define BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG (0)
#   endif
#endif

#if BROOKESIA_SYSTEM_HEAP_TRACE_APP_START && !BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG
#   undef BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG
#   define BROOKESIA_SYSTEM_CORE_ENABLE_PROFILE_LOG (1)
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_RUNTIME_ASYNC_DEBUG_PROBE)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_RUNTIME_ASYNC_DEBUG_PROBE)
#       define BROOKESIA_SYSTEM_CORE_RUNTIME_ASYNC_DEBUG_PROBE \
            CONFIG_BROOKESIA_SYSTEM_CORE_RUNTIME_ASYNC_DEBUG_PROBE
#   else
#       define BROOKESIA_SYSTEM_CORE_RUNTIME_ASYNC_DEBUG_PROBE (0)
#   endif
#endif

#define BROOKESIA_SYSTEM_CORE_SERVICE_NAME "SystemCore"
#define BROOKESIA_SYSTEM_CORE_GUI_SERVICE_NAME "SystemGui"
#define BROOKESIA_SYSTEM_CORE_TIMER_SERVICE_NAME "SystemTimer"
#define BROOKESIA_SYSTEM_CORE_SYSTEM_NAME "Brookesia Core"
#define BROOKESIA_SYSTEM_CORE_DEFAULT_SYSTEM_TYPE "core"
#define BROOKESIA_SYSTEM_CORE_DEFAULT_SCREEN_PATH "/root"

#if !defined(BROOKESIA_SYSTEM_CORE_RUNTIME_APP_MAX_Z_ORDER)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_RUNTIME_APP_MAX_Z_ORDER)
#       define BROOKESIA_SYSTEM_CORE_RUNTIME_APP_MAX_Z_ORDER CONFIG_BROOKESIA_SYSTEM_CORE_RUNTIME_APP_MAX_Z_ORDER
#   else
#       define BROOKESIA_SYSTEM_CORE_RUNTIME_APP_MAX_Z_ORDER (100)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_NAME_PREFIX)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_NAME_PREFIX)
#       define BROOKESIA_SYSTEM_CORE_WORKER_NAME_PREFIX CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_NAME_PREFIX
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_NAME_PREFIX "System"
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_PRIORITY)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_PRIORITY)
#       define BROOKESIA_SYSTEM_CORE_WORKER_PRIORITY CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_PRIORITY
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_PRIORITY (10)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_STACK_SIZE)
#       define BROOKESIA_SYSTEM_CORE_WORKER_STACK_SIZE CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_STACK_SIZE
#   elif defined(ESP_PLATFORM)
#       define BROOKESIA_SYSTEM_CORE_WORKER_STACK_SIZE (65536)
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_STACK_SIZE (32768)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_STACK_IN_EXT)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_STACK_IN_EXT)
#       define BROOKESIA_SYSTEM_CORE_WORKER_STACK_IN_EXT CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_STACK_IN_EXT
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_STACK_IN_EXT (0)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_POLL_INTERVAL_MS)
#       define BROOKESIA_SYSTEM_CORE_WORKER_POLL_INTERVAL_MS CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_POLL_INTERVAL_MS (2)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_NUM)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_NUM)
#       define BROOKESIA_SYSTEM_CORE_WORKER_NUM CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_NUM
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_NUM (3)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_0_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_0_CORE_ID)
#       define BROOKESIA_SYSTEM_CORE_WORKER_0_CORE_ID CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_0_CORE_ID
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_0_CORE_ID (0)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_1_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_1_CORE_ID)
#       define BROOKESIA_SYSTEM_CORE_WORKER_1_CORE_ID CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_1_CORE_ID
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_1_CORE_ID (1)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_2_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_2_CORE_ID)
#       define BROOKESIA_SYSTEM_CORE_WORKER_2_CORE_ID CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_2_CORE_ID
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_2_CORE_ID (-1)
#   endif
#endif

#if !defined(BROOKESIA_SYSTEM_CORE_WORKER_3_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_3_CORE_ID)
#       define BROOKESIA_SYSTEM_CORE_WORKER_3_CORE_ID CONFIG_BROOKESIA_SYSTEM_CORE_WORKER_3_CORE_ID
#   else
#       define BROOKESIA_SYSTEM_CORE_WORKER_3_CORE_ID (-1)
#   endif
#endif
