/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#ifndef _SMART_GADGET_UI_COMP_HOOK_H
#define _SMART_GADGET_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_panel_alarm_comp_create_hook(lv_obj_t *comp);
void ui_comp_panel_clock_dot_create_hook(lv_obj_t *comp);
void ui_comp_panel_scrolldots_create_hook(lv_obj_t *comp);
void ui_comp_label_small_label_create_hook(lv_obj_t *comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
