/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#if !defined(BROOKESIA_SERVICE_USB_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_SERVICE_USB_ENABLE_AUTO_REGISTER CONFIG_BROOKESIA_SERVICE_USB_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_SERVICE_USB_ENABLE_AUTO_REGISTER (0)
#   endif
#endif

#if BROOKESIA_SERVICE_USB_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_SERVICE_USB_PLUGIN_SYMBOL)
#       define BROOKESIA_SERVICE_USB_PLUGIN_SYMBOL service_usb_symbol
#   endif
#endif

#define BROOKESIA_SERVICE_USB_LOG_TAG "SvcUsb"

#if !defined(BROOKESIA_SERVICE_USB_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_USB_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_SERVICE_USB_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_USB_ENABLE_DEBUG_LOG (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_UPLOAD_ROOT)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_UPLOAD_ROOT)
#       define BROOKESIA_SERVICE_USB_UPLOAD_ROOT CONFIG_BROOKESIA_SERVICE_USB_UPLOAD_ROOT
#   else
#       define BROOKESIA_SERVICE_USB_UPLOAD_ROOT "/littlefs/usb"
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_MAX_TRANSFER_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_MAX_TRANSFER_SIZE)
#       define BROOKESIA_SERVICE_USB_MAX_TRANSFER_SIZE CONFIG_BROOKESIA_SERVICE_USB_MAX_TRANSFER_SIZE
#   else
#       define BROOKESIA_SERVICE_USB_MAX_TRANSFER_SIZE (8 * 1024 * 1024)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_FRAME_PAYLOAD_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_FRAME_PAYLOAD_SIZE)
#       define BROOKESIA_SERVICE_USB_FRAME_PAYLOAD_SIZE CONFIG_BROOKESIA_SERVICE_USB_FRAME_PAYLOAD_SIZE
#   else
#       define BROOKESIA_SERVICE_USB_FRAME_PAYLOAD_SIZE (16 * 1024)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_RX_QUEUE_LENGTH)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_RX_QUEUE_LENGTH)
#       define BROOKESIA_SERVICE_USB_RX_QUEUE_LENGTH CONFIG_BROOKESIA_SERVICE_USB_RX_QUEUE_LENGTH
#   else
#       define BROOKESIA_SERVICE_USB_RX_QUEUE_LENGTH (8)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_COMMAND_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_COMMAND_TIMEOUT_MS)
#       define BROOKESIA_SERVICE_USB_COMMAND_TIMEOUT_MS CONFIG_BROOKESIA_SERVICE_USB_COMMAND_TIMEOUT_MS
#   else
#       define BROOKESIA_SERVICE_USB_COMMAND_TIMEOUT_MS (30000)
#   endif
#endif

#define BROOKESIA_SERVICE_USB_TRANSPORT "serial_jtag"
#define BROOKESIA_SERVICE_USB_SESSION_MODE "exclusive"

#if !defined(BROOKESIA_SERVICE_USB_SERIAL_JTAG_RX_BUFFER_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_SERIAL_JTAG_RX_BUFFER_SIZE)
#       define BROOKESIA_SERVICE_USB_SERIAL_JTAG_RX_BUFFER_SIZE \
            CONFIG_BROOKESIA_SERVICE_USB_SERIAL_JTAG_RX_BUFFER_SIZE
#   else
#       define BROOKESIA_SERVICE_USB_SERIAL_JTAG_RX_BUFFER_SIZE (4096)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_SERIAL_JTAG_TX_BUFFER_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_SERIAL_JTAG_TX_BUFFER_SIZE)
#       define BROOKESIA_SERVICE_USB_SERIAL_JTAG_TX_BUFFER_SIZE \
            CONFIG_BROOKESIA_SERVICE_USB_SERIAL_JTAG_TX_BUFFER_SIZE
#   else
#       define BROOKESIA_SERVICE_USB_SERIAL_JTAG_TX_BUFFER_SIZE (4096)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_UART_PORT)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_UART_PORT)
#       define BROOKESIA_SERVICE_USB_UART_PORT CONFIG_BROOKESIA_SERVICE_USB_UART_PORT
#   else
#       define BROOKESIA_SERVICE_USB_UART_PORT (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_UART_BAUDRATE)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_UART_BAUDRATE)
#       define BROOKESIA_SERVICE_USB_UART_BAUDRATE CONFIG_BROOKESIA_SERVICE_USB_UART_BAUDRATE
#   else
#       define BROOKESIA_SERVICE_USB_UART_BAUDRATE (921600)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_UART_RX_BUFFER_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_UART_RX_BUFFER_SIZE)
#       define BROOKESIA_SERVICE_USB_UART_RX_BUFFER_SIZE CONFIG_BROOKESIA_SERVICE_USB_UART_RX_BUFFER_SIZE
#   else
#       define BROOKESIA_SERVICE_USB_UART_RX_BUFFER_SIZE (16384)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_USB_UART_TX_BUFFER_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_USB_UART_TX_BUFFER_SIZE)
#       define BROOKESIA_SERVICE_USB_UART_TX_BUFFER_SIZE CONFIG_BROOKESIA_SERVICE_USB_UART_TX_BUFFER_SIZE
#   else
#       define BROOKESIA_SERVICE_USB_UART_TX_BUFFER_SIZE (4096)
#   endif
#endif

#if defined(CONFIG_ESP_CONSOLE_UART_NUM)
#   define BROOKESIA_SERVICE_USB_CONSOLE_UART_NUM CONFIG_ESP_CONSOLE_UART_NUM
#else
#   define BROOKESIA_SERVICE_USB_CONSOLE_UART_NUM (-1)
#endif

#if defined(CONFIG_ESP_CONSOLE_UART_BAUDRATE)
#   define BROOKESIA_SERVICE_USB_CONSOLE_UART_BAUDRATE CONFIG_ESP_CONSOLE_UART_BAUDRATE
#else
#   define BROOKESIA_SERVICE_USB_CONSOLE_UART_BAUDRATE (115200)
#endif

#define BROOKESIA_SERVICE_USB_PROTOCOL_VERSION (1)
#define BROOKESIA_SERVICE_USB_FRAME_HEADER_SIZE (24)
