/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#define BROOKESIA_HAL_LINUX_LOG_TAG "HalLinux"

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_SYSTEM_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_SYSTEM_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_SYSTEM_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_SYSTEM_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_SYSTEM_DEVICE  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_NETWORK_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_NETWORK_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_NETWORK_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_NETWORK_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_NETWORK_DEVICE  (1)
#   endif
#endif

#if BROOKESIA_HAL_LINUX_ENABLE_NETWORK_DEVICE
#   if !defined(BROOKESIA_HAL_LINUX_NETWORK_ENABLE_SNTP_CLIENT_IMPL)
#       if defined(CONFIG_BROOKESIA_HAL_LINUX_NETWORK_ENABLE_SNTP_CLIENT_IMPL)
#           define BROOKESIA_HAL_LINUX_NETWORK_ENABLE_SNTP_CLIENT_IMPL  CONFIG_BROOKESIA_HAL_LINUX_NETWORK_ENABLE_SNTP_CLIENT_IMPL
#       else
#           define BROOKESIA_HAL_LINUX_NETWORK_ENABLE_SNTP_CLIENT_IMPL  (1)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_LINUX_NETWORK_ENABLE_HTTP_CLIENT_IMPL)
#       if defined(CONFIG_BROOKESIA_HAL_LINUX_NETWORK_ENABLE_HTTP_CLIENT_IMPL)
#           define BROOKESIA_HAL_LINUX_NETWORK_ENABLE_HTTP_CLIENT_IMPL  CONFIG_BROOKESIA_HAL_LINUX_NETWORK_ENABLE_HTTP_CLIENT_IMPL
#       else
#           define BROOKESIA_HAL_LINUX_NETWORK_ENABLE_HTTP_CLIENT_IMPL  (1)
#       endif
#   endif
#else
#   define BROOKESIA_HAL_LINUX_NETWORK_ENABLE_SNTP_CLIENT_IMPL  (0)
#   define BROOKESIA_HAL_LINUX_NETWORK_ENABLE_HTTP_CLIENT_IMPL  (0)
#endif

#if !defined(BROOKESIA_HAL_LINUX_SYSTEM_ENABLE_OTA_UPDATER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_SYSTEM_ENABLE_OTA_UPDATER_IMPL)
#       define BROOKESIA_HAL_LINUX_SYSTEM_ENABLE_OTA_UPDATER_IMPL  \
            CONFIG_BROOKESIA_HAL_LINUX_SYSTEM_ENABLE_OTA_UPDATER_IMPL
#   else
#       define BROOKESIA_HAL_LINUX_SYSTEM_ENABLE_OTA_UPDATER_IMPL  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_AUDIO_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_AUDIO_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_AUDIO_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_AUDIO_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_AUDIO_DEVICE  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_VIDEO_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_VIDEO_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_VIDEO_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_VIDEO_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_VIDEO_DEVICE  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_DISPLAY_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_DISPLAY_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_DISPLAY_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_DISPLAY_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_DISPLAY_DEVICE  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_POWER_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_POWER_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_POWER_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_POWER_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_POWER_DEVICE  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_WIFI_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_WIFI_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_WIFI_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_WIFI_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_WIFI_DEVICE  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_ENABLE_STORAGE_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_ENABLE_STORAGE_DEVICE)
#       define BROOKESIA_HAL_LINUX_ENABLE_STORAGE_DEVICE  CONFIG_BROOKESIA_HAL_LINUX_ENABLE_STORAGE_DEVICE
#   else
#       define BROOKESIA_HAL_LINUX_ENABLE_STORAGE_DEVICE  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_SYSTEM_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_SYSTEM_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_SYSTEM_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_SYSTEM_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_SYSTEM_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_NETWORK_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_NETWORK_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_NETWORK_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_NETWORK_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_NETWORK_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY)
#       define BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY  \
            CONFIG_BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY
#   else
#       define BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_READ_THROTTLE_BYTES_PER_SEC)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_READ_THROTTLE_BYTES_PER_SEC)
#       define BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_READ_THROTTLE_BYTES_PER_SEC  \
            CONFIG_BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_READ_THROTTLE_BYTES_PER_SEC
#   else
#       define BROOKESIA_HAL_LINUX_NETWORK_HTTP_CLIENT_READ_THROTTLE_BYTES_PER_SEC  (102400)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_MEDIA_BACKEND_STUB)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_MEDIA_BACKEND_FFMPEG_PORTAUDIO)
#       define BROOKESIA_HAL_LINUX_MEDIA_BACKEND_FFMPEG_PORTAUDIO_AVAILABLE  \
            CONFIG_BROOKESIA_HAL_LINUX_MEDIA_BACKEND_FFMPEG_PORTAUDIO
#       define BROOKESIA_HAL_LINUX_MEDIA_BACKEND_STUB  (!CONFIG_BROOKESIA_HAL_LINUX_MEDIA_BACKEND_FFMPEG_PORTAUDIO)
#   else
#       define BROOKESIA_HAL_LINUX_MEDIA_BACKEND_STUB  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_WIFI_BACKEND_STUB)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_WIFI_BACKEND_NETWORKMANAGER)
#       define BROOKESIA_HAL_LINUX_WIFI_BACKEND_NETWORKMANAGER_AVAILABLE  \
            CONFIG_BROOKESIA_HAL_LINUX_WIFI_BACKEND_NETWORKMANAGER
#       define BROOKESIA_HAL_LINUX_WIFI_BACKEND_STUB  (!CONFIG_BROOKESIA_HAL_LINUX_WIFI_BACKEND_NETWORKMANAGER)
#   else
#       define BROOKESIA_HAL_LINUX_WIFI_BACKEND_STUB  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_DISPLAY_BACKEND_STUB)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_DISPLAY_BACKEND_SDL2)
#       define BROOKESIA_HAL_LINUX_DISPLAY_BACKEND_SDL2_AVAILABLE  CONFIG_BROOKESIA_HAL_LINUX_DISPLAY_BACKEND_SDL2
#       define BROOKESIA_HAL_LINUX_DISPLAY_BACKEND_STUB  (!CONFIG_BROOKESIA_HAL_LINUX_DISPLAY_BACKEND_SDL2)
#   else
#       define BROOKESIA_HAL_LINUX_DISPLAY_BACKEND_STUB  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_POWER_BACKEND_STUB)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_POWER_BACKEND_UPOWER)
#       define BROOKESIA_HAL_LINUX_POWER_BACKEND_UPOWER_AVAILABLE  CONFIG_BROOKESIA_HAL_LINUX_POWER_BACKEND_UPOWER
#       define BROOKESIA_HAL_LINUX_POWER_BACKEND_STUB  (!CONFIG_BROOKESIA_HAL_LINUX_POWER_BACKEND_UPOWER)
#   else
#       define BROOKESIA_HAL_LINUX_POWER_BACKEND_STUB  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_VIDEO_BACKEND_STUB)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_VIDEO_BACKEND_FFMPEG_V4L2)
#       define BROOKESIA_HAL_LINUX_VIDEO_BACKEND_FFMPEG_V4L2_AVAILABLE  \
            CONFIG_BROOKESIA_HAL_LINUX_VIDEO_BACKEND_FFMPEG_V4L2
#       define BROOKESIA_HAL_LINUX_VIDEO_BACKEND_STUB  (!CONFIG_BROOKESIA_HAL_LINUX_VIDEO_BACKEND_FFMPEG_V4L2)
#   else
#       define BROOKESIA_HAL_LINUX_VIDEO_BACKEND_STUB  (1)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_AUDIO_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_AUDIO_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_AUDIO_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_VIDEO_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_VIDEO_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_VIDEO_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_VIDEO_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_VIDEO_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_DISPLAY_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_POWER_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_POWER_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_POWER_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_POWER_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_POWER_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_WIFI_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_WIFI_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_WIFI_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_WIFI_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_WIFI_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_HAL_LINUX_STORAGE_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_LINUX_STORAGE_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_LINUX_STORAGE_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_LINUX_STORAGE_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_LINUX_STORAGE_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif
