/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#include "../ui.h"

lv_obj_t *ui_Screen_POS_S5 = NULL;
lv_obj_t *ui_POS_S5_Image_IMG_Ok_1 = NULL;
lv_obj_t *ui_POS_S5_Image_IMG_Ok_2 = NULL;
lv_obj_t *ui_POS_S5_Label_Label_Succesful = NULL;
lv_obj_t *ui_POS_S5_Label_Label_press_contimue = NULL;
lv_obj_t *ui_POS_S5_Panel_BTN_Next_2 = NULL;
lv_obj_t *ui_POS_S5_Image_IMG_Arrow1 = NULL;
// event functions

// build functions

void ui_Screen_POS_S5_screen_init(void)
{
    ui_Screen_POS_S5 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_POS_S5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_POS_S5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_POS_S5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S5_Image_IMG_Ok_1 = lv_image_create(ui_Screen_POS_S5);
    lv_image_set_src(ui_POS_S5_Image_IMG_Ok_1, &ui_img_ok_png);
    lv_obj_set_width(ui_POS_S5_Image_IMG_Ok_1, LV_SIZE_CONTENT);   /// 124
    lv_obj_set_height(ui_POS_S5_Image_IMG_Ok_1, LV_SIZE_CONTENT);    /// 165
    lv_obj_set_x(ui_POS_S5_Image_IMG_Ok_1, 0);
    lv_obj_set_y(ui_POS_S5_Image_IMG_Ok_1, 60);
    lv_obj_set_align(ui_POS_S5_Image_IMG_Ok_1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_POS_S5_Image_IMG_Ok_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S5_Image_IMG_Ok_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_POS_S5_Image_IMG_Ok_1, 62, 62);
    lv_obj_set_style_opa(ui_POS_S5_Image_IMG_Ok_1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S5_Image_IMG_Ok_2 = lv_image_create(ui_Screen_POS_S5);
    lv_image_set_src(ui_POS_S5_Image_IMG_Ok_2, &ui_img_ok_png);
    lv_obj_set_width(ui_POS_S5_Image_IMG_Ok_2, LV_SIZE_CONTENT);   /// 124
    lv_obj_set_height(ui_POS_S5_Image_IMG_Ok_2, LV_SIZE_CONTENT);    /// 165
    lv_obj_set_x(ui_POS_S5_Image_IMG_Ok_2, 0);
    lv_obj_set_y(ui_POS_S5_Image_IMG_Ok_2, 60);
    lv_obj_set_align(ui_POS_S5_Image_IMG_Ok_2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_POS_S5_Image_IMG_Ok_2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S5_Image_IMG_Ok_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_pivot(ui_POS_S5_Image_IMG_Ok_2, 62, 62);

    ui_POS_S5_Label_Label_Succesful = lv_label_create(ui_Screen_POS_S5);
    lv_obj_set_width(ui_POS_S5_Label_Label_Succesful, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S5_Label_Label_Succesful, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S5_Label_Label_Succesful, 0);
    lv_obj_set_y(ui_POS_S5_Label_Label_Succesful, -122);
    lv_obj_set_align(ui_POS_S5_Label_Label_Succesful, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_POS_S5_Label_Label_Succesful, "Payment\nSuccesful!");
    lv_obj_set_style_text_color(ui_POS_S5_Label_Label_Succesful, lv_color_hex(0x0B1019), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S5_Label_Label_Succesful, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S5_Label_Label_Succesful, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S5_Label_Label_Succesful, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S5_Label_Label_press_contimue = lv_label_create(ui_Screen_POS_S5);
    lv_obj_set_width(ui_POS_S5_Label_Label_press_contimue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S5_Label_Label_press_contimue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S5_Label_Label_press_contimue, 0);
    lv_obj_set_y(ui_POS_S5_Label_Label_press_contimue, -99);
    lv_obj_set_align(ui_POS_S5_Label_Label_press_contimue, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_POS_S5_Label_Label_press_contimue, "Press to contimue");
    lv_obj_set_style_text_color(ui_POS_S5_Label_Label_press_contimue, lv_color_hex(0x7F848F),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S5_Label_Label_press_contimue, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S5_Label_Label_press_contimue, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S5_Label_Label_press_contimue, &lv_font_montserrat_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S5_Panel_BTN_Next_2 = lv_obj_create(ui_Screen_POS_S5);
    lv_obj_set_width(ui_POS_S5_Panel_BTN_Next_2, 60);
    lv_obj_set_height(ui_POS_S5_Panel_BTN_Next_2, 60);
    lv_obj_set_x(ui_POS_S5_Panel_BTN_Next_2, 0);
    lv_obj_set_y(ui_POS_S5_Panel_BTN_Next_2, -32);
    lv_obj_set_align(ui_POS_S5_Panel_BTN_Next_2, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_POS_S5_Panel_BTN_Next_2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_POS_S5_Panel_BTN_Next_2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S5_Panel_BTN_Next_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S5_Panel_BTN_Next_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S5_Panel_BTN_Next_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S5_Panel_BTN_Next_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POS_S5_Panel_BTN_Next_2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_POS_S5_Panel_BTN_Next_2, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_POS_S5_Panel_BTN_Next_2, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_POS_S5_Panel_BTN_Next_2, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_POS_S5_Image_IMG_Arrow1 = lv_image_create(ui_POS_S5_Panel_BTN_Next_2);
    lv_image_set_src(ui_POS_S5_Image_IMG_Arrow1, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_POS_S5_Image_IMG_Arrow1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_POS_S5_Image_IMG_Arrow1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_POS_S5_Image_IMG_Arrow1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_POS_S5_Image_IMG_Arrow1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S5_Image_IMG_Arrow1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen_POS_S5_screen_destroy(void)
{
    if (ui_Screen_POS_S5) {
        lv_obj_del(ui_Screen_POS_S5);
    }

    // NULL screen variables
    ui_Screen_POS_S5 = NULL;
    ui_POS_S5_Image_IMG_Ok_1 = NULL;
    ui_POS_S5_Image_IMG_Ok_2 = NULL;
    ui_POS_S5_Label_Label_Succesful = NULL;
    ui_POS_S5_Label_Label_press_contimue = NULL;
    ui_POS_S5_Panel_BTN_Next_2 = NULL;
    ui_POS_S5_Image_IMG_Arrow1 = NULL;

}
