/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#include "../ui.h"

lv_obj_t *ui_Screen_POS_S4 = NULL;
lv_obj_t *ui_POS_S4_Label_Label_Amount_Pirce2 = NULL;
lv_obj_t *ui_POS_S4_Label_Label_Amount_Title = NULL;
lv_obj_t *ui_POS_S4_Label_Label_QR_ready = NULL;
lv_obj_t *ui_POS_S4_Image_IMG_QR_Code = NULL;
lv_obj_t *ui_POS_S4_Label_Label_BTC_Address = NULL;
lv_obj_t *ui_POS_S4_Label_Label_Cancel = NULL;
// event functions

// build functions

void ui_Screen_POS_S4_screen_init(void)
{
    ui_Screen_POS_S4 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_POS_S4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_POS_S4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_POS_S4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S4_Label_Label_Amount_Pirce2 = lv_label_create(ui_Screen_POS_S4);
    lv_obj_set_width(ui_POS_S4_Label_Label_Amount_Pirce2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S4_Label_Label_Amount_Pirce2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S4_Label_Label_Amount_Pirce2, -5);
    lv_obj_set_y(ui_POS_S4_Label_Label_Amount_Pirce2, -157);
    lv_obj_set_align(ui_POS_S4_Label_Label_Amount_Pirce2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_POS_S4_Label_Label_Amount_Pirce2, "$ 1.99");
    lv_obj_set_style_text_font(ui_POS_S4_Label_Label_Amount_Pirce2, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S4_Label_Label_Amount_Title = lv_label_create(ui_Screen_POS_S4);
    lv_obj_set_width(ui_POS_S4_Label_Label_Amount_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S4_Label_Label_Amount_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S4_Label_Label_Amount_Title, -4);
    lv_obj_set_y(ui_POS_S4_Label_Label_Amount_Title, 37);
    lv_obj_set_align(ui_POS_S4_Label_Label_Amount_Title, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_POS_S4_Label_Label_Amount_Title, "Amount");
    lv_obj_set_style_text_color(ui_POS_S4_Label_Label_Amount_Title, lv_color_hex(0x0B1019),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S4_Label_Label_Amount_Title, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S4_Label_Label_Amount_Title, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S4_Label_Label_Amount_Title, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S4_Label_Label_QR_ready = lv_label_create(ui_Screen_POS_S4);
    lv_obj_set_width(ui_POS_S4_Label_Label_QR_ready, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S4_Label_Label_QR_ready, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S4_Label_Label_QR_ready, -2);
    lv_obj_set_y(ui_POS_S4_Label_Label_QR_ready, 55);
    lv_obj_set_align(ui_POS_S4_Label_Label_QR_ready, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_POS_S4_Label_Label_QR_ready, "QR code ready for scanning");
    lv_obj_set_style_text_color(ui_POS_S4_Label_Label_QR_ready, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S4_Label_Label_QR_ready, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S4_Label_Label_QR_ready, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S4_Label_Label_QR_ready, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S4_Image_IMG_QR_Code = lv_image_create(ui_Screen_POS_S4);
    lv_image_set_src(ui_POS_S4_Image_IMG_QR_Code, &ui_img_img_qr_png);
    lv_obj_set_width(ui_POS_S4_Image_IMG_QR_Code, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_POS_S4_Image_IMG_QR_Code, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_POS_S4_Image_IMG_QR_Code, -4);
    lv_obj_set_y(ui_POS_S4_Image_IMG_QR_Code, -10);
    lv_obj_set_align(ui_POS_S4_Image_IMG_QR_Code, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_POS_S4_Image_IMG_QR_Code, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S4_Image_IMG_QR_Code, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_POS_S4_Image_IMG_QR_Code, 200);
    lv_obj_set_style_bg_main_stop(ui_POS_S4_Image_IMG_QR_Code, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S4_Image_IMG_QR_Code, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POS_S4_Image_IMG_QR_Code, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_POS_S4_Image_IMG_QR_Code, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_POS_S4_Image_IMG_QR_Code, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_POS_S4_Image_IMG_QR_Code, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_POS_S4_Label_Label_BTC_Address = lv_label_create(ui_Screen_POS_S4);
    lv_obj_set_width(ui_POS_S4_Label_Label_BTC_Address, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S4_Label_Label_BTC_Address, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S4_Label_Label_BTC_Address, -1);
    lv_obj_set_y(ui_POS_S4_Label_Label_BTC_Address, -58);
    lv_obj_set_align(ui_POS_S4_Label_Label_BTC_Address, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_POS_S4_Label_Label_BTC_Address, "138u1Hsm1uGrDA9hG\nzKxeUEkW19Dc6t9Uq");
    lv_obj_set_style_text_color(ui_POS_S4_Label_Label_BTC_Address, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S4_Label_Label_BTC_Address, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S4_Label_Label_BTC_Address, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S4_Label_Label_BTC_Address, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S4_Label_Label_Cancel = lv_label_create(ui_Screen_POS_S4);
    lv_obj_set_width(ui_POS_S4_Label_Label_Cancel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S4_Label_Label_Cancel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S4_Label_Label_Cancel, 1);
    lv_obj_set_y(ui_POS_S4_Label_Label_Cancel, -35);
    lv_obj_set_align(ui_POS_S4_Label_Label_Cancel, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_POS_S4_Label_Label_Cancel, "Cancel Payment");
    lv_obj_add_flag(ui_POS_S4_Label_Label_Cancel, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_POS_S4_Label_Label_Cancel, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S4_Label_Label_Cancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S4_Label_Label_Cancel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S4_Label_Label_Cancel, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen_POS_S4_screen_destroy(void)
{
    if (ui_Screen_POS_S4) {
        lv_obj_del(ui_Screen_POS_S4);
    }

    // NULL screen variables
    ui_Screen_POS_S4 = NULL;
    ui_POS_S4_Label_Label_Amount_Pirce2 = NULL;
    ui_POS_S4_Label_Label_Amount_Title = NULL;
    ui_POS_S4_Label_Label_QR_ready = NULL;
    ui_POS_S4_Image_IMG_QR_Code = NULL;
    ui_POS_S4_Label_Label_BTC_Address = NULL;
    ui_POS_S4_Label_Label_Cancel = NULL;

}
