/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#include "../ui.h"

lv_obj_t *ui_Screen_POS_S1 = NULL;
lv_obj_t *ui_POS_S1_Panel_Circle_1 = NULL;
lv_obj_t *ui_POS_S1_Panel_Circle_2 = NULL;
lv_obj_t *ui_POS_S1_Image_IMG_POS = NULL;
lv_obj_t *ui_POS_S1_Label_Label_card_and_crypto = NULL;
lv_obj_t *ui_POS_S1_Label_Label_Lets_get = NULL;
lv_obj_t *ui_POS_S1_Panel_BTN_Next = NULL;
lv_obj_t *ui_POS_S1_Image_IMG_Arrow = NULL;
// event functions

// build functions

void ui_Screen_POS_S1_screen_init(void)
{
    ui_Screen_POS_S1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_POS_S1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_POS_S1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_POS_S1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S1_Panel_Circle_1 = lv_obj_create(ui_Screen_POS_S1);
    lv_obj_set_width(ui_POS_S1_Panel_Circle_1, 170);
    lv_obj_set_height(ui_POS_S1_Panel_Circle_1, 170);
    lv_obj_set_x(ui_POS_S1_Panel_Circle_1, 0);
    lv_obj_set_y(ui_POS_S1_Panel_Circle_1, -90);
    lv_obj_set_align(ui_POS_S1_Panel_Circle_1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_POS_S1_Panel_Circle_1, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_POS_S1_Panel_Circle_1, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S1_Panel_Circle_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S1_Panel_Circle_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S1_Panel_Circle_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S1_Panel_Circle_1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S1_Panel_Circle_2 = lv_obj_create(ui_Screen_POS_S1);
    lv_obj_set_width(ui_POS_S1_Panel_Circle_2, 200);
    lv_obj_set_height(ui_POS_S1_Panel_Circle_2, 200);
    lv_obj_set_x(ui_POS_S1_Panel_Circle_2, 0);
    lv_obj_set_y(ui_POS_S1_Panel_Circle_2, -90);
    lv_obj_set_align(ui_POS_S1_Panel_Circle_2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_POS_S1_Panel_Circle_2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_POS_S1_Panel_Circle_2, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S1_Panel_Circle_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S1_Panel_Circle_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S1_Panel_Circle_2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S1_Panel_Circle_2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_POS_S1_Panel_Circle_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S1_Image_IMG_POS = lv_image_create(ui_Screen_POS_S1);
    lv_image_set_src(ui_POS_S1_Image_IMG_POS, &ui_img_img_app_pos_png);
    lv_obj_set_width(ui_POS_S1_Image_IMG_POS, 124);
    lv_obj_set_height(ui_POS_S1_Image_IMG_POS, 165);
    lv_obj_set_x(ui_POS_S1_Image_IMG_POS, 4);
    lv_obj_set_y(ui_POS_S1_Image_IMG_POS, 0);
    lv_obj_set_align(ui_POS_S1_Image_IMG_POS, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_POS_S1_Image_IMG_POS, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S1_Image_IMG_POS, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_POS_S1_Image_IMG_POS, LV_IMAGE_ALIGN_TILE);

    ui_POS_S1_Label_Label_card_and_crypto = lv_label_create(ui_Screen_POS_S1);
    lv_obj_set_width(ui_POS_S1_Label_Label_card_and_crypto, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S1_Label_Label_card_and_crypto, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S1_Label_Label_card_and_crypto, 0);
    lv_obj_set_y(ui_POS_S1_Label_Label_card_and_crypto, -120);
    lv_obj_set_align(ui_POS_S1_Label_Label_card_and_crypto, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_POS_S1_Label_Label_card_and_crypto, "Card and Crypto\nPayment Solution");
    lv_obj_set_style_text_color(ui_POS_S1_Label_Label_card_and_crypto, lv_color_hex(0x0B1019),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S1_Label_Label_card_and_crypto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S1_Label_Label_card_and_crypto, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S1_Label_Label_card_and_crypto, &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S1_Label_Label_Lets_get = lv_label_create(ui_Screen_POS_S1);
    lv_obj_set_width(ui_POS_S1_Label_Label_Lets_get, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S1_Label_Label_Lets_get, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S1_Label_Label_Lets_get, 0);
    lv_obj_set_y(ui_POS_S1_Label_Label_Lets_get, -90);
    lv_obj_set_align(ui_POS_S1_Label_Label_Lets_get, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_POS_S1_Label_Label_Lets_get, "Let's get to work");
    lv_obj_set_style_text_color(ui_POS_S1_Label_Label_Lets_get, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S1_Label_Label_Lets_get, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S1_Label_Label_Lets_get, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S1_Label_Label_Lets_get, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S1_Panel_BTN_Next = lv_obj_create(ui_Screen_POS_S1);
    lv_obj_set_width(ui_POS_S1_Panel_BTN_Next, 60);
    lv_obj_set_height(ui_POS_S1_Panel_BTN_Next, 60);
    lv_obj_set_x(ui_POS_S1_Panel_BTN_Next, 0);
    lv_obj_set_y(ui_POS_S1_Panel_BTN_Next, -20);
    lv_obj_set_align(ui_POS_S1_Panel_BTN_Next, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_radius(ui_POS_S1_Panel_BTN_Next, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_POS_S1_Panel_BTN_Next, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S1_Panel_BTN_Next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S1_Panel_BTN_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S1_Panel_BTN_Next, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S1_Panel_BTN_Next, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_POS_S1_Panel_BTN_Next, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_POS_S1_Panel_BTN_Next, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_POS_S1_Panel_BTN_Next, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_POS_S1_Panel_BTN_Next, 0, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_POS_S1_Image_IMG_Arrow = lv_image_create(ui_POS_S1_Panel_BTN_Next);
    lv_image_set_src(ui_POS_S1_Image_IMG_Arrow, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_POS_S1_Image_IMG_Arrow, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_POS_S1_Image_IMG_Arrow, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_POS_S1_Image_IMG_Arrow, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_POS_S1_Image_IMG_Arrow, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S1_Image_IMG_Arrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen_POS_S1_screen_destroy(void)
{
    if (ui_Screen_POS_S1) {
        lv_obj_del(ui_Screen_POS_S1);
    }

    // NULL screen variables
    ui_Screen_POS_S1 = NULL;
    ui_POS_S1_Panel_Circle_1 = NULL;
    ui_POS_S1_Panel_Circle_2 = NULL;
    ui_POS_S1_Image_IMG_POS = NULL;
    ui_POS_S1_Label_Label_card_and_crypto = NULL;
    ui_POS_S1_Label_Label_Lets_get = NULL;
    ui_POS_S1_Panel_BTN_Next = NULL;
    ui_POS_S1_Image_IMG_Arrow = NULL;

}
