/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#include "../ui.h"

lv_obj_t *ui_Screen_POS_S3 = NULL;
lv_obj_t *ui_POS_S3_Label_Label_Select_Payment = NULL;
lv_obj_t *ui_POS_S3_Label_Label_Ony_BTC = NULL;
lv_obj_t *ui_POS_S3_Panel_Panel_List_BTC = NULL;
lv_obj_t *ui_POS_S3_Panel_Panel_List_Bg = NULL;
lv_obj_t *ui_POS_S3_Panel_Panel_BTC_table = NULL;
lv_obj_t *ui_POS_S3_Label_Label_Bitcoin = NULL;
lv_obj_t *ui_POS_S3_Label_Label_BTC = NULL;
lv_obj_t *ui_POS_S3_Image_IMG_BTC = NULL;
lv_obj_t *ui_POS_S3_Image_IMG_Arrow_List_1 = NULL;
lv_obj_t *ui_POS_S3_Panel_Panel_List_Card = NULL;
lv_obj_t *ui_POS_S3_Panel_Panel_List_Bg3 = NULL;
lv_obj_t *ui_POS_S3_Label_Label_Card = NULL;
lv_obj_t *ui_POS_S3_Image_IMG_XRP1 = NULL;
lv_obj_t *ui_POS_S3_Image_IMG_Arrow_List_4 = NULL;
lv_obj_t *ui_POS_S3_Panel_Panel_Caed_table = NULL;
lv_obj_t *ui_POS_S3_Label_Label_Card1 = NULL;
// event functions

// build functions

void ui_Screen_POS_S3_screen_init(void)
{
    ui_Screen_POS_S3 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen_POS_S3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen_POS_S3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen_POS_S3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Label_Label_Select_Payment = lv_label_create(ui_Screen_POS_S3);
    lv_obj_set_width(ui_POS_S3_Label_Label_Select_Payment, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S3_Label_Label_Select_Payment, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S3_Label_Label_Select_Payment, 0);
    lv_obj_set_y(ui_POS_S3_Label_Label_Select_Payment, 15);
    lv_obj_set_align(ui_POS_S3_Label_Label_Select_Payment, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_POS_S3_Label_Label_Select_Payment, "Select Payment\nMetod");
    lv_obj_set_style_text_color(ui_POS_S3_Label_Label_Select_Payment, lv_color_hex(0x0B1019),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S3_Label_Label_Select_Payment, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S3_Label_Label_Select_Payment, LV_TEXT_ALIGN_CENTER,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S3_Label_Label_Select_Payment, &lv_font_montserrat_18,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Label_Label_Ony_BTC = lv_label_create(ui_Screen_POS_S3);
    lv_obj_set_width(ui_POS_S3_Label_Label_Ony_BTC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S3_Label_Label_Ony_BTC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S3_Label_Label_Ony_BTC, 0);
    lv_obj_set_y(ui_POS_S3_Label_Label_Ony_BTC, 70);
    lv_obj_set_align(ui_POS_S3_Label_Label_Ony_BTC, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_POS_S3_Label_Label_Ony_BTC, "Only BTC payment is possible");
    lv_obj_set_style_text_color(ui_POS_S3_Label_Label_Ony_BTC, lv_color_hex(0x7F848F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S3_Label_Label_Ony_BTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S3_Label_Label_Ony_BTC, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S3_Label_Label_Ony_BTC, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Panel_Panel_List_BTC = lv_obj_create(ui_Screen_POS_S3);
    lv_obj_set_height(ui_POS_S3_Panel_Panel_List_BTC, 84);
    lv_obj_set_width(ui_POS_S3_Panel_Panel_List_BTC, lv_pct(100));
    lv_obj_set_x(ui_POS_S3_Panel_Panel_List_BTC, 0);
    lv_obj_set_y(ui_POS_S3_Panel_Panel_List_BTC, 91);
    lv_obj_set_align(ui_POS_S3_Panel_Panel_List_BTC, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_POS_S3_Panel_Panel_List_BTC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_POS_S3_Panel_Panel_List_BTC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S3_Panel_Panel_List_BTC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S3_Panel_Panel_List_BTC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S3_Panel_Panel_List_BTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S3_Panel_Panel_List_BTC, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Panel_Panel_List_Bg = lv_obj_create(ui_POS_S3_Panel_Panel_List_BTC);
    lv_obj_set_height(ui_POS_S3_Panel_Panel_List_Bg, 70);
    lv_obj_set_width(ui_POS_S3_Panel_Panel_List_Bg, lv_pct(100));
    lv_obj_set_align(ui_POS_S3_Panel_Panel_List_Bg, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_POS_S3_Panel_Panel_List_Bg, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S3_Panel_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S3_Panel_Panel_List_Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S3_Panel_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_POS_S3_Panel_Panel_List_Bg, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POS_S3_Panel_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S3_Panel_Panel_List_Bg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_POS_S3_Panel_Panel_List_Bg, lv_color_hex(0xFFCEB0), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_POS_S3_Panel_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(ui_POS_S3_Panel_Panel_List_Bg, lv_color_hex(0xFF7A28), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_opa(ui_POS_S3_Panel_Panel_List_Bg, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_POS_S3_Panel_Panel_BTC_table = lv_obj_create(ui_POS_S3_Panel_Panel_List_BTC);
    lv_obj_set_height(ui_POS_S3_Panel_Panel_BTC_table, 20);
    lv_obj_set_width(ui_POS_S3_Panel_Panel_BTC_table, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_POS_S3_Panel_Panel_BTC_table, 18);
    lv_obj_set_y(ui_POS_S3_Panel_Panel_BTC_table, -10);
    lv_obj_remove_flag(ui_POS_S3_Panel_Panel_BTC_table, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_POS_S3_Panel_Panel_BTC_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S3_Panel_Panel_BTC_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S3_Panel_Panel_BTC_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_POS_S3_Panel_Panel_BTC_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_POS_S3_Panel_Panel_BTC_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_POS_S3_Panel_Panel_BTC_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_POS_S3_Panel_Panel_BTC_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Label_Label_Bitcoin = lv_label_create(ui_POS_S3_Panel_Panel_BTC_table);
    lv_obj_set_width(ui_POS_S3_Label_Label_Bitcoin, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S3_Label_Label_Bitcoin, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_POS_S3_Label_Label_Bitcoin, LV_ALIGN_CENTER);
    lv_label_set_text(ui_POS_S3_Label_Label_Bitcoin, "Bitcoin");
    lv_obj_set_style_text_color(ui_POS_S3_Label_Label_Bitcoin, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S3_Label_Label_Bitcoin, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S3_Label_Label_Bitcoin, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S3_Label_Label_Bitcoin, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Label_Label_BTC = lv_label_create(ui_POS_S3_Panel_Panel_List_BTC);
    lv_obj_set_width(ui_POS_S3_Label_Label_BTC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S3_Label_Label_BTC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S3_Label_Label_BTC, 68);
    lv_obj_set_y(ui_POS_S3_Label_Label_BTC, 6);
    lv_obj_set_align(ui_POS_S3_Label_Label_BTC, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_POS_S3_Label_Label_BTC, "BTC");
    lv_obj_set_style_text_color(ui_POS_S3_Label_Label_BTC, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S3_Label_Label_BTC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S3_Label_Label_BTC, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S3_Label_Label_BTC, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Image_IMG_BTC = lv_image_create(ui_POS_S3_Panel_Panel_List_BTC);
    lv_image_set_src(ui_POS_S3_Image_IMG_BTC, &ui_img_img_btc_png);
    lv_obj_set_width(ui_POS_S3_Image_IMG_BTC, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_POS_S3_Image_IMG_BTC, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_POS_S3_Image_IMG_BTC, 20);
    lv_obj_set_y(ui_POS_S3_Image_IMG_BTC, 6);
    lv_obj_set_align(ui_POS_S3_Image_IMG_BTC, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_POS_S3_Image_IMG_BTC, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S3_Image_IMG_BTC, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_POS_S3_Image_IMG_Arrow_List_1 = lv_image_create(ui_POS_S3_Panel_Panel_List_BTC);
    lv_image_set_src(ui_POS_S3_Image_IMG_Arrow_List_1, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_POS_S3_Image_IMG_Arrow_List_1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_POS_S3_Image_IMG_Arrow_List_1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_POS_S3_Image_IMG_Arrow_List_1, -10);
    lv_obj_set_y(ui_POS_S3_Image_IMG_Arrow_List_1, 6);
    lv_obj_set_align(ui_POS_S3_Image_IMG_Arrow_List_1, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_POS_S3_Image_IMG_Arrow_List_1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S3_Image_IMG_Arrow_List_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_POS_S3_Image_IMG_Arrow_List_1, lv_color_hex(0x1D222A),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_POS_S3_Image_IMG_Arrow_List_1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Panel_Panel_List_Card = lv_obj_create(ui_Screen_POS_S3);
    lv_obj_set_height(ui_POS_S3_Panel_Panel_List_Card, 84);
    lv_obj_set_width(ui_POS_S3_Panel_Panel_List_Card, lv_pct(100));
    lv_obj_set_x(ui_POS_S3_Panel_Panel_List_Card, 0);
    lv_obj_set_y(ui_POS_S3_Panel_Panel_List_Card, 190);
    lv_obj_set_align(ui_POS_S3_Panel_Panel_List_Card, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_POS_S3_Panel_Panel_List_Card, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_POS_S3_Panel_Panel_List_Card, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S3_Panel_Panel_List_Card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S3_Panel_Panel_List_Card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S3_Panel_Panel_List_Card, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S3_Panel_Panel_List_Card, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Panel_Panel_List_Bg3 = lv_obj_create(ui_POS_S3_Panel_Panel_List_Card);
    lv_obj_set_height(ui_POS_S3_Panel_Panel_List_Bg3, 70);
    lv_obj_set_width(ui_POS_S3_Panel_Panel_List_Bg3, lv_pct(100));
    lv_obj_set_x(ui_POS_S3_Panel_Panel_List_Bg3, 0);
    lv_obj_set_y(ui_POS_S3_Panel_Panel_List_Bg3, -12);
    lv_obj_set_align(ui_POS_S3_Panel_Panel_List_Bg3, LV_ALIGN_TOP_MID);
    lv_obj_set_style_bg_color(ui_POS_S3_Panel_Panel_List_Bg3, lv_color_hex(0xF1F1F2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_POS_S3_Panel_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_POS_S3_Panel_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S3_Panel_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_POS_S3_Panel_Panel_List_Bg3, lv_color_hex(0x9B9DA4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_POS_S3_Panel_Panel_List_Bg3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S3_Panel_Panel_List_Bg3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_POS_S3_Panel_Panel_List_Bg3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_POS_S3_Panel_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_POS_S3_Panel_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_POS_S3_Panel_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_POS_S3_Panel_Panel_List_Bg3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Label_Label_Card = lv_label_create(ui_POS_S3_Panel_Panel_List_Bg3);
    lv_obj_set_width(ui_POS_S3_Label_Label_Card, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S3_Label_Label_Card, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_POS_S3_Label_Label_Card, 68);
    lv_obj_set_y(ui_POS_S3_Label_Label_Card, 0);
    lv_obj_set_align(ui_POS_S3_Label_Label_Card, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_POS_S3_Label_Label_Card, "Card");
    lv_obj_set_style_text_color(ui_POS_S3_Label_Label_Card, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S3_Label_Label_Card, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S3_Label_Label_Card, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S3_Label_Label_Card, &ui_font_Big_Number, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Image_IMG_XRP1 = lv_image_create(ui_POS_S3_Panel_Panel_List_Bg3);
    lv_image_set_src(ui_POS_S3_Image_IMG_XRP1, &ui_img_img_card_png);
    lv_obj_set_width(ui_POS_S3_Image_IMG_XRP1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_POS_S3_Image_IMG_XRP1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_POS_S3_Image_IMG_XRP1, 15);
    lv_obj_set_y(ui_POS_S3_Image_IMG_XRP1, 0);
    lv_obj_set_align(ui_POS_S3_Image_IMG_XRP1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_POS_S3_Image_IMG_XRP1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S3_Image_IMG_XRP1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_POS_S3_Image_IMG_Arrow_List_4 = lv_image_create(ui_POS_S3_Panel_Panel_List_Bg3);
    lv_image_set_src(ui_POS_S3_Image_IMG_Arrow_List_4, &ui_img_img_arrow_right_png);
    lv_obj_set_width(ui_POS_S3_Image_IMG_Arrow_List_4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_POS_S3_Image_IMG_Arrow_List_4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_POS_S3_Image_IMG_Arrow_List_4, -10);
    lv_obj_set_y(ui_POS_S3_Image_IMG_Arrow_List_4, 0);
    lv_obj_set_align(ui_POS_S3_Image_IMG_Arrow_List_4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_POS_S3_Image_IMG_Arrow_List_4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_POS_S3_Image_IMG_Arrow_List_4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_POS_S3_Image_IMG_Arrow_List_4, lv_color_hex(0x1D222A),
                                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_POS_S3_Image_IMG_Arrow_List_4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Panel_Panel_Caed_table = lv_obj_create(ui_POS_S3_Panel_Panel_List_Card);
    lv_obj_set_height(ui_POS_S3_Panel_Panel_Caed_table, 20);
    lv_obj_set_width(ui_POS_S3_Panel_Panel_Caed_table, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_x(ui_POS_S3_Panel_Panel_Caed_table, 18);
    lv_obj_set_y(ui_POS_S3_Panel_Panel_Caed_table, -10);
    lv_obj_remove_flag(ui_POS_S3_Panel_Panel_Caed_table, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_main_stop(ui_POS_S3_Panel_Panel_Caed_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_POS_S3_Panel_Panel_Caed_table, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_POS_S3_Panel_Panel_Caed_table, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_POS_S3_Panel_Panel_Caed_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_POS_S3_Panel_Panel_Caed_table, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_POS_S3_Panel_Panel_Caed_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_POS_S3_Panel_Panel_Caed_table, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_POS_S3_Label_Label_Card1 = lv_label_create(ui_POS_S3_Panel_Panel_Caed_table);
    lv_obj_set_width(ui_POS_S3_Label_Label_Card1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_POS_S3_Label_Label_Card1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_POS_S3_Label_Label_Card1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_POS_S3_Label_Label_Card1, "Card");
    lv_obj_set_style_text_color(ui_POS_S3_Label_Label_Card1, lv_color_hex(0x1D222A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_POS_S3_Label_Label_Card1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_POS_S3_Label_Label_Card1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_POS_S3_Label_Label_Card1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_POS_S3_Label_Label_Card1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen_POS_S3_screen_destroy(void)
{
    if (ui_Screen_POS_S3) {
        lv_obj_del(ui_Screen_POS_S3);
    }

    // NULL screen variables
    ui_Screen_POS_S3 = NULL;
    ui_POS_S3_Label_Label_Select_Payment = NULL;
    ui_POS_S3_Label_Label_Ony_BTC = NULL;
    ui_POS_S3_Panel_Panel_List_BTC = NULL;
    ui_POS_S3_Panel_Panel_List_Bg = NULL;
    ui_POS_S3_Panel_Panel_BTC_table = NULL;
    ui_POS_S3_Label_Label_Bitcoin = NULL;
    ui_POS_S3_Label_Label_BTC = NULL;
    ui_POS_S3_Image_IMG_BTC = NULL;
    ui_POS_S3_Image_IMG_Arrow_List_1 = NULL;
    ui_POS_S3_Panel_Panel_List_Card = NULL;
    ui_POS_S3_Panel_Panel_List_Bg3 = NULL;
    ui_POS_S3_Label_Label_Card = NULL;
    ui_POS_S3_Image_IMG_XRP1 = NULL;
    ui_POS_S3_Image_IMG_Arrow_List_4 = NULL;
    ui_POS_S3_Panel_Panel_Caed_table = NULL;
    ui_POS_S3_Label_Label_Card1 = NULL;

}
