/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#ifndef UI_SCREEN_POS_S1_H
#define UI_SCREEN_POS_S1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_POS_S1
extern void ui_Screen_POS_S1_screen_init(void);
extern void ui_Screen_POS_S1_screen_destroy(void);
extern lv_obj_t *ui_Screen_POS_S1;
extern lv_obj_t *ui_POS_S1_Panel_Circle_1;
extern lv_obj_t *ui_POS_S1_Panel_Circle_2;
extern lv_obj_t *ui_POS_S1_Image_IMG_POS;
extern lv_obj_t *ui_POS_S1_Label_Label_card_and_crypto;
extern lv_obj_t *ui_POS_S1_Label_Label_Lets_get;
extern lv_obj_t *ui_POS_S1_Panel_BTN_Next;
extern lv_obj_t *ui_POS_S1_Image_IMG_Arrow;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
