/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#ifndef UI_SCREEN_POS_S2_H
#define UI_SCREEN_POS_S2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_POS_S2
extern void ui_Screen_POS_S2_screen_init(void);
extern void ui_Screen_POS_S2_screen_destroy(void);
extern lv_obj_t *ui_Screen_POS_S2;
extern lv_obj_t *ui_POS_S2_Label_Label_Enter_Amount;
extern lv_obj_t *ui_POS_S2_Label_Label_Want_to_pay;
extern lv_obj_t *ui_POS_S2_Panel_Panel_Amount;
extern lv_obj_t *ui_POS_S2_Textarea_TextArea1;
extern lv_obj_t *ui_POS_S2_Panel_Panel_Amount_table;
extern lv_obj_t *ui_POS_S2_Label_Label_Amount_1;
extern lv_obj_t *ui_POS_S2_Label_Label_Amount_Pirce;
extern lv_obj_t *ui_POS_S2_Panel_BTN_Continue;
extern lv_obj_t *ui_POS_S2_Label_Label_Continue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
