/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#ifndef UI_SCREEN_POS_S5_H
#define UI_SCREEN_POS_S5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_POS_S5
extern void ui_Screen_POS_S5_screen_init(void);
extern void ui_Screen_POS_S5_screen_destroy(void);
extern lv_obj_t *ui_Screen_POS_S5;
extern lv_obj_t *ui_POS_S5_Image_IMG_Ok_1;
extern lv_obj_t *ui_POS_S5_Image_IMG_Ok_2;
extern lv_obj_t *ui_POS_S5_Label_Label_Succesful;
extern lv_obj_t *ui_POS_S5_Label_Label_press_contimue;
extern lv_obj_t *ui_POS_S5_Panel_BTN_Next_2;
extern lv_obj_t *ui_POS_S5_Image_IMG_Arrow1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
