/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#ifndef UI_SCREEN_POS_S4_H
#define UI_SCREEN_POS_S4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen_POS_S4
extern void ui_Screen_POS_S4_screen_init(void);
extern void ui_Screen_POS_S4_screen_destroy(void);
extern lv_obj_t *ui_Screen_POS_S4;
extern lv_obj_t *ui_POS_S4_Label_Label_Amount_Pirce2;
extern lv_obj_t *ui_POS_S4_Label_Label_Amount_Title;
extern lv_obj_t *ui_POS_S4_Label_Label_QR_ready;
extern lv_obj_t *ui_POS_S4_Image_IMG_QR_Code;
extern lv_obj_t *ui_POS_S4_Label_Label_BTC_Address;
extern lv_obj_t *ui_POS_S4_Label_Label_Cancel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
