// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: Smart_Gadget

#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

#if ESP_BROOKESIA_SQUARELINE_USE_INTERNAL_UI_COMP
#define LV_EVENT_GET_COMP_CHILD ui_comp_get_event_code()

void get_component_child_event_cb(lv_event_t * e);
void del_component_child_event_cb(lv_event_t * e);

lv_obj_t * ui_comp_get_child(lv_obj_t * comp, uint32_t child_idx);

lv_event_code_t ui_comp_get_event_code(void);

void esp_brookesia_squareline_ui_comp_init(void);
#endif /* ESP_BROOKESIA_SQUARELINE_USE_INTERNAL_UI_COMP */

#ifdef __cplusplus
} /*extern "C"*/
#endif
