#pragma once

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Fonts */
// Masion-Neue-Book
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_8);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_10);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_12);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_14);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_16);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_18);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_20);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_22);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_24);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_26);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_28);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_30);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_32);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_34);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_36);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_38);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_40);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_42);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_44);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_46);
LV_FONT_DECLARE(esp_brookesia_font_maison_neue_book_48);

#ifdef __cplusplus
}
#endif
