/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

/**
 * @brief Default log tag used by service-manager components.
 */
#define BROOKESIA_SERVICE_MANAGER_LOG_TAG "SvcMgr"

#if !defined(BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_SERVICE_MANAGER_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_EVENT_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif

#   if !defined(BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_FUNCTION_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif

#   if !defined(BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_SERVICE_MANAGER_SERVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_MANAGER_DEFAULT_CALL_FUNCTION_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_DEFAULT_CALL_FUNCTION_TIMEOUT_MS)
#       define BROOKESIA_SERVICE_MANAGER_DEFAULT_CALL_FUNCTION_TIMEOUT_MS  CONFIG_BROOKESIA_SERVICE_MANAGER_DEFAULT_CALL_FUNCTION_TIMEOUT_MS
#   else
#       define BROOKESIA_SERVICE_MANAGER_DEFAULT_CALL_FUNCTION_TIMEOUT_MS  (500)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Worker /////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_NAME)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_NAME)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_NAME  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_NAME
#   else
#       define BROOKESIA_SERVICE_MANAGER_WORKER_NAME  ("SvcMgrMain")
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_PRIORITY)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_PRIORITY)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_PRIORITY  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_PRIORITY
#   else
#       define BROOKESIA_SERVICE_MANAGER_WORKER_PRIORITY  (10)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_STACK_SIZE)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_STACK_SIZE
#   else
#       define BROOKESIA_SERVICE_MANAGER_WORKER_STACK_SIZE  (10 * 1024)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_STACK_IN_EXT)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_STACK_IN_EXT)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_STACK_IN_EXT  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_STACK_IN_EXT
#   else
#       define BROOKESIA_SERVICE_MANAGER_WORKER_STACK_IN_EXT  (0)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_POLL_INTERVAL_MS)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_POLL_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_MANAGER_WORKER_POLL_INTERVAL_MS  (5)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_NUM)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_NUM)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_NUM  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_NUM
#   else
#       define BROOKESIA_SERVICE_MANAGER_WORKER_NUM  (3)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_0_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_0_CORE_ID)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_0_CORE_ID  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_0_CORE_ID
#   elif defined(ESP_PLATFORM)
#       define BROOKESIA_SERVICE_MANAGER_WORKER_0_CORE_ID  (0)
#   else
#       define BROOKESIA_SERVICE_MANAGER_WORKER_0_CORE_ID  (-1)
#   endif
#endif
#if BROOKESIA_SERVICE_MANAGER_WORKER_NUM >= 2
#   if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_1_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_1_CORE_ID)
#          define BROOKESIA_SERVICE_MANAGER_WORKER_1_CORE_ID  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_1_CORE_ID
#      elif defined(ESP_PLATFORM)
#          define BROOKESIA_SERVICE_MANAGER_WORKER_1_CORE_ID  (1)
#      else
#          define BROOKESIA_SERVICE_MANAGER_WORKER_1_CORE_ID  (-1)
#      endif
#   endif
#endif
#if BROOKESIA_SERVICE_MANAGER_WORKER_NUM >= 3
#   if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_2_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_2_CORE_ID)
#          define BROOKESIA_SERVICE_MANAGER_WORKER_2_CORE_ID  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_2_CORE_ID
#      elif defined(ESP_PLATFORM)
#          define BROOKESIA_SERVICE_MANAGER_WORKER_2_CORE_ID  (2)
#      else
#          define BROOKESIA_SERVICE_MANAGER_WORKER_2_CORE_ID  (-1)
#      endif
#   endif
#endif
#if BROOKESIA_SERVICE_MANAGER_WORKER_NUM >= 4
#   if !defined(BROOKESIA_SERVICE_MANAGER_WORKER_3_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_3_CORE_ID)
#          define BROOKESIA_SERVICE_MANAGER_WORKER_3_CORE_ID  CONFIG_BROOKESIA_SERVICE_MANAGER_WORKER_3_CORE_ID
#      elif defined(ESP_PLATFORM)
#          define BROOKESIA_SERVICE_MANAGER_WORKER_3_CORE_ID  (3)
#      else
#          define BROOKESIA_SERVICE_MANAGER_WORKER_3_CORE_ID  (-1)
#      endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////// Secondary Scheduler //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_ENABLE)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_ENABLE)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_ENABLE \
        CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_ENABLE
#   elif BROOKESIA_SERVICE_MANAGER_WORKER_STACK_IN_EXT
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_ENABLE  (1)
#   else
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_ENABLE  (0)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NAME)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NAME)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NAME \
        CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NAME
#   else
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NAME  ("SvcMgrSec")
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_PRIORITY)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_PRIORITY)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_PRIORITY \
        CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_PRIORITY
#   else
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_PRIORITY  (5)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_STACK_SIZE)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_STACK_SIZE \
        CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_STACK_SIZE
#   else
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_STACK_SIZE  (6 * 1024)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_POLL_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_POLL_INTERVAL_MS)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_POLL_INTERVAL_MS \
        CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_POLL_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_POLL_INTERVAL_MS  (5)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM \
        CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM
#   else
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM  (2)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_0_CORE_ID)
#   if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_0_CORE_ID)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_0_CORE_ID \
        CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_0_CORE_ID
#   elif defined(ESP_PLATFORM)
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_0_CORE_ID  (0)
#   else
#       define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_0_CORE_ID  (-1)
#   endif
#endif
#if BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM >= 2
#   if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_1_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_1_CORE_ID)
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_1_CORE_ID \
           CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_1_CORE_ID
#      elif defined(ESP_PLATFORM)
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_1_CORE_ID  (1)
#      else
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_1_CORE_ID  (-1)
#      endif
#   endif
#endif
#if BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM >= 3
#   if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_2_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_2_CORE_ID)
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_2_CORE_ID \
           CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_2_CORE_ID
#      elif defined(ESP_PLATFORM)
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_2_CORE_ID  (2)
#      else
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_2_CORE_ID  (-1)
#      endif
#   endif
#endif
#if BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_NUM >= 4
#   if !defined(BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_3_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_3_CORE_ID)
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_3_CORE_ID \
           CONFIG_BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_3_CORE_ID
#      elif defined(ESP_PLATFORM)
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_3_CORE_ID  (3)
#      else
#          define BROOKESIA_SERVICE_MANAGER_SECONDARY_SCHEDULER_WORKER_3_CORE_ID  (-1)
#      endif
#   endif
#endif
