/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: Smart_Gadget

#pragma once

#include "lvgl.h"
#include "esp_brookesia_gui_internal.h"

#if ESP_BROOKESIA_SQUARELINE_ENABLE_UI_COMP

#ifdef __cplusplus
extern "C" {
#endif

#define LV_EVENT_GET_COMP_CHILD ui_comp_get_event_code()

void get_component_child_event_cb(lv_event_t *e);
void del_component_child_event_cb(lv_event_t *e);

lv_obj_t *ui_comp_get_child(lv_obj_t *comp, uint32_t child_idx);

lv_event_code_t ui_comp_get_event_code(void);

void esp_brookesia_squareline_ui_comp_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif /* ESP_BROOKESIA_SQUARELINE_ENABLE_UI_COMP */
