idf_component_register(
    SRCS ${COMPONENT_SRCS_C} ${COMPONENT_SRCS_CPP}
    INCLUDE_DIRS ${COMPONENT_INCLUDE_DIRS}
    PRIV_INCLUDE_DIRS ${COMPONENT_PRIVATE_INCLUDE_DIRS}
    REQUIRES ${COMPONENT_REQUIRES}
    PRIV_REQUIRES ${COMPONENT_PRIV_REQUIRES}
)

if(CONFIG_BROOKESIA_SERVICE_AUDIO_ENABLE_AUTO_REGISTER)
    set(BROOKESIA_SERVICE_AUDIO_PLAYBACK_PLUGIN_SYMBOL service_audio_playback_symbol)
    set(BROOKESIA_SERVICE_AUDIO_ENCODER_PLUGIN_SYMBOL_0 service_audio_encoder_symbol_0)
    set(BROOKESIA_SERVICE_AUDIO_DECODER_PLUGIN_SYMBOL_0 service_audio_decoder_symbol_0)
    target_compile_definitions(${COMPONENT_LIB} PRIVATE
        BROOKESIA_SERVICE_AUDIO_PLAYBACK_PLUGIN_SYMBOL=${BROOKESIA_SERVICE_AUDIO_PLAYBACK_PLUGIN_SYMBOL}
        BROOKESIA_SERVICE_AUDIO_ENCODER_PLUGIN_SYMBOL_0=${BROOKESIA_SERVICE_AUDIO_ENCODER_PLUGIN_SYMBOL_0}
        BROOKESIA_SERVICE_AUDIO_DECODER_PLUGIN_SYMBOL_0=${BROOKESIA_SERVICE_AUDIO_DECODER_PLUGIN_SYMBOL_0}
    )
    target_link_libraries(${COMPONENT_LIB} PRIVATE
        "-u ${BROOKESIA_SERVICE_AUDIO_PLAYBACK_PLUGIN_SYMBOL}"
        "-u ${BROOKESIA_SERVICE_AUDIO_ENCODER_PLUGIN_SYMBOL_0}"
        "-u ${BROOKESIA_SERVICE_AUDIO_DECODER_PLUGIN_SYMBOL_0}"
    )
endif()

include(package_manager)
cu_pkg_define_version(${COMPONENT_DIR})
