/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "sdkconfig.h"

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Debug Log //////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#define BROOKESIA_HAL_ADAPTOR_LOG_TAG "HalAdpt"

#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_HAL_ADAPTOR_SYSTEM_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_SYSTEM_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_NETWORK_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_SNTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_PROCESSOR_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_PROCESSOR_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_PROCESSOR_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_PROCESSOR_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_PROCESSOR_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_VIDEO_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_VIDEO_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Wi-Fi Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_DEVICE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_DEVICE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_DEVICE_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_DEVICE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_DEVICE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_BACKEND_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_BACKEND_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_BACKEND_ENABLE_DEBUG_LOG  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_BACKEND_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_BACKEND_ENABLE_DEBUG_LOG  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_WIFI_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_WIFI_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_WIFI_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_WIFI_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_WIFI_DEVICE  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN  CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN  (1)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX  CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX  (11)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT  (1)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_INTERVAL_MS)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_INTERVAL_MS  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_INTERVAL_MS
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_INTERVAL_MS  (1000)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_TIMEOUT_MS)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_TIMEOUT_MS  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_TIMEOUT_MS
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_TIMEOUT_MS  (300000)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_EVENT_DELAY_MS)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_EVENT_DELAY_MS)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_EVENT_DELAY_MS  CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_EVENT_DELAY_MS
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_EVENT_DELAY_MS  (2000)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_START_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_START_INTERVAL_MS)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_START_INTERVAL_MS  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_START_INTERVAL_MS
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_START_INTERVAL_MS  (1000)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_TIMEOUT_MS)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_TIMEOUT_MS  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_TIMEOUT_MS
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_TIMEOUT_MS  (20000)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS  (3000)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_STACK_SIZE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_STACK_SIZE)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_STACK_SIZE  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_STACK_SIZE
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_STACK_SIZE  (4096)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_PRIORITY)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_PRIORITY)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_PRIORITY  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_PRIORITY
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_PRIORITY  (3)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_CORE_ID)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_CORE_ID)
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_CORE_ID  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_CORE_ID
#   else
#       define BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_CORE_ID  (-1)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////// System Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_SYSTEM_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_SYSTEM_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_SYSTEM_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_SYSTEM_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_SYSTEM_DEVICE  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_ENABLE_SYSTEM_DEVICE
#   if !defined(BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_BOARD_INFO_IMPL)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_BOARD_INFO_IMPL)
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_BOARD_INFO_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_BOARD_INFO_IMPL
#       else
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_BOARD_INFO_IMPL  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_OTA_UPDATER_IMPL)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_OTA_UPDATER_IMPL)
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_OTA_UPDATER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_OTA_UPDATER_IMPL
#       else
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_ENABLE_OTA_UPDATER_IMPL  (0)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////// Network Device //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_NETWORK_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_NETWORK_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_NETWORK_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_NETWORK_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_NETWORK_DEVICE  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_ENABLE_NETWORK_DEVICE
#   if !defined(BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_SNTP_CLIENT_IMPL)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_SNTP_CLIENT_IMPL)
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_SNTP_CLIENT_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_SNTP_CLIENT_IMPL
#       else
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_SNTP_CLIENT_IMPL  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_HTTP_CLIENT_IMPL)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_HTTP_CLIENT_IMPL)
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_HTTP_CLIENT_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_HTTP_CLIENT_IMPL
#       else
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_HTTP_CLIENT_IMPL  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY)
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY  CONFIG_BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY
#       else
#           define BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY  (1)
#       endif
#   endif
#endif
#if !BROOKESIA_HAL_ADAPTOR_ENABLE_NETWORK_DEVICE
#   define BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_SNTP_CLIENT_IMPL  (0)
#   define BROOKESIA_HAL_ADAPTOR_NETWORK_ENABLE_HTTP_CLIENT_IMPL  (0)
#   define BROOKESIA_HAL_ADAPTOR_NETWORK_HTTP_CLIENT_REQUIRE_TLS_VERIFY  (1)
#endif
#if BROOKESIA_HAL_ADAPTOR_ENABLE_SYSTEM_DEVICE
#   if !defined(BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_THREAD_STACK_SIZE)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_THREAD_STACK_SIZE)
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_THREAD_STACK_SIZE  CONFIG_BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_THREAD_STACK_SIZE
#       else
#           define BROOKESIA_HAL_ADAPTOR_SYSTEM_OTA_UPDATER_THREAD_STACK_SIZE  (10240)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Audio Codec Device ///////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE  (0)
#   endif
#endif

/* Codec player interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL  (0)
#   endif
#endif

/* Codec recorder interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_PROCESSOR_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_PROCESSOR_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_PROCESSOR_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_PROCESSOR_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_PROCESSOR_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS  (16)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS  (1)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE  (16000)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT  "M"
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN  "36.0"
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS  "{\"0\":0.0,\"1\":0.0}"
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////// Video Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_VIDEO_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_VIDEO_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_VIDEO_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_VIDEO_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_VIDEO_DEVICE  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_KEEP_DEVICE_INITIALIZED_ON_RELEASE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_KEEP_DEVICE_INITIALIZED_ON_RELEASE)
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_KEEP_DEVICE_INITIALIZED_ON_RELEASE  \
            CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_KEEP_DEVICE_INITIALIZED_ON_RELEASE
#   else
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_KEEP_DEVICE_INITIALIZED_ON_RELEASE  (1)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_CAMERA_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_CAMERA_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_CAMERA_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_CAMERA_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_CAMERA_IMPL  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_ENCODER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_ENCODER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_ENCODER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_ENCODER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_ENCODER_IMPL  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_DEVICE_PATH_PREFIX)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_DEVICE_PATH_PREFIX)
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_DEVICE_PATH_PREFIX  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_DEVICE_PATH_PREFIX
#   else
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_DEVICE_PATH_PREFIX  "/dev/video"
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_NUM)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_NUM)
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_NUM  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_NUM
#   else
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_DEFAULT_NUM  (1)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_DECODER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_DECODER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_DECODER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_DECODER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_DECODER_IMPL  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_DEFAULT_NUM)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_DEFAULT_NUM)
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_DEFAULT_NUM  CONFIG_BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_DEFAULT_NUM
#   else
#       define BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_DEFAULT_NUM  (1)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_PROCESSOR_IMPL_ENABLE_DEBUG_LOG)
#   define BROOKESIA_HAL_ADAPTOR_AUDIO_PROCESSOR_IMPL_ENABLE_DEBUG_LOG  (0)
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_DEVICE_ENABLE_DEBUG_LOG)
#   define BROOKESIA_HAL_ADAPTOR_VIDEO_DEVICE_ENABLE_DEBUG_LOG  (0)
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_CAMERA_IMPL)
#   define BROOKESIA_HAL_ADAPTOR_VIDEO_ENABLE_CAMERA_IMPL  (0)
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_IMPL_ENABLE_DEBUG_LOG)
#   define BROOKESIA_HAL_ADAPTOR_VIDEO_ENCODER_IMPL_ENABLE_DEBUG_LOG  (0)
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_IMPL_ENABLE_DEBUG_LOG)
#   define BROOKESIA_HAL_ADAPTOR_VIDEO_DECODER_IMPL_ENABLE_DEBUG_LOG  (0)
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Display LCD Device ///////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE  (0)
#   endif
#endif
/* LCD panel interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES  (1)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES  (1)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_INIT_THREAD_CORE_ID)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_INIT_THREAD_CORE_ID)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_INIT_THREAD_CORE_ID  \
                CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_INIT_THREAD_CORE_ID
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_INIT_THREAD_CORE_ID  (-1)
#       endif
#   endif
#endif
/* LCD touch interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL  (0)
#   endif
#endif
/* LEDC backlight interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL  (0)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Storage Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE  (0)
#   endif
#endif
/* General FS interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_FILE_SYSTEM_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_FILE_SYSTEM_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_FILE_SYSTEM_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_FILE_SYSTEM_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_FILE_SYSTEM_IMPL  (0)
#   endif
#endif
#if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_KEY_VALUE_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_KEY_VALUE_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_KEY_VALUE_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_KEY_VALUE_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_KEY_VALUE_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_FILE_SYSTEM_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SPIFFS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SPIFFS)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SPIFFS  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SPIFFS
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SPIFFS  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_LITTLEFS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_LITTLEFS)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_LITTLEFS  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_LITTLEFS
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_LITTLEFS  (0)
#       endif
#   endif
#   if BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_LITTLEFS
#       if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_BASE_PATH)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_BASE_PATH)
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_BASE_PATH  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_BASE_PATH
#           else
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_BASE_PATH  "/littlefs"
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_PARTITION_LABEL)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_PARTITION_LABEL)
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_PARTITION_LABEL  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_PARTITION_LABEL
#           else
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_PARTITION_LABEL  "littlefs_data"
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_FORMAT_IF_MOUNT_FAILED)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_FORMAT_IF_MOUNT_FAILED)
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_FORMAT_IF_MOUNT_FAILED  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_FORMAT_IF_MOUNT_FAILED
#           else
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_LITTLEFS_FORMAT_IF_MOUNT_FAILED  (0)
#           endif
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_FATFS_FLASH)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_FATFS_FLASH)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_FATFS_FLASH  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_FATFS_FLASH
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_FATFS_FLASH  (0)
#       endif
#   endif
#   if BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_FATFS_FLASH
#       if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_BASE_PATH)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_BASE_PATH)
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_BASE_PATH  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_BASE_PATH
#           else
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_BASE_PATH  "/fatfs"
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_PARTITION_LABEL)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_PARTITION_LABEL)
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_PARTITION_LABEL  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_PARTITION_LABEL
#           else
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_PARTITION_LABEL  "fatfs_data"
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_FORMAT_IF_MOUNT_FAILED)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_FORMAT_IF_MOUNT_FAILED)
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_FORMAT_IF_MOUNT_FAILED  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_FORMAT_IF_MOUNT_FAILED
#           else
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_FORMAT_IF_MOUNT_FAILED  (0)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_MAX_FILES)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_MAX_FILES)
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_MAX_FILES  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_MAX_FILES
#           else
#               define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_MAX_FILES  (4)
#           endif
#       endif
#   else
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_BASE_PATH  "/fatfs"
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_PARTITION_LABEL  "fatfs_data"
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_FORMAT_IF_MOUNT_FAILED  (0)
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_FATFS_FLASH_MAX_FILES  (4)
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SDCARD)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SDCARD)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SDCARD  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SDCARD
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_FILE_SYSTEM_ENABLE_SDCARD  (0)
#       endif
#   endif
#endif

#if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_KEY_VALUE_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_KEY_VALUE_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_KEY_VALUE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_KEY_VALUE_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_KEY_VALUE_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Power Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE
#   if !defined(BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY)
#           define BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY
#       else
#           define BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY  (0)
#       endif
#   endif
#   if BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101  (0)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC  (0)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV  (3500)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV  (3300)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL  (2)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV  (1)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV  (1000)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT  (8)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX  (4095)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV  (3300)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV  (3300)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV  (4200)
#           endif
#       endif
#   endif
#endif
