/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "sdkconfig.h"

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Debug Log //////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#define BROOKESIA_HAL_ADAPTOR_LOG_TAG "HalAdpt"

#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Audio Codec Device ///////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE  (0)
#   endif
#endif
/* Codec player interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL  (0)
#   endif
#endif

#if BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_DEFAULT)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_DEFAULT)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_DEFAULT  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_DEFAULT
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_DEFAULT  (75)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MIN)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MIN)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MIN  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MIN
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MIN  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MAX)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MAX)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MAX  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MAX
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_VOLUME_MAX  (100)
#       endif
#   endif
#endif
/* Codec recorder interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS  (16)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS  (1)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE  (16000)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT  "M"
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN  "36.0"
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS  "{\"0\":0.0,\"1\":0.0}"
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Display LCD Device ///////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE  (0)
#   endif
#endif
/* LCD panel interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL  (0)
#   endif
#endif
/* LCD touch interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL  (0)
#   endif
#endif
/* LEDC backlight interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_DEFAULT)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_DEFAULT)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_DEFAULT  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_DEFAULT
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_DEFAULT  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MIN)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MIN)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MIN  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MIN
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MIN  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MAX)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MAX)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MAX  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MAX
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_BRIGHTNESS_MAX  (100)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Storage Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE  (0)
#   endif
#endif
/* General FS interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD  (0)
#       endif
#   endif
#endif
