/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "sdkconfig.h"

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Debug Log //////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#define BROOKESIA_HAL_ADAPTOR_LOG_TAG "HalAdpt"

#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if BROOKESIA_HAL_ADAPTOR_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_HAL_ADAPTOR_GENERAL_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_GENERAL_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_GENERAL_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_GENERAL_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_GENERAL_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_BOARD_INFO_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_POWER_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_AXP2101_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_BATTERY_ADC_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_PLAYER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_DEVICE_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LEDC_BACKLIGHT_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_TOUCH_IMPL_ENABLE_DEBUG_LOG  (0)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////// General Device //////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_GENERAL_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_GENERAL_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_GENERAL_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_GENERAL_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_GENERAL_DEVICE  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_ENABLE_GENERAL_DEVICE
#   if !defined(BROOKESIA_HAL_ADAPTOR_GENERAL_ENABLE_BOARD_INFO_IMPL)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_GENERAL_ENABLE_BOARD_INFO_IMPL)
#           define BROOKESIA_HAL_ADAPTOR_GENERAL_ENABLE_BOARD_INFO_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_GENERAL_ENABLE_BOARD_INFO_IMPL
#       else
#           define BROOKESIA_HAL_ADAPTOR_GENERAL_ENABLE_BOARD_INFO_IMPL  (0)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Audio Codec Device ///////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_AUDIO_DEVICE  (0)
#   endif
#endif

/* Codec player interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_PLAYER_IMPL  (0)
#   endif
#endif

/* Codec recorder interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_AUDIO_ENABLE_CODEC_RECORDER_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_BITS  (16)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNELS  (1)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_SAMPLE_RATE  (16000)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_MIC_LAYOUT  "M"
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_GENERAL_GAIN  "36.0"
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS)
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS  CONFIG_BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS
#       else
#           define BROOKESIA_HAL_ADAPTOR_AUDIO_CODEC_RECORDER_CHANNEL_GAINS  "{\"0\":0.0,\"1\":0.0}"
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Display LCD Device ///////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_DISPLAY_DEVICE  (0)
#   endif
#endif
/* LCD panel interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_PANEL_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_H_RES  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_V_RES  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_X_ALIGN_BYTES  (1)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES)
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES
#       else
#           define BROOKESIA_HAL_ADAPTOR_DISPLAY_LCD_PANEL_DRAW_Y_ALIGN_BYTES  (1)
#       endif
#   endif
#endif
/* LCD touch interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LCD_TOUCH_IMPL  (0)
#   endif
#endif
/* LEDC backlight interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_DISPLAY_ENABLE_LEDC_BACKLIGHT_IMPL  (0)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
///////////////////////////////////////////////// Storage Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_STORAGE_DEVICE  (0)
#   endif
#endif
/* General FS interface */
#if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL)
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL
#   else
#       define BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_STORAGE_ENABLE_GENERAL_FS_IMPL
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SPIFFS  (0)
#       endif
#   endif
#   if !defined(BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD)
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD  CONFIG_BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD
#       else
#           define BROOKESIA_HAL_ADAPTOR_STORAGE_GENERAL_FS_ENABLE_SDCARD  (0)
#       endif
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Power Device ///////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE)
#   if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE)
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE  CONFIG_BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE
#   else
#       define BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE  (0)
#   endif
#endif
#if BROOKESIA_HAL_ADAPTOR_ENABLE_POWER_DEVICE
#   if !defined(BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY)
#       if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY)
#           define BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY
#       else
#           define BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY  (0)
#       endif
#   endif
#   if BROOKESIA_HAL_ADAPTOR_POWER_ENABLE_BATTERY
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_AXP2101  (0)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_IMPL_ADC  (0)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_LOW_VOLTAGE_MV  (3500)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_CRITICAL_VOLTAGE_MV  (3300)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_MUL  (2)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_VOLTAGE_SCALE_DIV  (1)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_CHARGE_DETECT_MV  (1000)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_SAMPLE_COUNT  (8)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_RAW_MAX  (4095)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_REF_VOLTAGE_MV  (3300)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MIN_MV  (3300)
#           endif
#       endif
#       if !defined(BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV)
#           if defined(CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV)
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV  CONFIG_BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV
#           else
#               define BROOKESIA_HAL_ADAPTOR_POWER_BATTERY_ADC_PERCENTAGE_VOLTAGE_MAX_MV  (4200)
#           endif
#       endif
#   endif
#endif
