/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#include <array>
#include <cerrno>
#include <chrono>
#include <exception>
#include <limits>
#include <string_view>

#include "boost/format.hpp"
#include "boost/json.hpp"
#include "esp_mac.h"
#include "esp_wifi.h"
#include "nvs_flash.h"
#include "esp_netif.h"
#include "esp_http_server.h"
#include "lwip/sockets.h"
#include "brookesia/hal_adaptor/macro_configs.h"
#if !BROOKESIA_HAL_ADAPTOR_WIFI_BACKEND_ENABLE_DEBUG_LOG
#   define BROOKESIA_LOG_DISABLE_DEBUG_TRACE 1
#endif
#include "private/utils.hpp"
#include "brookesia/lib_utils/function_guard.hpp"
#include "brookesia/lib_utils/thread_config.hpp"
#include "softap.hpp"
#include "backend.hpp"

namespace esp_brookesia::hal {

namespace {
wifi_ap_config_t get_ap_config(const wifi::SoftApParams &ap_params)
{
    BROOKESIA_LOG_TRACE_GUARD();

    BROOKESIA_LOGD("Params: ap_params(%1%)", BROOKESIA_DESCRIBE_TO_STR(ap_params));

    // Initialize the config with default values
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
    wifi_ap_config_t cfg = {
        .ssid = "",
        .password = "",
        .channel = static_cast<uint8_t>(ap_params.has_channel() ? ap_params.get_channel() :
                                        BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT),
        .authmode = WIFI_AUTH_OPEN,
        .max_connection = ap_params.max_connection,
    };
#pragma GCC diagnostic pop

    if (!ap_params.ssid.empty()) {
        snprintf(reinterpret_cast<char *>(cfg.ssid), sizeof(cfg.ssid), "%s", ap_params.ssid.c_str());
    } else {
        auto default_ssid = SoftAp::get_ap_default_ssid();
        BROOKESIA_LOGW("No SSID provided, use default SSID: %1%", default_ssid);
        snprintf(reinterpret_cast<char *>(cfg.ssid), sizeof(cfg.ssid), "%s", default_ssid.c_str());
    }
    if (!ap_params.password.empty()) {
        snprintf(reinterpret_cast<char *>(cfg.password), sizeof(cfg.password), "%s", ap_params.password.c_str());
        cfg.authmode = WIFI_AUTH_WPA2_PSK;
    }

    return cfg;
}

wifi_scan_config_t get_ap_start_scan_config()
{
    BROOKESIA_LOG_TRACE_GUARD();

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
    return {
        .ssid = nullptr,
        .bssid = nullptr,
        .channel = 0,
        .show_hidden = true,
        .scan_type = WIFI_SCAN_TYPE_ACTIVE,
        .scan_time = {
            .active = {
                .min = 100,
                .max = 300,
            }
        }
    };
#pragma GCC diagnostic pop
}
} // anonymous namespace

/* Symbols generated by EMBED_TXTFILES for the captive portal HTML page */
extern const char wifi_provision_html_start[] asm("_binary_wifi_provision_html_start");
extern const char wifi_provision_html_end[]   asm("_binary_wifi_provision_html_end");

constexpr int PROVISION_DNS_PORT = 53;

/* DNS header structure for captive portal DNS server */
struct ProvisionDnsHeader {
    uint16_t id;
    uint16_t flags;
    uint16_t qdcount;
    uint16_t ancount;
    uint16_t nscount;
    uint16_t arcount;
} __attribute__((packed));

bool SoftAp::start_soft_ap()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (has_softap_state_flag_bit(SoftApStateFlagBit::Setuping) ||
            has_softap_state_flag_bit(SoftApStateFlagBit::Setuped)) {
        BROOKESIA_LOGD("AP is already setuping or setuped, skip");
        return true;
    }

    update_softap_state_flag_bit(SoftApStateFlagBit::Setuping, true);

    lib_utils::FunctionGuard stop_guard([this]() {
        BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();
        stop_soft_ap();
    });

    softap_netif_ = esp_netif_create_default_wifi_ap();
    BROOKESIA_CHECK_NULL_RETURN(softap_netif_, false, "Create default AP netif failed");

    auto hal = static_cast<WifiEspBackend *>(hal_);
    BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

    if (is_softap_setup_ready()) {
        auto softap_params = get_soft_ap_params();
        if (softap_params.ssid.empty()) {
            softap_params.ssid = SoftAp::get_ap_default_ssid();
            BROOKESIA_LOGW("No SSID provided, use default '%1%'", softap_params.ssid);
            set_soft_ap_params(softap_params);
            hal->notify_softap_params_updated(softap_params);
        }

        if (softap_params.has_channel()) {
            BROOKESIA_LOGD("Channel specified, directly start AP");
            BROOKESIA_CHECK_FALSE_RETURN(do_soft_ap_start(), false, "Start SoftAP failed");
            stop_guard.release();
            return true;
        } else {
            BROOKESIA_LOGD("No channel specified, need to start setup task to get best channel");
        }
    } else {
        BROOKESIA_LOGD("Softap setup is not ready, need to start setup task");
    }

    BROOKESIA_CHECK_FALSE_RETURN(start_soft_ap_setup_task(), false, "Start SoftAP setup task failed");

    stop_guard.release();

    return true;
}

void SoftAp::stop_soft_ap()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    /* Clean up provision servers if running (before tearing down AP) */
    cleanup_provision_servers();

    stop_soft_ap_setup_task();
    stop_soft_ap_event_task();

    do_softap_stop();

    // Publish SoftAP stopped event if AP is still started
    if (has_softap_state_flag_bit(SoftApStateFlagBit::Started)) {
        BROOKESIA_LOGD("Publish missing SoftAP stopped event");
        auto hal = static_cast<WifiEspBackend *>(hal_);
        if (hal != nullptr) {
            hal->notify_softap_event(wifi::SoftApEvent::Stopped);
        }
    }
    clear_softap_state_flags();

    if (softap_netif_ != nullptr) {
        esp_netif_destroy_default_wifi(reinterpret_cast<esp_netif_t *>(softap_netif_));
        softap_netif_ = nullptr;
    }
}

bool SoftAp::set_soft_ap_params(const wifi::SoftApParams &params)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: params(%1%)", BROOKESIA_DESCRIBE_TO_STR(params));

    softap_params_ = params;

    return true;
}

void SoftAp::set_provision_connect_status(ProvisionConnectStatus status)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: status(%1%)", BROOKESIA_DESCRIBE_TO_STR(status));

    provision_connect_status_ = status;

    if (status == ProvisionConnectStatus::Success) {
        BROOKESIA_LOGW(
            "Provision connect succeeded, schedule to close provision in %1%ms", BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS
        );

        auto hal = static_cast<WifiEspBackend *>(hal_);
        BROOKESIA_CHECK_NULL_EXIT(hal, "Invalid WifiEspBackend pointer");

        auto task_scheduler = hal->get_task_scheduler();
        BROOKESIA_CHECK_NULL_EXIT(task_scheduler, "Invalid task scheduler");

        auto task = [this]() {
            BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

            BROOKESIA_LOGI("%1% seconds later, close provision...", BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS / 1000);

            stop_soft_ap_provision();
        };
        auto result = task_scheduler->post_delayed(
                          task, BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SUCCESS_CLOSE_DELAY_MS, nullptr,
                          hal->get_task_group()
                      );
        BROOKESIA_CHECK_FALSE_EXIT(result, "Failed to post close provision task");
    }
}

void SoftAp::set_provision_connect_error_msg(const std::string &msg)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: msg(%1%)", msg);

    provision_connect_error_msg_ = msg;
}

void SoftAp::set_provision_dns_sock(int sock)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: sock(%1%)", sock);

    provision_dns_sock_ = sock;
}

void SoftAp::trigger_provision_connect(const std::string &ssid, const std::string &password)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: ssid(%1%)", ssid);

    auto hal = static_cast<WifiEspBackend *>(hal_);
    BROOKESIA_CHECK_NULL_EXIT(hal, "Invalid WifiEspBackend pointer");

    /* Post connect operation to the task scheduler for thread safety */
    auto task_scheduler = hal->get_task_scheduler();
    BROOKESIA_CHECK_NULL_EXIT(task_scheduler, "Invalid task scheduler");

    auto task = [this, hal, ssid, password]() {
        BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();
        hal->set_target_connect_ap_info(wifi::ConnectApInfo(ssid, password));
        auto result = hal->request_station_action(wifi::StationAction::Connect);
        BROOKESIA_CHECK_FALSE_EXIT(result, "Failed to trigger connect general action");
    };
    auto result = task_scheduler->post(task, nullptr, hal->get_task_group());
    BROOKESIA_CHECK_FALSE_EXIT(result, "Failed to post connect operation task");
}

bool SoftAp::start_soft_ap_provision()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (is_softap_provision_running()) {
        BROOKESIA_LOGD("SoftAP provision is already running, skip");
        return true;
    }

    auto hal = static_cast<WifiEspBackend *>(hal_);
    BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

    lib_utils::FunctionGuard stop_guard([this]() {
        BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();
        stop_soft_ap_provision();
    });

    is_softap_provision_running_ = true;

    /* Trigger disconnect action before starting provision. Auto-connect policy is owned by the service. */
    hal->request_station_action(wifi::StationAction::Disconnect);

    /* Start SoftAP (handles AP mode, channel selection, etc.) */
    BROOKESIA_CHECK_FALSE_RETURN(start_soft_ap(), false, "Failed to start SoftAP for provision");

    /* Start HTTP captive portal server */
    BROOKESIA_CHECK_FALSE_RETURN(init_provision_http_server(), false, "Failed to init provision HTTP server");

    /* Start DNS server for captive portal redirect */
    BROOKESIA_CHECK_FALSE_RETURN(init_provision_dns_server(), false, "Failed to init provision DNS server");

    provision_connect_status_ = ProvisionConnectStatus::Idle;
    provision_connect_error_msg_.clear();

    stop_guard.release();

    BROOKESIA_LOGI("SoftAP provision started");

    return true;
}

bool SoftAp::stop_soft_ap_provision()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (!is_softap_provision_running()) {
        BROOKESIA_LOGD("SoftAP provision is not running, skip");
        return true;
    }

    auto hal = static_cast<WifiEspBackend *>(hal_);
    BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

    /* Clean up provision servers and stop SoftAP */
    cleanup_provision_servers();
    stop_soft_ap();

    return true;
}

bool SoftAp::on_hal_scan_ap_infos_updated(const std::vector<wifi::ScanApInfo> &ap_infos)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    // BROOKESIA_LOGD("Params: ap_infos(%1%)", BROOKESIA_DESCRIBE_TO_STR(ap_infos));

    if (has_softap_state_flag_bit(SoftApStateFlagBit::Setuping)) {
        BROOKESIA_LOGD("SoftAP is setuping, start AP with best channel");

        auto hal = static_cast<WifiEspBackend *>(hal_);
        BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

        auto softap_params = get_soft_ap_params();
        softap_params.channel = get_ap_best_channel(ap_infos);
        set_soft_ap_params(softap_params);
        hal->notify_softap_params_updated(softap_params);
        BROOKESIA_CHECK_FALSE_RETURN(do_soft_ap_start(), false, "Start SoftAP failed");
    }

    if (is_softap_provision_running()) {
        BROOKESIA_LOGD("SoftAP provision is running, notify provision to update AP list");
        boost::lock_guard<boost::mutex> lock(provision_scan_mutex_);
        provision_scan_ap_infos_ = ap_infos;
        provision_scan_completed_ = true;
        provision_scan_cv_.notify_all();
    }

    return true;
}

bool SoftAp::on_hal_softap_wifi_event(uint8_t event)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: event(%1%)", event);

    if (!has_softap_state_flag_bit(SoftApStateFlagBit::Setuped)) {
        BROOKESIA_LOGD("SoftAP is not setuped, skip");
        return true;
    }

    auto event_id = static_cast<wifi_event_t>(event);
    wifi::SoftApEvent softap_event = wifi::SoftApEvent::Max;
    switch (event_id) {
    case WIFI_EVENT_AP_START:
        BROOKESIA_LOGD("Detected SoftAP started event");
        softap_event = wifi::SoftApEvent::Started;
        break;
    case WIFI_EVENT_AP_STOP:
        BROOKESIA_LOGD("Detected SoftAP stopped event");
        softap_event = wifi::SoftApEvent::Stopped;
        break;
    case WIFI_EVENT_STA_DISCONNECTED:
        if (!is_softap_provision_running() || (get_provision_connect_status() != ProvisionConnectStatus::Connecting)) {
            BROOKESIA_LOGD("Provision is not running or not connecting, skip");
            break;
        }
        set_provision_connect_status(ProvisionConnectStatus::Failed);
        set_provision_connect_error_msg("Connection failed after retries");
        break;
    default:
        break;
    }

    if (softap_event != wifi::SoftApEvent::Max) {
        BROOKESIA_CHECK_FALSE_RETURN(start_soft_ap_event_task(softap_event), false, "Failed to start SoftAP event task");
    }

    return true;
}

bool SoftAp::on_hal_softap_ip_event(uint8_t event)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: event(%1%)", event);

    if (!has_softap_state_flag_bit(SoftApStateFlagBit::Setuped)) {
        BROOKESIA_LOGD("SoftAP is not setuped, skip");
        return true;
    }

    auto event_id = static_cast<ip_event_t>(event);
    switch (event_id) {
    case IP_EVENT_STA_GOT_IP:
        if (!is_softap_provision_running() ||
                (get_provision_connect_status() != ProvisionConnectStatus::Connecting)) {
            BROOKESIA_LOGD("Provision is not running or not connecting, skip");
            break;
        }
        set_provision_connect_status(ProvisionConnectStatus::Success);
        break;
    default:
        break;
    }

    return true;
}

void SoftAp::reset_data()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    set_soft_ap_params(wifi::SoftApParams{});
}

void SoftAp::cleanup_provision_servers()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (!is_softap_provision_running_) {
        return;
    }

    is_softap_provision_running_ = false;
    provision_connect_status_ = ProvisionConnectStatus::Idle;
    provision_connect_error_msg_.clear();

    deinit_provision_http_server();
    deinit_provision_dns_server();

    BROOKESIA_LOGI("SoftAP provision stopped");
}

bool SoftAp::init_provision_http_server()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (provision_httpd_ != nullptr) {
        BROOKESIA_LOGD("Provision HTTP server already running, skip");
        return true;
    }

    lib_utils::FunctionGuard deinit_guard([this]() {
        BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();
        deinit_provision_http_server();
    });

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
    httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
    cfg.uri_match_fn = httpd_uri_match_wildcard;
    cfg.max_uri_handlers = 8;
    cfg.lru_purge_enable = true;

    httpd_handle_t httpd = nullptr;
    BROOKESIA_CHECK_ESP_ERR_RETURN(httpd_start(&httpd, &cfg), false, "Failed to start provision httpd");
    provision_httpd_ = httpd;

    /* Register URI handlers - order matters: specific routes before wildcard */
    auto provision_handle_root = +[](httpd_req_t *req) -> esp_err_t {
        httpd_resp_set_type(req, "text/html");
        size_t len = wifi_provision_html_end - wifi_provision_html_start;
        return httpd_resp_send(req, wifi_provision_html_start, len);
    };
    httpd_uri_t root_get = {
        .uri = "/",
        .method = HTTP_GET,
        .handler = provision_handle_root,
        .user_ctx = this,
    };
    httpd_register_uri_handler(httpd, &root_get);

    auto provision_handle_scan = +[](httpd_req_t *req) -> esp_err_t {
        BROOKESIA_LOG_TRACE_GUARD();

        auto softap = static_cast<SoftAp *>(req->user_ctx);
        BROOKESIA_CHECK_NULL_RETURN(softap, ESP_ERR_INVALID_ARG, "Invalid SoftAp pointer");

        auto hal = static_cast<WifiEspBackend *>(softap->hal_);
        BROOKESIA_CHECK_NULL_RETURN(hal, ESP_ERR_INVALID_ARG, "Invalid WifiEspBackend pointer");

        auto task_scheduler = hal->get_task_scheduler();
        BROOKESIA_CHECK_NULL_RETURN(task_scheduler, ESP_ERR_INVALID_ARG, "Invalid task scheduler");

        hal->stop_scan();

        /* Cancel previous scan task if exists */
        if (softap->provision_scan_periodic_task_ != 0)
        {
            task_scheduler->cancel(softap->provision_scan_periodic_task_);
            softap->provision_scan_periodic_task_ = 0;
        }

        {
            boost::lock_guard<boost::mutex> lock(softap->provision_scan_mutex_);
            softap->provision_scan_ap_infos_.clear();
            softap->provision_scan_completed_ = false;
        }

        auto scan_periodic_task = [softap, hal]()
        {
            BROOKESIA_LOG_TRACE_GUARD();

            BROOKESIA_CHECK_FALSE_RETURN(hal->do_scan_start(), false, "Failed to start scan");

            if (hal->is_scanning()) {
                BROOKESIA_LOGD("Scan is already running, stop periodic task");
                return false;
            }

            return true;
        };
        auto result = task_scheduler->post_periodic(
                          scan_periodic_task, BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_START_INTERVAL_MS,
                          &softap->provision_scan_periodic_task_,
                          hal->get_task_group()
                      );
        BROOKESIA_CHECK_FALSE_RETURN(result, ESP_ERR_INVALID_STATE, "Failed to start scan periodic task");

        /* Wait for scan results with timeout */
        boost::unique_lock<boost::mutex> lock(softap->provision_scan_mutex_);
        auto timeout = boost::chrono::milliseconds(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_SCAN_TIMEOUT_MS);
        auto deadline = boost::chrono::steady_clock::now() + timeout;

        while (!softap->provision_scan_completed_)
        {
            auto status = softap->provision_scan_cv_.wait_until(lock, deadline);
            if (status == boost::cv_status::timeout) {
                BROOKESIA_LOGD("Scan timeout, cancel periodic task and return empty result");

                /* Timeout: cancel scan task and return empty result */
                lock.unlock();
                task_scheduler->cancel(softap->provision_scan_periodic_task_);
                softap->provision_scan_periodic_task_ = 0;

                httpd_resp_set_type(req, "application/json");
                httpd_resp_sendstr(req, "[]");
                return ESP_OK;
            }
        }

        /* Scan completed, cancel periodic task */
        lock.unlock();
        task_scheduler->cancel(softap->provision_scan_periodic_task_);
        softap->provision_scan_periodic_task_ = 0;

        /* Re-acquire lock to read scan results */
        lock.lock();

        BROOKESIA_LOGD("Scan completed, return %1% APs", softap->provision_scan_ap_infos_.size());

        /* Build JSON response using boost::json */
        boost::json::array arr;
        for (const auto &ap_info : softap->provision_scan_ap_infos_)
        {
            arr.push_back(boost::json::object{
                {"ssid", ap_info.ssid},
                {"rssi", ap_info.rssi},
                {"locked", ap_info.is_locked}
            });
        }
        std::string json_str;
        BROOKESIA_CHECK_EXCEPTION_RETURN(
            json_str = boost::json::serialize(arr), ESP_ERR_NO_MEM, "Failed to serialize JSON"
        );

        httpd_resp_set_type(req, "application/json");

        return httpd_resp_sendstr(req, json_str.c_str());
    };
    httpd_uri_t scan_get = {
        .uri = "/api/wifi/scan",
        .method = HTTP_GET,
        .handler = provision_handle_scan,
        .user_ctx = this,
    };
    httpd_register_uri_handler(httpd, &scan_get);

    auto provision_handle_connect = +[](httpd_req_t *req) -> esp_err_t {
        BROOKESIA_LOG_TRACE_GUARD();

        auto softap = static_cast<SoftAp *>(req->user_ctx);
        BROOKESIA_CHECK_NULL_RETURN(softap, ESP_ERR_INVALID_ARG, "Invalid SoftAp pointer");

        /* Read body */
        std::vector<char> buffer(256);
        auto buf = buffer.data();

        int recv_len = httpd_req_recv(req, buf, buffer.size() - 1);
        if (recv_len <= 0)
        {
            return httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "Invalid body");
        }
        buf[recv_len] = '\0';

        /* Parse JSON using boost::json */
        try
        {
            auto json = boost::json::parse(std::string_view(buf, recv_len));
            auto &obj = json.as_object();

            if (!obj.contains("ssid") || !obj.at("ssid").is_string()) {
                return httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "SSID missing");
            }

            auto ssid = std::string(obj.at("ssid").as_string());
            auto pwd = (obj.contains("password") && obj.at("password").is_string())
                       ? std::string(obj.at("password").as_string())
                       : std::string();

            BROOKESIA_LOGI("Provision: User chose SSID: %1%", ssid);

            /* Update provision status */
            softap->set_provision_connect_status(SoftAp::ProvisionConnectStatus::Connecting);
            softap->set_provision_connect_error_msg("");

            /* Trigger connect via WifiEspBackend member function (has friend access to Wifi) */
            softap->trigger_provision_connect(ssid, pwd);

            httpd_resp_set_type(req, "application/json");
            httpd_resp_sendstr(req, "{\"success\":true}");
            return ESP_OK;

        } catch (const std::exception &e)
        {
            BROOKESIA_LOGE("Provision: JSON parse error: %1%", e.what());
            return httpd_resp_send_err(req, HTTPD_400_BAD_REQUEST, "JSON parse error");
        }
    };
    httpd_uri_t connect_post = {
        .uri = "/api/wifi/connect",
        .method = HTTP_POST,
        .handler = provision_handle_connect,
        .user_ctx = this,
    };
    httpd_register_uri_handler(httpd, &connect_post);

    auto provision_handle_status = +[](httpd_req_t *req) -> esp_err_t {
        BROOKESIA_LOG_TRACE_GUARD();

        auto softap = static_cast<SoftAp *>(req->user_ctx);
        BROOKESIA_CHECK_NULL_RETURN(softap, ESP_ERR_INVALID_ARG, "Invalid SoftAp pointer");

        auto connect_status = softap->get_provision_connect_status();

        const char *status_str = "idle";
        switch (connect_status)
        {
        case SoftAp::ProvisionConnectStatus::Connecting:
            status_str = "connecting";
            break;
        case SoftAp::ProvisionConnectStatus::Success:
            status_str = "success";
            break;
        case SoftAp::ProvisionConnectStatus::Failed:
            status_str = "failed";
            break;
        case SoftAp::ProvisionConnectStatus::Idle:
        default:
            status_str = "idle";
            break;
        }

        boost::json::object obj;
        obj["status"] = status_str;
        if (connect_status == SoftAp::ProvisionConnectStatus::Failed &&
                !softap->get_provision_connect_error_msg().empty())
        {
            obj["error"] = softap->get_provision_connect_error_msg();
        }
        auto json_str = boost::json::serialize(obj);

        httpd_resp_set_type(req, "application/json");
        return httpd_resp_sendstr(req, json_str.c_str());
    };
    httpd_uri_t status_get = {
        .uri = "/api/wifi/status",
        .method = HTTP_GET,
        .handler = provision_handle_status,
        .user_ctx = this,
    };
    httpd_register_uri_handler(httpd, &status_get);

    /* Wildcard redirect for captive portal (any other URI -> root page) */
    auto provision_handle_any = +[](httpd_req_t *req) -> esp_err_t {
        httpd_resp_set_status(req, "302 Found");
        httpd_resp_set_hdr(req, "Location", "http://192.168.4.1/");
        httpd_resp_send(req, nullptr, 0);
        return ESP_OK;
    };
    httpd_uri_t any_get = {
        .uri = "/*",
        .method = HTTP_GET,
        .handler = provision_handle_any,
        .user_ctx = this,
    };
    httpd_register_uri_handler(httpd, &any_get);
#pragma GCC diagnostic pop

    deinit_guard.release();

    BROOKESIA_LOGI("Provision HTTP server started on port %1%", cfg.server_port);

    return true;
}

void SoftAp::deinit_provision_http_server()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (provision_httpd_ != nullptr) {
        httpd_stop(static_cast<httpd_handle_t>(provision_httpd_));
        provision_httpd_ = nullptr;
        BROOKESIA_LOGD("Provision HTTP server stopped");
    }
    if (provision_scan_periodic_task_ != 0) {
        auto hal = static_cast<WifiEspBackend *>(hal_);
        auto task_scheduler = (hal != nullptr) ? hal->get_task_scheduler() : nullptr;
        if (task_scheduler) {
            task_scheduler->cancel(provision_scan_periodic_task_);
        }
        provision_scan_periodic_task_ = 0;
    }

    BROOKESIA_LOGI("Provision HTTP server stopped");
}

bool SoftAp::init_provision_dns_server()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (provision_dns_thread_ != nullptr) {
        BROOKESIA_LOGD("Provision DNS server already running, skip");
        return true;
    }

    /* ---- Provision DNS server thread (captive portal) ---- */
    /* Every DNS query is answered with 192.168.4.1 to redirect to the captive portal */
    auto provision_dns_thread = [this]() {
        int sock = socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP);
        if (sock < 0) {
            BROOKESIA_LOGE("Provision DNS: socket create failed: %1%", errno);
            return;
        }
        set_provision_dns_sock(sock);

        struct sockaddr_in addr = {};
        addr.sin_family = AF_INET;
        addr.sin_port = htons(PROVISION_DNS_PORT);
        addr.sin_addr.s_addr = htonl(INADDR_ANY);

        if (bind(sock, reinterpret_cast<struct sockaddr *>(&addr), sizeof(addr)) < 0) {
            BROOKESIA_LOGE("Provision DNS: bind failed: %1%", errno);
            lwip_close(sock);
            set_provision_dns_sock(-1);
            return;
        }

        BROOKESIA_LOGI("Provision: Captive DNS started on port %1%", PROVISION_DNS_PORT);

        std::vector<uint8_t> rx_buffer(256);
        auto *rx_buf = rx_buffer.data();

        while (true) {
            struct sockaddr_in source_addr;
            socklen_t socklen = sizeof(source_addr);
            int len = recvfrom(sock, rx_buf, rx_buffer.size(), 0,
                               reinterpret_cast<struct sockaddr *>(&source_addr), &socklen);
            if (len <= 0) {
                break;
            }

            if (len < static_cast<int>(sizeof(ProvisionDnsHeader))) {
                continue;
            }

            auto *hdr = reinterpret_cast<ProvisionDnsHeader *>(rx_buf);

            // Only support standard query
            if ((ntohs(hdr->flags) & 0x8000) != 0) {
                continue; // Ignore if already response
            }

            uint16_t qdcount = ntohs(hdr->qdcount);
            if (qdcount != 1) {
                continue; // Only handle single question
            }

            uint8_t *question = rx_buf + sizeof(ProvisionDnsHeader);
            uint8_t *end = rx_buf + len;

            // Parse QName safely
            uint8_t *q = question;
            while (q < end && *q) {
                q += (*q) + 1;
            }
            if (q + 5 > end) {
                continue; // malformed
            }

            q++; // skip null label

            uint16_t qtype = ntohs(*reinterpret_cast<uint16_t *>(q));
            uint16_t qclass = ntohs(*reinterpret_cast<uint16_t *>(q + 2));
            q += 4;

            // Only respond to A record queries (Type 1)
            if (qtype != 1 || qclass != 1) {
                continue;
            }

            // Remove any additional / authority sections
            hdr->ancount = htons(0);
            hdr->nscount = htons(0);
            hdr->arcount = htons(0);

            // Build answer
            uint8_t *ptr = rx_buf + len;

            // Name pointer to offset 12 (start of question)
            ptr[0] = 0xC0;
            ptr[1] = 0x0C;

            ptr[2] = 0x00; ptr[3] = 0x01; // Type A
            ptr[4] = 0x00; ptr[5] = 0x01; // Class IN

            ptr[6] = 0x00; ptr[7] = 0x00;
            ptr[8] = 0x00; ptr[9] = 0x1E; // TTL 30s

            ptr[10] = 0x00; ptr[11] = 0x04; // Data length 4

            ptr[12] = 192;
            ptr[13] = 168;
            ptr[14] = 4;
            ptr[15] = 1;

            size_t ans_len = 16;

            // Set response flags properly
            uint16_t flags = 0;
            flags |= 0x8000;  // QR = 1 (response)
            flags |= 0x0400;  // AA = 1 (authoritative)
            flags |= 0x0080;  // RA = 1 (recursion available)
            flags |= 0x0100;  // RD copy (optional safe default)

            hdr->flags = htons(flags);
            hdr->ancount = htons(1);

            int tx_len = len + ans_len;

            sendto(sock, rx_buf, tx_len, 0,
                   reinterpret_cast<struct sockaddr *>(&source_addr),
                   sizeof(source_addr));
        }

        lwip_close(sock);
        set_provision_dns_sock(-1);

        BROOKESIA_LOGI("Provision DNS server stopped");
    };
    {
        BROOKESIA_THREAD_CONFIG_GUARD({
            .core_id = BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_CORE_ID,
            .priority = BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_PRIORITY,
            .stack_size = BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_PROVISION_DNS_THREAD_STACK_SIZE,
        });
        BROOKESIA_CHECK_EXCEPTION_RETURN(
            provision_dns_thread_ = std::make_unique<boost::thread>(provision_dns_thread), false,
            "Failed to create provision DNS thread"
        );
    }

    return true;
}

void SoftAp::deinit_provision_dns_server()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (provision_dns_sock_ >= 0) {
        lwip_close(provision_dns_sock_);
        provision_dns_sock_ = -1;
    }
    /* Thread will exit after socket closure causes recvfrom to fail */
    if (provision_dns_thread_ != nullptr) {
        if (provision_dns_thread_->joinable()) {
            provision_dns_thread_->join();
        }
        provision_dns_thread_.reset();
    }
}

bool SoftAp::do_soft_ap_start(const wifi::SoftApParams *params)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (has_softap_state_flag_bit(SoftApStateFlagBit::Started) ||
            has_softap_state_flag_bit(SoftApStateFlagBit::Starting)) {
        BROOKESIA_LOGD("SoftAP is already starting or started, skip");
        return true;
    }

    update_softap_state_flag_bit(SoftApStateFlagBit::Setuping, false);
    update_softap_state_flag_bit(SoftApStateFlagBit::Setuped, true);
    update_softap_state_flag_bit(SoftApStateFlagBit::Starting, false);

    lib_utils::FunctionGuard stop_ap_guard([this]() {
        BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();
        do_softap_stop();
    });

    if (!params) {
        auto hal = static_cast<WifiEspBackend *>(hal_);
        BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

        auto softap_params = get_soft_ap_params();
        if (softap_params.ssid.empty()) {
            softap_params.ssid = SoftAp::get_ap_default_ssid();
            BROOKESIA_LOGW("No SSID provided, use default '%1%'", softap_params.ssid);
            set_soft_ap_params(softap_params);
            hal->notify_softap_params_updated(softap_params);
        }
    }

    wifi_config_t wifi_config = {
        .ap = get_ap_config(params ? *params : get_soft_ap_params()),
    };

    BROOKESIA_LOGI("Starting AP(%1%) in channel '%2%'...", wifi_config.ap.ssid, wifi_config.ap.channel);
    BROOKESIA_LOGD("With password: %1%", wifi_config.ap.password);

    BROOKESIA_CHECK_ESP_ERR_RETURN(esp_wifi_set_mode(WIFI_MODE_APSTA), false, "Set WiFi mode failed");
    BROOKESIA_CHECK_ESP_ERR_RETURN(esp_wifi_set_config(WIFI_IF_AP, &wifi_config), false, "Failed to set WiFi config");

    stop_ap_guard.release();

    return true;
}

void SoftAp::do_softap_stop()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (!has_softap_state_flag_bit(SoftApStateFlagBit::Started) &&
            !has_softap_state_flag_bit(SoftApStateFlagBit::Starting)) {
        BROOKESIA_LOGD("AP is not starting or started, skip");
        return;
    }

    update_softap_state_flag_bit(SoftApStateFlagBit::Stopping, true);

    BROOKESIA_CHECK_ESP_ERR_EXECUTE(esp_wifi_set_mode(WIFI_MODE_STA), {}, {
        BROOKESIA_LOGE("Set WiFi mode failed");
    });
}

bool SoftAp::start_soft_ap_setup_task()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (is_softap_setup_task_running()) {
        BROOKESIA_LOGD("SoftAP setup task is already running, skip");
        return true;
    }

    auto hal = static_cast<WifiEspBackend *>(hal_);
    BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

    auto task_scheduler = hal->get_task_scheduler();
    BROOKESIA_CHECK_NULL_RETURN(task_scheduler, false, "Invalid task scheduler");

    auto softap_setup_task = [this, hal, start_time = std::chrono::steady_clock::now()]() {
        BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

        if (has_softap_state_flag_bit(SoftApStateFlagBit::Setuped)) {
            BROOKESIA_LOGD("AP is setuped, stop setup task");
            stop_soft_ap_setup_task();
            return false;
        }

        if (std::chrono::steady_clock::now() - start_time >
                std::chrono::milliseconds(BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_TIMEOUT_MS)) {
            BROOKESIA_LOGE("Setup timeout, stop AP");
            stop_soft_ap();
            return false;
        }

        if (!is_softap_setup_ready()) {
            BROOKESIA_LOGD("WiFi is not started or stopping, skip setup");
            return true;
        }

        auto &softap_params = get_soft_ap_params();
        if (softap_params.has_channel()) {
            stop_soft_ap_setup_task();
            BROOKESIA_LOGD("Channel specified, directly start AP");
            BROOKESIA_CHECK_FALSE_RETURN(do_soft_ap_start(), false, "Start SoftAP failed");
            return false;
        }

        auto scan_cfg = get_ap_start_scan_config();
        if (!hal->do_scan_start(&scan_cfg)) {
            stop_soft_ap_setup_task();
            BROOKESIA_LOGW("Do scan failed, start SoftAP with default channel");
            BROOKESIA_CHECK_FALSE_RETURN(do_soft_ap_start(), false, "Start SoftAP failed");
            return false;
        }

        return true;
    };
    auto result = task_scheduler->post_periodic(
                      softap_setup_task, BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_SETUP_INTERVAL_MS, &softap_setup_task_,
                      hal->get_task_group()
                  );
    BROOKESIA_CHECK_FALSE_RETURN(result, false, "Post SoftAP setup task failed");

    return true;
}

void SoftAp::stop_soft_ap_setup_task()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (!is_softap_setup_task_running()) {
        BROOKESIA_LOGD("SoftAP setup task is not running, skip");
        return;
    }

    auto hal = static_cast<WifiEspBackend *>(hal_);
    auto task_scheduler = (hal != nullptr) ? hal->get_task_scheduler() : nullptr;
    if (task_scheduler) {
        task_scheduler->cancel(softap_setup_task_);
    }
    softap_setup_task_ = 0;
}

bool SoftAp::start_soft_ap_event_task(wifi::SoftApEvent event)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: event(%1%)", BROOKESIA_DESCRIBE_TO_STR(event));

    auto hal = static_cast<WifiEspBackend *>(hal_);
    BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

    auto task_scheduler = hal->get_task_scheduler();
    BROOKESIA_CHECK_NULL_RETURN(task_scheduler, false, "Invalid task scheduler");

    if (get_softap_target_event() == event) {
        BROOKESIA_LOGD("Event is the same as the target, skip");
        if ((softap_event_task_ != 0) &&
                (task_scheduler->get_state(softap_event_task_) == lib_utils::TaskScheduler::TaskState::Running)) {
            BROOKESIA_LOGD("Restart timer");
            task_scheduler->restart_timer(softap_event_task_);
        }
        return true;
    }

    /* Stop the previous event task */
    stop_soft_ap_event_task();

    set_softap_target_event(event);

    auto softap_event_task = [this, event]() {
        BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

        BROOKESIA_LOGD("Params: event(%1%)", BROOKESIA_DESCRIBE_TO_STR(event));

        switch (event) {
        case wifi::SoftApEvent::Started:
            update_softap_state_flag_bit(SoftApStateFlagBit::Started, true);
            update_softap_state_flag_bit(SoftApStateFlagBit::Starting, false);
            break;
        case wifi::SoftApEvent::Stopped:
            clear_softap_state_flags();
            break;
        default:
            break;
        }
        auto hal = static_cast<WifiEspBackend *>(hal_);
        if (hal != nullptr) {
            hal->notify_softap_event(get_softap_target_event());
        }
        stop_soft_ap_event_task();
    };
    auto result = task_scheduler->post_delayed(
                      softap_event_task, BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_EVENT_DELAY_MS, &softap_event_task_,
                      hal->get_task_group()
                  );
    BROOKESIA_CHECK_FALSE_RETURN(result, false, "Post SoftAP event task failed");

    return true;
}

void SoftAp::stop_soft_ap_event_task()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    if (softap_event_task_ == 0) {
        BROOKESIA_LOGD("No SoftAP event task, skip");
        return;
    }

    auto hal = static_cast<WifiEspBackend *>(hal_);
    auto task_scheduler = (hal != nullptr) ? hal->get_task_scheduler() : nullptr;
    if (task_scheduler) {
        task_scheduler->cancel(softap_event_task_);
    }

    softap_event_task_ = 0;
    set_softap_target_event(wifi::SoftApEvent::Max);
}

bool SoftAp::is_softap_setup_ready()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    auto hal = static_cast<WifiEspBackend *>(hal_);
    BROOKESIA_CHECK_NULL_RETURN(hal, false, "Invalid WifiEspBackend pointer");

    if (!hal->is_general_event_ready(wifi::GeneralEvent::Started) || hal->is_general_action_running(wifi::GeneralAction::Stop) ||
            hal->is_general_action_running(wifi::GeneralAction::Disconnect)) {
        return false;
    }

    return true;
}

void SoftAp::set_softap_target_event(wifi::SoftApEvent event)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: event(%1%)", BROOKESIA_DESCRIBE_TO_STR(event));

    softap_target_event_ = event;
}

void SoftAp::update_softap_state_flag_bit(SoftApStateFlagBit flag_bit, bool enable)
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    BROOKESIA_LOGD("Params: flag_bit(%1%), enable(%2%)", BROOKESIA_DESCRIBE_TO_STR(flag_bit), enable);

    BROOKESIA_LOGD("Original state flags(%1%)", BROOKESIA_DESCRIBE_TO_STR(softap_state_flags_));

    softap_state_flags_.set(BROOKESIA_DESCRIBE_ENUM_TO_NUM(flag_bit), enable);

    BROOKESIA_LOGD("New state flags(%1%)", BROOKESIA_DESCRIBE_TO_STR(softap_state_flags_));
}

void SoftAp::clear_softap_state_flags()
{
    BROOKESIA_LOG_TRACE_GUARD_WITH_THIS();

    softap_state_flags_.reset();
}

// This function should be called only when `is_softap_setup_ready() == true`,
// otherwise the MAC address cannot be obtained
std::string SoftAp::get_ap_default_ssid()
{
    uint8_t mac[6] = {};
    esp_err_t ret = ESP_OK;
#if CONFIG_ESP_HOSTED_ENABLED
    ret = esp_wifi_get_mac(WIFI_IF_AP, mac);
#else
    ret = esp_read_mac(mac, ESP_MAC_WIFI_SOFTAP);
#endif
    BROOKESIA_CHECK_ESP_ERR_RETURN(ret, "ESP-AP-Default", "Failed to read MAC address");

    return (boost::format("ESP-AP-%02X%02X")
            % static_cast<unsigned int>(mac[4])
            % static_cast<unsigned int>(mac[5])).str();
}

// TODO: If AP fails to start, automatically switch channel
uint8_t SoftAp::get_ap_best_channel(const std::vector<wifi::ScanApInfo> &ap_infos)
{
    if (ap_infos.empty()) {
        BROOKESIA_LOGD("No AP scanned, return default channel: %1%", BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT);
        return BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT;
    }

    std::array < size_t, BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX + 1 > channel_count{};
    for (const auto &ap : ap_infos) {
        if ((ap.channel >= BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN) && (ap.channel <= BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX)) {
            channel_count[ap.channel]++;
        }
    }

    uint8_t best_channel = BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_DEFAULT;
    float best_score = std::numeric_limits<float>::max();
    auto get = [&](int ch) -> size_t {
        return (ch >= BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN && ch <= BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX) ? channel_count[ch] : 0;
    };
    for (uint8_t ch = BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MIN; ch <= BROOKESIA_HAL_ADAPTOR_WIFI_SOFTAP_CHANNEL_MAX; ++ch) {
        // --- 1. Adjacent channel weighted interference ---
        float score =
            0.25f * get(ch - 2) +
            0.50f * get(ch - 1) +
            1.00f * get(ch) +
            0.50f * get(ch + 1) +
            0.25f * get(ch + 2);
        // --- 2. Avoid "falsely clean" channels with 0 AP present ---
        if (channel_count[ch] == 0) {
            score += 0.8f;   // Empirical value: slight penalty
        }
        // --- 3. Deprioritize traditionally crowded channels ---
        if (ch == 1 || ch == 6 || ch == 11) {
            score += 2.0f;   // Provisioning AP: strongly not recommended
        }
        // --- 4. Penalty for edge channel compatibility ---
        if (ch >= 12) {
            score += 1.0f;
        }
        BROOKESIA_LOGI("\t - Scanned channel[%1%]: AP count(%2%), score(%3$.2f)", ch, channel_count[ch], score);

        if (score < best_score) {
            best_score = score;
            best_channel = ch;
        }
    }

    BROOKESIA_LOGI("Best AP channel: %1% (score=%2$.2f)", best_channel, best_score);

    return best_channel;
}

} // namespace esp_brookesia::hal
