/*
 * SPDX-FileCopyrightText: 2025-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "sdkconfig.h"

/* Debug log */
#define BROOKESIA_SERVICE_SNTP_LOG_TAG "SvcSNTP"

/* Auto register */
#if !defined(BROOKESIA_SERVICE_SNTP_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_SERVICE_SNTP_ENABLE_AUTO_REGISTER  CONFIG_BROOKESIA_SERVICE_SNTP_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_SERVICE_SNTP_ENABLE_AUTO_REGISTER  (0)
#   endif
#endif

/* Plugin symbol */
#if BROOKESIA_SERVICE_SNTP_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_SERVICE_SNTP_PLUGIN_SYMBOL)
#       define BROOKESIA_SERVICE_SNTP_PLUGIN_SYMBOL  service_sntp_symbol
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_SNTP_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_SNTP_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_SNTP_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_SNTP_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_SNTP_DEFAULT_NTP_SERVER)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_DEFAULT_NTP_SERVER)
#       define BROOKESIA_SERVICE_SNTP_DEFAULT_NTP_SERVER  CONFIG_BROOKESIA_SERVICE_SNTP_DEFAULT_NTP_SERVER
#   else
#       define BROOKESIA_SERVICE_SNTP_DEFAULT_NTP_SERVER  "pool.ntp.org"
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_SNTP_DEFAULT_TIMEZONE)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_DEFAULT_TIMEZONE)
#       define BROOKESIA_SERVICE_SNTP_DEFAULT_TIMEZONE  CONFIG_BROOKESIA_SERVICE_SNTP_DEFAULT_TIMEZONE
#   else
#       define BROOKESIA_SERVICE_SNTP_DEFAULT_TIMEZONE  "CST-8"
#   endif
#endif

#if !defined(BROOKESIA_SERVICE_SNTP_WAIT_FOR_NETWORK_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_WAIT_FOR_NETWORK_INTERVAL_MS)
#       define BROOKESIA_SERVICE_SNTP_WAIT_FOR_NETWORK_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_SNTP_WAIT_FOR_NETWORK_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_SNTP_WAIT_FOR_NETWORK_INTERVAL_MS  (1000)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_SNTP_SYNC_TIME_INTERVAL_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_SYNC_TIME_INTERVAL_MS)
#       define BROOKESIA_SERVICE_SNTP_SYNC_TIME_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_SNTP_SYNC_TIME_INTERVAL_MS
#   else
#       define BROOKESIA_SERVICE_SNTP_SYNC_TIME_INTERVAL_MS  (1000)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_SNTP_SYNC_TIME_TIMEOUT_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_SYNC_TIME_TIMEOUT_MS)
#       define BROOKESIA_SERVICE_SNTP_SYNC_TIME_TIMEOUT_MS  CONFIG_BROOKESIA_SERVICE_SNTP_SYNC_TIME_TIMEOUT_MS
#   else
#       define BROOKESIA_SERVICE_SNTP_SYNC_TIME_TIMEOUT_MS  (60000)
#   endif
#endif
#if !defined(BROOKESIA_SERVICE_SNTP_SYNC_TIME_RETRY_DELAY_MS)
#   if defined(CONFIG_BROOKESIA_SERVICE_SNTP_SYNC_TIME_RETRY_DELAY_MS)
#       define BROOKESIA_SERVICE_SNTP_SYNC_TIME_RETRY_DELAY_MS  CONFIG_BROOKESIA_SERVICE_SNTP_SYNC_TIME_RETRY_DELAY_MS
#   else
#       define BROOKESIA_SERVICE_SNTP_SYNC_TIME_RETRY_DELAY_MS  (1000)
#   endif
#endif
