// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LabelMacAddr;
extern lv_obj_t * ui_LabelIpAddr;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_LabelTitle;
extern lv_obj_t * ui_LabelStatus;
extern lv_obj_t * ui_ButtonConnect;
extern lv_obj_t * ui_LabelConnect;
extern lv_obj_t * ui_ImageUpLoad;
extern lv_obj_t * ui_ImageDownLoad;
extern lv_obj_t * ui_LabelDownLoad;
extern lv_obj_t * ui_LabelUpLoad;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

