// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_LabelMacAddr = NULL;
lv_obj_t * ui_LabelIpAddr = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_LabelTitle = NULL;
lv_obj_t * ui_LabelStatus = NULL;
lv_obj_t * ui_ButtonConnect = NULL;
lv_obj_t * ui_LabelConnect = NULL;
lv_obj_t * ui_ImageUpLoad = NULL;
lv_obj_t * ui_ImageDownLoad = NULL;
lv_obj_t * ui_LabelDownLoad = NULL;
lv_obj_t * ui_LabelUpLoad = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelMacAddr = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelMacAddr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelMacAddr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelMacAddr, 0);
    lv_obj_set_y(ui_LabelMacAddr, 130);
    lv_obj_set_align(ui_LabelMacAddr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelMacAddr, "MAC:90:e5:b1:ae:cc:a8");
    lv_obj_set_style_text_color(ui_LabelMacAddr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelMacAddr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelMacAddr, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelIpAddr = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelIpAddr, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelIpAddr, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelIpAddr, 0);
    lv_obj_set_y(ui_LabelIpAddr, 100);
    lv_obj_set_align(ui_LabelIpAddr, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelIpAddr, "IP:192.168.1.1");
    lv_obj_set_style_text_color(ui_LabelIpAddr, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelIpAddr, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelIpAddr, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 100);
    lv_obj_set_height(ui_Panel2, 34);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -136);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x20242F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTitle, "Linux.NCM");
    lv_obj_set_style_text_color(ui_LabelTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelStatus = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelStatus, 0);
    lv_obj_set_y(ui_LabelStatus, -88);
    lv_obj_set_align(ui_LabelStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelStatus, "Offline");
    lv_obj_set_style_text_color(ui_LabelStatus, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelStatus, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonConnect = lv_button_create(ui_Screen1);
    lv_obj_set_width(ui_ButtonConnect, 190);
    lv_obj_set_height(ui_ButtonConnect, 70);
    lv_obj_set_x(ui_ButtonConnect, 0);
    lv_obj_set_y(ui_ButtonConnect, -20);
    lv_obj_set_align(ui_ButtonConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ButtonConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonConnect, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonConnect, lv_color_hex(0x517DFD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelConnect = lv_label_create(ui_ButtonConnect);
    lv_obj_set_width(ui_LabelConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelConnect, "Start NCM");
    lv_obj_set_style_text_color(ui_LabelConnect, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelConnect, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageUpLoad = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageUpLoad, &ui_img_upload_png);
    lv_obj_set_width(ui_ImageUpLoad, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageUpLoad, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageUpLoad, 47);
    lv_obj_set_y(ui_ImageUpLoad, 55);
    lv_obj_set_align(ui_ImageUpLoad, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageUpLoad, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageUpLoad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageUpLoad, 300);

    ui_ImageDownLoad = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageDownLoad, &ui_img_download_png);
    lv_obj_set_width(ui_ImageDownLoad, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_ImageDownLoad, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_ImageDownLoad, -126);
    lv_obj_set_y(ui_ImageDownLoad, 55);
    lv_obj_set_align(ui_ImageDownLoad, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageDownLoad, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageDownLoad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageDownLoad, 300);

    ui_LabelDownLoad = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelDownLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDownLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelDownLoad, -55);
    lv_obj_set_y(ui_LabelDownLoad, 55);
    lv_obj_set_align(ui_LabelDownLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDownLoad, "0.0 Mbps");
    lv_obj_set_style_text_color(ui_LabelDownLoad, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDownLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDownLoad, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUpLoad = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelUpLoad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUpLoad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUpLoad, 118);
    lv_obj_set_y(ui_LabelUpLoad, 55);
    lv_obj_set_align(ui_LabelUpLoad, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelUpLoad, "0.0 Mbps");
    lv_obj_set_style_text_color(ui_LabelUpLoad, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUpLoad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUpLoad, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_LabelMacAddr = NULL;
    ui_LabelIpAddr = NULL;
    ui_Panel2 = NULL;
    ui_LabelTitle = NULL;
    ui_LabelStatus = NULL;
    ui_ButtonConnect = NULL;
    ui_LabelConnect = NULL;
    ui_ImageUpLoad = NULL;
    ui_ImageDownLoad = NULL;
    ui_LabelDownLoad = NULL;
    ui_LabelUpLoad = NULL;

}
