/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_BOOT_FILES           1
#define MMAP_BOOT_CHECKSUM        0x862C

enum MMAP_BOOT_LISTS {
    MMAP_BOOT_ESP_BROOKESIA_SPEAKER_BOOT_ANIMATION_360_360_AAF = 0,        /*!< esp_brookesia_speaker_boot_animation_360_360.aaf */
};
