/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_EMOTION_FILES           6
#define MMAP_EMOTION_CHECKSUM        0x138F

enum MMAP_EMOTION_LISTS {
    MMAP_EMOTION_EMOTION_ANGRY_284_126_AAF = 0,        /*!< emotion_angry_284_126.aaf */
    MMAP_EMOTION_EMOTION_BLINK_FAST_284_126_AAF = 1,        /*!< emotion_blink_fast_284_126.aaf */
    MMAP_EMOTION_EMOTION_BLINK_SLOW_284_126_AAF = 2,        /*!< emotion_blink_slow_284_126.aaf */
    MMAP_EMOTION_EMOTION_HAPPY_284_126_AAF = 3,        /*!< emotion_happy_284_126.aaf */
    MMAP_EMOTION_EMOTION_SAD_284_126_AAF = 4,        /*!< emotion_sad_284_126.aaf */
    MMAP_EMOTION_EMOTION_SLEEP_284_126_AAF = 5,        /*!< emotion_sleep_284_126.aaf */
};
