// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: POS

#ifndef _POS_UI_H
#define _POS_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "esp_brookesia.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_POS_S1.h"
#include "screens/ui_Screen_POS_S2.h"
#include "screens/ui_Screen_POS_S3.h"
#include "screens/ui_Screen_POS_S4.h"
#include "screens/ui_Screen_POS_S5.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t *ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_app_pos_png);    // assets/img_app_pos.png
LV_IMG_DECLARE(ui_img_img_arrow_right_png);    // assets/IMG_arrow_right.png
LV_IMG_DECLARE(ui_img_img_btc_png);    // assets/IMG_BTC.png
LV_IMG_DECLARE(ui_img_img_card_png);    // assets/IMG_Card.png
LV_IMG_DECLARE(ui_img_img_qr_png);    // assets/IMG_QR.png
LV_IMG_DECLARE(ui_img_ok_png);    // assets/ok.png

// FONTS
LV_FONT_DECLARE(ui_font_Big_Number);
LV_FONT_DECLARE(ui_font_Bold_Font);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
