/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

/* Debug log */
#define BROOKESIA_SERVICE_NVS_LOG_TAG "SrvNVS"

#if !defined(BROOKESIA_SERVICE_NVS_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_SERVICE_NVS_ENABLE_DEBUG_LOG)
#       define BROOKESIA_SERVICE_NVS_ENABLE_DEBUG_LOG  CONFIG_BROOKESIA_SERVICE_NVS_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_SERVICE_NVS_ENABLE_DEBUG_LOG  (0)
#   endif
#endif

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/////////////////////////////////////////////////// Task Scheduler /////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
#if !defined(BROOKESIA_SERVICE_NVS_ENABLE_TASK_SCHEDULER)
#   if defined(CONFIG_BROOKESIA_SERVICE_NVS_ENABLE_TASK_SCHEDULER)
#       define BROOKESIA_SERVICE_NVS_ENABLE_TASK_SCHEDULER  CONFIG_BROOKESIA_SERVICE_NVS_ENABLE_TASK_SCHEDULER
#   else
#       define BROOKESIA_SERVICE_NVS_ENABLE_TASK_SCHEDULER  (0)
#   endif
#endif
#if BROOKESIA_SERVICE_NVS_ENABLE_TASK_SCHEDULER
#   if !defined(BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_NAME)
#      if defined(CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_NAME)
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_NAME  CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_NAME
#      else
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_NAME  "nvs_tsc_worker"
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_CORE_ID)
#      if defined(CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_CORE_ID)
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_CORE_ID  CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_CORE_ID
#      else
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_CORE_ID  (-1)
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_PRIORITY)
#      if defined(CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_PRIORITY)
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_PRIORITY  CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_PRIORITY
#      else
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_PRIORITY  (5)
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_STACK_SIZE)
#      if defined(CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_STACK_SIZE)
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_STACK_SIZE  CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_STACK_SIZE
#      else
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_STACK_SIZE  (5120)
#      endif
#   endif
#   if !defined(BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS)
#      if defined(CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS)
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS  CONFIG_BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS
#      else
#          define BROOKESIA_SERVICE_NVS_TASK_SCHEDULER_WORKER_POLL_INTERVAL_MS  (5)
#      endif
#   endif
#endif // BROOKESIA_SERVICE_NVS_ENABLE_TASK_SCHEDULER
