// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: quick_settings

#include "ui_comp_quicksettings.h"


// COMPONENT QuickSettings

lv_obj_t * ui_ContainerQuickSettings_create(lv_obj_t * comp_parent)
{
    lv_obj_t * cui_ContainerQuickSettings;
    cui_ContainerQuickSettings = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_ContainerQuickSettings);
    lv_obj_set_width(cui_ContainerQuickSettings, lv_pct(100));
    lv_obj_set_height(cui_ContainerQuickSettings, lv_pct(100));
    lv_obj_set_x(cui_ContainerQuickSettings, -1);
    lv_obj_set_y(cui_ContainerQuickSettings, 0);
    lv_obj_set_align(cui_ContainerQuickSettings, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(cui_ContainerQuickSettings, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerQuickSettings, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_ContainerQuickSettings, LV_OBJ_FLAG_SNAPPABLE);      /// Flags
    lv_obj_set_scroll_dir(cui_ContainerQuickSettings, LV_DIR_VER);
    lv_obj_set_style_bg_color(cui_ContainerQuickSettings, lv_color_hex(0x1A1A1A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerQuickSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(cui_ContainerQuickSettings, true, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_ContainerQuickSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ContainerQuickSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ContainerQuickSettings, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ContainerQuickSettings, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerStatus;
    cui_ContainerStatus = lv_obj_create(cui_ContainerQuickSettings);
    lv_obj_remove_style_all(cui_ContainerStatus);
    lv_obj_set_width(cui_ContainerStatus, lv_pct(100));
    lv_obj_set_height(cui_ContainerStatus, LV_SIZE_CONTENT);    /// 59
    lv_obj_set_x(cui_ContainerStatus, 1);
    lv_obj_set_y(cui_ContainerStatus, -1);
    lv_obj_set_align(cui_ContainerStatus, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_ContainerStatus, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_ContainerStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ContainerStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ContainerStatus, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ContainerStatus, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerStatusInternal;
    cui_ContainerStatusInternal = lv_obj_create(cui_ContainerStatus);
    lv_obj_remove_style_all(cui_ContainerStatusInternal);
    lv_obj_set_width(cui_ContainerStatusInternal, lv_pct(47));
    lv_obj_set_height(cui_ContainerStatusInternal, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_ContainerStatusInternal, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(cui_ContainerStatusInternal, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerStatusInternal, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_ContainerStatusInternal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ContainerStatusInternalTop;
    cui_ContainerStatusInternalTop = lv_obj_create(cui_ContainerStatusInternal);
    lv_obj_remove_style_all(cui_ContainerStatusInternalTop);
    lv_obj_set_width(cui_ContainerStatusInternalTop, lv_pct(97));
    lv_obj_set_height(cui_ContainerStatusInternalTop, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(cui_ContainerStatusInternalTop, -1);
    lv_obj_set_y(cui_ContainerStatusInternalTop, 0);
    lv_obj_set_align(cui_ContainerStatusInternalTop, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_ContainerStatusInternalTop, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelStatusInternalLeft;
    cui_LabelStatusInternalLeft = lv_label_create(cui_ContainerStatusInternalTop);
    lv_obj_set_width(cui_LabelStatusInternalLeft, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelStatusInternalLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_LabelStatusInternalLeft, -1);
    lv_obj_set_y(cui_LabelStatusInternalLeft, 0);
    lv_obj_set_align(cui_LabelStatusInternalLeft, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_LabelStatusInternalLeft, "12:00 AM");
    lv_obj_set_style_text_color(cui_LabelStatusInternalLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelStatusInternalLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelStatusInternalLeft, &ui_font_esp_brookesia_font_maison_neue_book_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerStatusInternalRight;
    cui_ContainerStatusInternalRight = lv_obj_create(cui_ContainerStatusInternalTop);
    lv_obj_remove_style_all(cui_ContainerStatusInternalRight);
    lv_obj_set_width(cui_ContainerStatusInternalRight, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_ContainerStatusInternalRight, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_ContainerStatusInternalRight, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(cui_ContainerStatusInternalRight, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_ContainerStatusInternalRight, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_ContainerStatusInternalRight, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_ContainerStatusInternalRight, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ContainerStatusInternalRight, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ImageStatusInternalRightWifi;
    cui_ImageStatusInternalRightWifi = lv_image_create(cui_ContainerStatusInternalRight);
    lv_image_set_src(cui_ImageStatusInternalRightWifi, &ui_img_speaker_image_middle_quick_settings_wifi_close_20_20_png);
    lv_obj_set_width(cui_ImageStatusInternalRightWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_ImageStatusInternalRightWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_ImageStatusInternalRightWifi, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_ImageStatusInternalRightWifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_ImageStatusInternalRightWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ImageStatusInternalRightBattery;
    cui_ImageStatusInternalRightBattery = lv_image_create(cui_ContainerStatusInternalRight);
    lv_image_set_src(cui_ImageStatusInternalRightBattery,
                     &ui_img_speaker_image_middle_quick_settings_battery_charge_20_20_png);
    lv_obj_set_width(cui_ImageStatusInternalRightBattery, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_ImageStatusInternalRightBattery, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_ImageStatusInternalRightBattery, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(cui_ImageStatusInternalRightBattery, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_ImageStatusInternalRightBattery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelStatusInternalRightBatteryPercent;
    cui_LabelStatusInternalRightBatteryPercent = lv_label_create(cui_ContainerStatusInternalRight);
    lv_obj_set_width(cui_LabelStatusInternalRightBatteryPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelStatusInternalRightBatteryPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelStatusInternalRightBatteryPercent, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelStatusInternalRightBatteryPercent, "100%");
    lv_obj_set_style_text_color(cui_LabelStatusInternalRightBatteryPercent, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelStatusInternalRightBatteryPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelStatusInternalRightBatteryPercent, &ui_font_esp_brookesia_font_maison_neue_book_12,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_LabelStatusInternalRightBatteryPercent, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_LabelStatusInternalRightBatteryPercent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_LabelStatusInternalRightBatteryPercent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_LabelStatusInternalRightBatteryPercent, -1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerStatusInternalBottom;
    cui_ContainerStatusInternalBottom = lv_obj_create(cui_ContainerStatusInternal);
    lv_obj_remove_style_all(cui_ContainerStatusInternalBottom);
    lv_obj_set_height(cui_ContainerStatusInternalBottom, 22);
    lv_obj_set_width(cui_ContainerStatusInternalBottom, lv_pct(100));
    lv_obj_set_align(cui_ContainerStatusInternalBottom, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerStatusInternalBottom, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_ContainerStatusInternalBottom, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(cui_ContainerStatusInternalBottom, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(cui_ContainerStatusInternalBottom, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelStatusInternalBottomLeft;
    cui_LabelStatusInternalBottomLeft = lv_label_create(cui_ContainerStatusInternalBottom);
    lv_obj_set_width(cui_LabelStatusInternalBottomLeft, LV_SIZE_CONTENT);   /// 60
    lv_obj_set_height(cui_LabelStatusInternalBottomLeft, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelStatusInternalBottomLeft, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelStatusInternalBottomLeft, "5/27");
    lv_obj_set_style_text_color(cui_LabelStatusInternalBottomLeft, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelStatusInternalBottomLeft, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelStatusInternalBottomLeft, &ui_font_esp_brookesia_font_maison_neue_book_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_LabelStatusInternalBottomRight;
    cui_LabelStatusInternalBottomRight = lv_label_create(cui_ContainerStatusInternalBottom);
    lv_obj_set_width(cui_LabelStatusInternalBottomRight, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(cui_LabelStatusInternalBottomRight, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelStatusInternalBottomRight, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelStatusInternalBottomRight, "Wednesday");
    lv_obj_set_style_text_color(cui_LabelStatusInternalBottomRight, lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelStatusInternalBottomRight, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelStatusInternalBottomRight, &ui_font_esp_brookesia_font_maison_neue_book_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerButtons;
    cui_ContainerButtons = lv_obj_create(cui_ContainerQuickSettings);
    lv_obj_remove_style_all(cui_ContainerButtons);
    lv_obj_set_width(cui_ContainerButtons, lv_pct(79));
    lv_obj_set_height(cui_ContainerButtons, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_ContainerButtons, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerButtons, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(cui_ContainerButtons, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_ContainerButtons, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_ContainerButtons, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ContainerButtons, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerButtonsWifi;
    cui_ContainerButtonsWifi = lv_obj_create(cui_ContainerButtons);
    lv_obj_remove_style_all(cui_ContainerButtonsWifi);
    lv_obj_set_width(cui_ContainerButtonsWifi, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_ContainerButtonsWifi, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(cui_ContainerButtonsWifi, -97);
    lv_obj_set_y(cui_ContainerButtonsWifi, 20);
    lv_obj_set_align(cui_ContainerButtonsWifi, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerButtonsWifi, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerButtonsWifi, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_ContainerButtonsWifi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_ContainerButtonsWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ContainerButtonsWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerButtonsWifiIcon;
    cui_ContainerButtonsWifiIcon = lv_obj_create(cui_ContainerButtonsWifi);
    lv_obj_remove_style_all(cui_ContainerButtonsWifiIcon);
    lv_obj_set_width(cui_ContainerButtonsWifiIcon, 80);
    lv_obj_set_height(cui_ContainerButtonsWifiIcon, 80);
    lv_obj_set_align(cui_ContainerButtonsWifiIcon, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(cui_ContainerButtonsWifiIcon, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(cui_ContainerButtonsWifiIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ContainerButtonsWifiIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerButtonsWifiIcon, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerButtonsWifiIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_ContainerButtonsWifiIcon, &ui_img_speaker_image_middle_quick_settings_wifi_48_48_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerButtonsWifiIcon, lv_color_hex(0xFF3034), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(cui_ContainerButtonsWifiIcon, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(cui_ContainerButtonsWifiIcon, lv_color_hex(0xFF3034), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ContainerButtonsWifiIcon, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_LabelButtonsWifiLabel;
    cui_LabelButtonsWifiLabel = lv_label_create(cui_ContainerButtonsWifi);
    lv_obj_set_width(cui_LabelButtonsWifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelButtonsWifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelButtonsWifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelButtonsWifiLabel, "Wi-Fi");
    lv_obj_set_style_text_color(cui_LabelButtonsWifiLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelButtonsWifiLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelButtonsWifiLabel, &ui_font_esp_brookesia_font_maison_neue_book_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_LabelButtonsWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_LabelButtonsWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_LabelButtonsWifiLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_LabelButtonsWifiLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerButtonsVolume;
    cui_ContainerButtonsVolume = lv_obj_create(cui_ContainerButtons);
    lv_obj_remove_style_all(cui_ContainerButtonsVolume);
    lv_obj_set_width(cui_ContainerButtonsVolume, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_ContainerButtonsVolume, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(cui_ContainerButtonsVolume, -97);
    lv_obj_set_y(cui_ContainerButtonsVolume, 20);
    lv_obj_set_align(cui_ContainerButtonsVolume, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerButtonsVolume, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerButtonsVolume, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_ContainerButtonsVolume, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_ContainerButtonsVolume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ContainerButtonsVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerButtonsVolumeIcon;
    cui_ContainerButtonsVolumeIcon = lv_obj_create(cui_ContainerButtonsVolume);
    lv_obj_remove_style_all(cui_ContainerButtonsVolumeIcon);
    lv_obj_set_width(cui_ContainerButtonsVolumeIcon, 80);
    lv_obj_set_height(cui_ContainerButtonsVolumeIcon, 80);
    lv_obj_set_align(cui_ContainerButtonsVolumeIcon, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_ContainerButtonsVolumeIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ContainerButtonsVolumeIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerButtonsVolumeIcon, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerButtonsVolumeIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_ContainerButtonsVolumeIcon,
                                  &ui_img_speaker_image_middle_quick_settings_volume_high_48_48_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerButtonsVolumeIcon, lv_color_hex(0xFF3034), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ContainerButtonsVolumeIcon, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_LabelButtonsVolumeLabel;
    cui_LabelButtonsVolumeLabel = lv_label_create(cui_ContainerButtonsVolume);
    lv_obj_set_width(cui_LabelButtonsVolumeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelButtonsVolumeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelButtonsVolumeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelButtonsVolumeLabel, "Volume");
    lv_obj_set_style_text_color(cui_LabelButtonsVolumeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelButtonsVolumeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelButtonsVolumeLabel, &ui_font_esp_brookesia_font_maison_neue_book_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_LabelButtonsVolumeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_LabelButtonsVolumeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_LabelButtonsVolumeLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_LabelButtonsVolumeLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerButtonsBrightness;
    cui_ContainerButtonsBrightness = lv_obj_create(cui_ContainerButtons);
    lv_obj_remove_style_all(cui_ContainerButtonsBrightness);
    lv_obj_set_width(cui_ContainerButtonsBrightness, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(cui_ContainerButtonsBrightness, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(cui_ContainerButtonsBrightness, -97);
    lv_obj_set_y(cui_ContainerButtonsBrightness, 20);
    lv_obj_set_align(cui_ContainerButtonsBrightness, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerButtonsBrightness, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerButtonsBrightness, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_ContainerButtonsBrightness, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(cui_ContainerButtonsBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ContainerButtonsBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerButtonsBrightnessIcon;
    cui_ContainerButtonsBrightnessIcon = lv_obj_create(cui_ContainerButtonsBrightness);
    lv_obj_remove_style_all(cui_ContainerButtonsBrightnessIcon);
    lv_obj_set_width(cui_ContainerButtonsBrightnessIcon, 80);
    lv_obj_set_height(cui_ContainerButtonsBrightnessIcon, 80);
    lv_obj_set_align(cui_ContainerButtonsBrightnessIcon, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(cui_ContainerButtonsBrightnessIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(cui_ContainerButtonsBrightnessIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerButtonsBrightnessIcon, lv_color_hex(0x38393A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ContainerButtonsBrightnessIcon, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(cui_ContainerButtonsBrightnessIcon,
                                  &ui_img_speaker_image_middle_quick_settings_brightness_high_48_48_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(cui_ContainerButtonsBrightnessIcon, lv_color_hex(0xFF3034), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(cui_ContainerButtonsBrightnessIcon, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    lv_obj_t * cui_LabelButtonsBrightnessLabel;
    cui_LabelButtonsBrightnessLabel = lv_label_create(cui_ContainerButtonsBrightness);
    lv_obj_set_width(cui_LabelButtonsBrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelButtonsBrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelButtonsBrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_LabelButtonsBrightnessLabel, "Brightness");
    lv_obj_set_style_text_color(cui_LabelButtonsBrightnessLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelButtonsBrightnessLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_LabelButtonsBrightnessLabel, &ui_font_esp_brookesia_font_maison_neue_book_16,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_LabelButtonsBrightnessLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_LabelButtonsBrightnessLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_LabelButtonsBrightnessLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_LabelButtonsBrightnessLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerMemory;
    cui_ContainerMemory = lv_obj_create(cui_ContainerQuickSettings);
    lv_obj_remove_style_all(cui_ContainerMemory);
    lv_obj_set_width(cui_ContainerMemory, lv_pct(100));
    lv_obj_set_height(cui_ContainerMemory, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_ContainerMemory, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerMemory, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerMemory, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_ContainerMemory, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(cui_ContainerMemory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_ContainerMemory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_ContainerMemory, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_ContainerMemory, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(cui_ContainerMemory, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(cui_ContainerMemory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_ContainerMemoryInternal;
    cui_ContainerMemoryInternal = lv_obj_create(cui_ContainerMemory);
    lv_obj_remove_style_all(cui_ContainerMemoryInternal);
    lv_obj_set_width(cui_ContainerMemoryInternal, 216);
    lv_obj_set_height(cui_ContainerMemoryInternal, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_ContainerMemoryInternal, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_ContainerMemoryInternal, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_ContainerMemoryInternal, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(cui_ContainerMemoryInternal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_ContainerMemoryInternalSram;
    cui_ContainerMemoryInternalSram = lv_obj_create(cui_ContainerMemoryInternal);
    lv_obj_remove_style_all(cui_ContainerMemoryInternalSram);
    lv_obj_set_width(cui_ContainerMemoryInternalSram, lv_pct(100));
    lv_obj_set_height(cui_ContainerMemoryInternalSram, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_ContainerMemoryInternalSram, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(cui_ContainerMemoryInternalSram, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelMemoryInternalSramLabel;
    cui_LabelMemoryInternalSramLabel = lv_label_create(cui_ContainerMemoryInternalSram);
    lv_obj_set_width(cui_LabelMemoryInternalSramLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelMemoryInternalSramLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelMemoryInternalSramLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_LabelMemoryInternalSramLabel, "  SRAM:");
    lv_obj_set_style_text_color(cui_LabelMemoryInternalSramLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelMemoryInternalSramLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BarMemoryInternalSramBar;
    cui_BarMemoryInternalSramBar = lv_bar_create(cui_ContainerMemoryInternalSram);
    lv_bar_set_value(cui_BarMemoryInternalSramBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_BarMemoryInternalSramBar, 0, LV_ANIM_OFF);
    lv_obj_set_height(cui_BarMemoryInternalSramBar, 10);
    lv_obj_set_width(cui_BarMemoryInternalSramBar, lv_pct(70));
    lv_obj_set_align(cui_BarMemoryInternalSramBar, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_bg_color(cui_BarMemoryInternalSramBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BarMemoryInternalSramBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_BarMemoryInternalSramBar, lv_color_hex(0xFF0000),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_BarMemoryInternalSramBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_BarMemoryInternalSramBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_BarMemoryInternalSramBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_BarMemoryInternalSramBar,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_BarMemoryInternalSramBar,
                                                                                  lv_obj_get_style_pad_right(cui_BarMemoryInternalSramBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t * cui_ContainerMemoryInternalPsram;
    cui_ContainerMemoryInternalPsram = lv_obj_create(cui_ContainerMemoryInternal);
    lv_obj_remove_style_all(cui_ContainerMemoryInternalPsram);
    lv_obj_set_width(cui_ContainerMemoryInternalPsram, lv_pct(100));
    lv_obj_set_height(cui_ContainerMemoryInternalPsram, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(cui_ContainerMemoryInternalPsram, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_ContainerMemoryInternalPsram, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_LabelMemoryInternalPsramLabel;
    cui_LabelMemoryInternalPsramLabel = lv_label_create(cui_ContainerMemoryInternalPsram);
    lv_obj_set_width(cui_LabelMemoryInternalPsramLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_LabelMemoryInternalPsramLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_LabelMemoryInternalPsramLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_LabelMemoryInternalPsramLabel, "PSRAM:");
    lv_obj_set_style_text_color(cui_LabelMemoryInternalPsramLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_LabelMemoryInternalPsramLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_BarMemoryInternalPsramBar;
    cui_BarMemoryInternalPsramBar = lv_bar_create(cui_ContainerMemoryInternalPsram);
    lv_bar_set_value(cui_BarMemoryInternalPsramBar, 50, LV_ANIM_OFF);
    lv_bar_set_start_value(cui_BarMemoryInternalPsramBar, 0, LV_ANIM_OFF);
    lv_obj_set_height(cui_BarMemoryInternalPsramBar, 10);
    lv_obj_set_width(cui_BarMemoryInternalPsramBar, lv_pct(70));
    lv_obj_set_align(cui_BarMemoryInternalPsramBar, LV_ALIGN_RIGHT_MID);

    lv_obj_set_style_bg_color(cui_BarMemoryInternalPsramBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_BarMemoryInternalPsramBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(cui_BarMemoryInternalPsramBar, lv_color_hex(0xFF0000),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(cui_BarMemoryInternalPsramBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(cui_BarMemoryInternalPsramBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(cui_BarMemoryInternalPsramBar, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(cui_BarMemoryInternalPsramBar,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(cui_BarMemoryInternalPsramBar,
                                                                                  lv_obj_get_style_pad_right(cui_BarMemoryInternalPsramBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_CONTAINERQUICKSETTINGS_NUM);
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERQUICKSETTINGS] = cui_ContainerQuickSettings;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS] = cui_ContainerStatus;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL] = cui_ContainerStatusInternal;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALTOP] =
        cui_ContainerStatusInternalTop;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALTOP_LABELSTATUSINTERNALLEFT]
        = cui_LabelStatusInternalLeft;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALTOP_CONTAINERSTATUSINTERNALRIGHT]
        = cui_ContainerStatusInternalRight;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALTOP_CONTAINERSTATUSINTERNALRIGHT_IMAGESTATUSINTERNALRIGHTWIFI]
        = cui_ImageStatusInternalRightWifi;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALTOP_CONTAINERSTATUSINTERNALRIGHT_IMAGESTATUSINTERNALRIGHTBATTERY]
        = cui_ImageStatusInternalRightBattery;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALTOP_CONTAINERSTATUSINTERNALRIGHT_LABELSTATUSINTERNALRIGHTBATTERYPERCENT]
        = cui_LabelStatusInternalRightBatteryPercent;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALBOTTOM] =
        cui_ContainerStatusInternalBottom;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALBOTTOM_LABELSTATUSINTERNALBOTTOMLEFT]
        = cui_LabelStatusInternalBottomLeft;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERSTATUS_CONTAINERSTATUSINTERNAL_CONTAINERSTATUSINTERNALBOTTOM_LABELSTATUSINTERNALBOTTOMRIGHT]
        = cui_LabelStatusInternalBottomRight;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS] = cui_ContainerButtons;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSWIFI] = cui_ContainerButtonsWifi;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSWIFI_CONTAINERBUTTONSWIFIICON] =
        cui_ContainerButtonsWifiIcon;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSWIFI_LABELBUTTONSWIFILABEL] =
        cui_LabelButtonsWifiLabel;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSVOLUME] = cui_ContainerButtonsVolume;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSVOLUME_CONTAINERBUTTONSVOLUMEICON] =
        cui_ContainerButtonsVolumeIcon;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSVOLUME_LABELBUTTONSVOLUMELABEL] =
        cui_LabelButtonsVolumeLabel;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSBRIGHTNESS] = cui_ContainerButtonsBrightness;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSBRIGHTNESS_CONTAINERBUTTONSBRIGHTNESSICON] =
        cui_ContainerButtonsBrightnessIcon;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERBUTTONS_CONTAINERBUTTONSBRIGHTNESS_LABELBUTTONSBRIGHTNESSLABEL] =
        cui_LabelButtonsBrightnessLabel;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY] = cui_ContainerMemory;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY_CONTAINERMEMORYINTERNAL] = cui_ContainerMemoryInternal;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY_CONTAINERMEMORYINTERNAL_CONTAINERMEMORYINTERNALSRAM] =
        cui_ContainerMemoryInternalSram;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY_CONTAINERMEMORYINTERNAL_CONTAINERMEMORYINTERNALSRAM_LABELMEMORYINTERNALSRAMLABEL]
        = cui_LabelMemoryInternalSramLabel;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY_CONTAINERMEMORYINTERNAL_CONTAINERMEMORYINTERNALSRAM_BARMEMORYINTERNALSRAMBAR]
        = cui_BarMemoryInternalSramBar;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY_CONTAINERMEMORYINTERNAL_CONTAINERMEMORYINTERNALPSRAM] =
        cui_ContainerMemoryInternalPsram;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY_CONTAINERMEMORYINTERNAL_CONTAINERMEMORYINTERNALPSRAM_LABELMEMORYINTERNALPSRAMLABEL]
        = cui_LabelMemoryInternalPsramLabel;
    children[UI_COMP_CONTAINERQUICKSETTINGS_CONTAINERMEMORY_CONTAINERMEMORYINTERNAL_CONTAINERMEMORYINTERNALPSRAM_BARMEMORYINTERNALPSRAMBAR]
        = cui_BarMemoryInternalPsramBar;
    lv_obj_add_event_cb(cui_ContainerQuickSettings, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ContainerQuickSettings, del_component_child_event_cb, LV_EVENT_DELETE, children);
    // ui_comp_ContainerQuickSettings_create_hook(cui_ContainerQuickSettings);
    return cui_ContainerQuickSettings;
}

