// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: chatbot

#include "../ui.h"

lv_obj_t * uic_SettingsDropdownAgents;
lv_obj_t * uic_SettingsLabelVolumeIncText;
lv_obj_t * uic_SettingsButtonVolumeInc;
lv_obj_t * uic_SettingsLabelVolumeText;
lv_obj_t * uic_SettingsLabelVolumeDecText;
lv_obj_t * uic_SettingsButtonVolumeDec;
lv_obj_t * uic_SettingsContainerVolumeContent;
lv_obj_t * uic_SettingsLabelVolumeTitle;
lv_obj_t * uic_SettingsPanelVolume;
lv_obj_t * uic_SettingsButtonBrightnessInc;
lv_obj_t * uic_SettingsLabelBrightnessText;
lv_obj_t * uic_SettingsLabelBrightnessDecText;
lv_obj_t * uic_SettingsButtonBrightnessDec;
lv_obj_t * uic_SettingsContainerBrightnessContent;
lv_obj_t * uic_SettingsPanelBrightness;
lv_obj_t * uic_WifiSsidText;
lv_obj_t * uic_SettingsContainerWifiContent;
lv_obj_t * uic_SettingsLabelTitle;
lv_obj_t * uic_SettingsPanelWifi;
lv_obj_t * uic_ScreenSettings;
lv_obj_t * ui_ScreenSettings = NULL;
lv_obj_t * ui_SettingsPanelMain = NULL;
lv_obj_t * ui_SettingsPanelWifi = NULL;
lv_obj_t * ui_SettingsLabelWifiTitle = NULL;
lv_obj_t * ui_SettingsContainerWifiContent = NULL;
lv_obj_t * ui_SettingsLabelWifiSsidText = NULL;
lv_obj_t * ui_SettingsPanelBrightness = NULL;
lv_obj_t * ui_SettingsLabelBrightnessTitle = NULL;
lv_obj_t * ui_SettingsContainerBrightnessContent = NULL;
lv_obj_t * ui_SettingsButtonBrightnessDec = NULL;
lv_obj_t * ui_SettingsLabelBrightnessDecText = NULL;
lv_obj_t * ui_SettingsLabelBrightnessText = NULL;
lv_obj_t * ui_SettingsButtonBrightnessInc = NULL;
lv_obj_t * ui_SettingsLabelBrightnessIncText = NULL;
lv_obj_t * ui_SettingsPanelVolume = NULL;
lv_obj_t * ui_SettingsLabelVolumeTitle = NULL;
lv_obj_t * ui_SettingsContainerVolumeContent = NULL;
lv_obj_t * ui_SettingsButtonVolumeDec = NULL;
lv_obj_t * ui_SettingsLabelVolumeDecText = NULL;
lv_obj_t * ui_SettingsLabelVolumeText = NULL;
lv_obj_t * ui_SettingsButtonVolumeInc = NULL;
lv_obj_t * ui_SettingsLabelVolumeIncText = NULL;
lv_obj_t * ui_SettingsPanelAgent = NULL;
lv_obj_t * ui_SettingsLabelAgentTitle = NULL;
lv_obj_t * ui_SettingsContainerAgentContent = NULL;
lv_obj_t * ui_SettingsDropdownAgents = NULL;
lv_obj_t * ui_SettingsPanelReset = NULL;
lv_obj_t * ui_SettingsButtonResetBtn = NULL;
lv_obj_t * ui_SettingsLabelResetBtnText = NULL;
// event funtions

// build funtions

void ui_ScreenSettings_screen_init(void)
{
    ui_ScreenSettings = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ScreenSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSettings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSettings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPanelMain = lv_obj_create(ui_ScreenSettings);
    lv_obj_set_width(ui_SettingsPanelMain, 240);
    lv_obj_set_height(ui_SettingsPanelMain, 240);
    lv_obj_set_align(ui_SettingsPanelMain, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsPanelMain, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsPanelMain, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_pad_left(ui_SettingsPanelMain, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsPanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsPanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsPanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsPanelMain, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsPanelMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPanelWifi = lv_obj_create(ui_SettingsPanelMain);
    lv_obj_set_height(ui_SettingsPanelWifi, 50);
    lv_obj_set_width(ui_SettingsPanelWifi, lv_pct(100));
    lv_obj_set_align(ui_SettingsPanelWifi, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsPanelWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingsPanelWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsPanelWifi, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsPanelWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsPanelWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsPanelWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsPanelWifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelWifiTitle = lv_label_create(ui_SettingsPanelWifi);
    lv_obj_set_width(ui_SettingsLabelWifiTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelWifiTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelWifiTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SettingsLabelWifiTitle, "WiFi: ");

    ui_SettingsContainerWifiContent = lv_obj_create(ui_SettingsPanelWifi);
    lv_obj_remove_style_all(ui_SettingsContainerWifiContent);
    lv_obj_set_width(ui_SettingsContainerWifiContent, lv_pct(80));
    lv_obj_set_height(ui_SettingsContainerWifiContent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsContainerWifiContent, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_SettingsContainerWifiContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsLabelWifiSsidText = lv_label_create(ui_SettingsContainerWifiContent);
    lv_obj_set_width(ui_SettingsLabelWifiSsidText, lv_pct(100));
    lv_obj_set_height(ui_SettingsLabelWifiSsidText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelWifiSsidText, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SettingsLabelWifiSsidText, LV_LABEL_LONG_MODE_SCROLL_CIRCULAR);
    lv_label_set_text(ui_SettingsLabelWifiSsidText, "");
    lv_obj_set_style_text_align(ui_SettingsLabelWifiSsidText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPanelBrightness = lv_obj_create(ui_SettingsPanelMain);
    lv_obj_set_height(ui_SettingsPanelBrightness, 60);
    lv_obj_set_width(ui_SettingsPanelBrightness, lv_pct(100));
    lv_obj_set_align(ui_SettingsPanelBrightness, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsPanelBrightness, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingsPanelBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsPanelBrightness, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsPanelBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsPanelBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsPanelBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsPanelBrightness, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelBrightnessTitle = lv_label_create(ui_SettingsPanelBrightness);
    lv_obj_set_width(ui_SettingsLabelBrightnessTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelBrightnessTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelBrightnessTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SettingsLabelBrightnessTitle, "Brightness:");

    ui_SettingsContainerBrightnessContent = lv_obj_create(ui_SettingsPanelBrightness);
    lv_obj_remove_style_all(ui_SettingsContainerBrightnessContent);
    lv_obj_set_width(ui_SettingsContainerBrightnessContent, lv_pct(60));
    lv_obj_set_height(ui_SettingsContainerBrightnessContent, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_SettingsContainerBrightnessContent, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_SettingsContainerBrightnessContent, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsContainerBrightnessContent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsContainerBrightnessContent,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_SettingsContainerBrightnessContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsContainerBrightnessContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonBrightnessDec = lv_button_create(ui_SettingsContainerBrightnessContent);
    lv_obj_set_width(ui_SettingsButtonBrightnessDec, 40);
    lv_obj_set_height(ui_SettingsButtonBrightnessDec, 40);
    lv_obj_set_align(ui_SettingsButtonBrightnessDec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonBrightnessDec, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonBrightnessDec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButtonBrightnessDec, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SettingsButtonBrightnessDec, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SettingsLabelBrightnessDecText = lv_label_create(ui_SettingsButtonBrightnessDec);
    lv_obj_set_width(ui_SettingsLabelBrightnessDecText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelBrightnessDecText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelBrightnessDecText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelBrightnessDecText, "-");
    lv_obj_set_style_text_font(ui_SettingsLabelBrightnessDecText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelBrightnessText = lv_label_create(ui_SettingsContainerBrightnessContent);
    lv_obj_set_width(ui_SettingsLabelBrightnessText, 30);
    lv_obj_set_height(ui_SettingsLabelBrightnessText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelBrightnessText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelBrightnessText, "100");
    lv_obj_set_style_text_align(ui_SettingsLabelBrightnessText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonBrightnessInc = lv_button_create(ui_SettingsContainerBrightnessContent);
    lv_obj_set_width(ui_SettingsButtonBrightnessInc, 40);
    lv_obj_set_height(ui_SettingsButtonBrightnessInc, 40);
    lv_obj_set_align(ui_SettingsButtonBrightnessInc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonBrightnessInc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonBrightnessInc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButtonBrightnessInc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SettingsButtonBrightnessInc, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SettingsLabelBrightnessIncText = lv_label_create(ui_SettingsButtonBrightnessInc);
    lv_obj_set_width(ui_SettingsLabelBrightnessIncText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelBrightnessIncText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelBrightnessIncText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelBrightnessIncText, "+");
    lv_obj_set_style_text_font(ui_SettingsLabelBrightnessIncText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPanelVolume = lv_obj_create(ui_SettingsPanelMain);
    lv_obj_set_height(ui_SettingsPanelVolume, 60);
    lv_obj_set_width(ui_SettingsPanelVolume, lv_pct(100));
    lv_obj_set_align(ui_SettingsPanelVolume, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsPanelVolume, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingsPanelVolume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsPanelVolume, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsPanelVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsPanelVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsPanelVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsPanelVolume, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelVolumeTitle = lv_label_create(ui_SettingsPanelVolume);
    lv_obj_set_width(ui_SettingsLabelVolumeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelVolumeTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelVolumeTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SettingsLabelVolumeTitle, "Volume:");

    ui_SettingsContainerVolumeContent = lv_obj_create(ui_SettingsPanelVolume);
    lv_obj_remove_style_all(ui_SettingsContainerVolumeContent);
    lv_obj_set_width(ui_SettingsContainerVolumeContent, lv_pct(60));
    lv_obj_set_height(ui_SettingsContainerVolumeContent, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_SettingsContainerVolumeContent, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_SettingsContainerVolumeContent, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsContainerVolumeContent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsContainerVolumeContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_SettingsContainerVolumeContent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsContainerVolumeContent, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonVolumeDec = lv_button_create(ui_SettingsContainerVolumeContent);
    lv_obj_set_width(ui_SettingsButtonVolumeDec, 40);
    lv_obj_set_height(ui_SettingsButtonVolumeDec, 40);
    lv_obj_set_align(ui_SettingsButtonVolumeDec, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonVolumeDec, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonVolumeDec, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButtonVolumeDec, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SettingsButtonVolumeDec, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SettingsLabelVolumeDecText = lv_label_create(ui_SettingsButtonVolumeDec);
    lv_obj_set_width(ui_SettingsLabelVolumeDecText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelVolumeDecText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelVolumeDecText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelVolumeDecText, "-");
    lv_obj_set_style_text_font(ui_SettingsLabelVolumeDecText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelVolumeText = lv_label_create(ui_SettingsContainerVolumeContent);
    lv_obj_set_width(ui_SettingsLabelVolumeText, 30);
    lv_obj_set_height(ui_SettingsLabelVolumeText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelVolumeText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelVolumeText, "100");
    lv_obj_set_style_text_align(ui_SettingsLabelVolumeText, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonVolumeInc = lv_button_create(ui_SettingsContainerVolumeContent);
    lv_obj_set_width(ui_SettingsButtonVolumeInc, 40);
    lv_obj_set_height(ui_SettingsButtonVolumeInc, 40);
    lv_obj_set_align(ui_SettingsButtonVolumeInc, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonVolumeInc, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonVolumeInc, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SettingsButtonVolumeInc, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_SettingsButtonVolumeInc, 255, LV_PART_MAIN | LV_STATE_DISABLED);

    ui_SettingsLabelVolumeIncText = lv_label_create(ui_SettingsButtonVolumeInc);
    lv_obj_set_width(ui_SettingsLabelVolumeIncText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelVolumeIncText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelVolumeIncText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelVolumeIncText, "+");
    lv_obj_set_style_text_font(ui_SettingsLabelVolumeIncText, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsPanelAgent = lv_obj_create(ui_SettingsPanelMain);
    lv_obj_set_height(ui_SettingsPanelAgent, 60);
    lv_obj_set_width(ui_SettingsPanelAgent, lv_pct(100));
    lv_obj_set_align(ui_SettingsPanelAgent, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsPanelAgent, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingsPanelAgent, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsPanelAgent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsPanelAgent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsPanelAgent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsPanelAgent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsPanelAgent, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsLabelAgentTitle = lv_label_create(ui_SettingsPanelAgent);
    lv_obj_set_width(ui_SettingsLabelAgentTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelAgentTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelAgentTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_SettingsLabelAgentTitle, "Agents:");

    ui_SettingsContainerAgentContent = lv_obj_create(ui_SettingsPanelAgent);
    lv_obj_remove_style_all(ui_SettingsContainerAgentContent);
    lv_obj_set_width(ui_SettingsContainerAgentContent, lv_pct(80));
    lv_obj_set_height(ui_SettingsContainerAgentContent, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_SettingsContainerAgentContent, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_SettingsContainerAgentContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsDropdownAgents = lv_dropdown_create(ui_SettingsContainerAgentContent);
    lv_obj_set_width(ui_SettingsDropdownAgents, lv_pct(70));
    lv_obj_set_height(ui_SettingsDropdownAgents, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsDropdownAgents, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsDropdownAgents, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SettingsPanelReset = lv_obj_create(ui_SettingsPanelMain);
    lv_obj_set_height(ui_SettingsPanelReset, 60);
    lv_obj_set_width(ui_SettingsPanelReset, lv_pct(100));
    lv_obj_set_align(ui_SettingsPanelReset, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SettingsPanelReset, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingsPanelReset, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsPanelReset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsPanelReset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsPanelReset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsPanelReset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsPanelReset, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsButtonResetBtn = lv_button_create(ui_SettingsPanelReset);
    lv_obj_set_height(ui_SettingsButtonResetBtn, 35);
    lv_obj_set_width(ui_SettingsButtonResetBtn, lv_pct(50));
    lv_obj_set_align(ui_SettingsButtonResetBtn, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButtonResetBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SettingsButtonResetBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsLabelResetBtnText = lv_label_create(ui_SettingsButtonResetBtn);
    lv_obj_set_width(ui_SettingsLabelResetBtnText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabelResetBtnText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsLabelResetBtnText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabelResetBtnText, "Factory Reset");

    uic_ScreenSettings = ui_ScreenSettings;
    uic_SettingsPanelWifi = ui_SettingsPanelWifi;
    uic_SettingsLabelTitle = ui_SettingsLabelWifiTitle;
    uic_SettingsContainerWifiContent = ui_SettingsContainerWifiContent;
    uic_WifiSsidText = ui_SettingsLabelWifiSsidText;
    uic_SettingsPanelBrightness = ui_SettingsPanelBrightness;
    uic_SettingsContainerBrightnessContent = ui_SettingsContainerBrightnessContent;
    uic_SettingsButtonBrightnessDec = ui_SettingsButtonBrightnessDec;
    uic_SettingsLabelBrightnessDecText = ui_SettingsLabelBrightnessDecText;
    uic_SettingsLabelBrightnessText = ui_SettingsLabelBrightnessText;
    uic_SettingsButtonBrightnessInc = ui_SettingsButtonBrightnessInc;
    uic_SettingsPanelVolume = ui_SettingsPanelVolume;
    uic_SettingsLabelVolumeTitle = ui_SettingsLabelVolumeTitle;
    uic_SettingsContainerVolumeContent = ui_SettingsContainerVolumeContent;
    uic_SettingsButtonVolumeDec = ui_SettingsButtonVolumeDec;
    uic_SettingsLabelVolumeDecText = ui_SettingsLabelVolumeDecText;
    uic_SettingsLabelVolumeText = ui_SettingsLabelVolumeText;
    uic_SettingsButtonVolumeInc = ui_SettingsButtonVolumeInc;
    uic_SettingsLabelVolumeIncText = ui_SettingsLabelVolumeIncText;
    uic_SettingsDropdownAgents = ui_SettingsDropdownAgents;

}

void ui_ScreenSettings_screen_destroy(void)
{
    if(ui_ScreenSettings) lv_obj_del(ui_ScreenSettings);

    // NULL screen variables
    uic_ScreenSettings = NULL;
    ui_ScreenSettings = NULL;
    ui_SettingsPanelMain = NULL;
    uic_SettingsPanelWifi = NULL;
    ui_SettingsPanelWifi = NULL;
    uic_SettingsLabelTitle = NULL;
    ui_SettingsLabelWifiTitle = NULL;
    uic_SettingsContainerWifiContent = NULL;
    ui_SettingsContainerWifiContent = NULL;
    uic_WifiSsidText = NULL;
    ui_SettingsLabelWifiSsidText = NULL;
    uic_SettingsPanelBrightness = NULL;
    ui_SettingsPanelBrightness = NULL;
    ui_SettingsLabelBrightnessTitle = NULL;
    uic_SettingsContainerBrightnessContent = NULL;
    ui_SettingsContainerBrightnessContent = NULL;
    uic_SettingsButtonBrightnessDec = NULL;
    ui_SettingsButtonBrightnessDec = NULL;
    uic_SettingsLabelBrightnessDecText = NULL;
    ui_SettingsLabelBrightnessDecText = NULL;
    uic_SettingsLabelBrightnessText = NULL;
    ui_SettingsLabelBrightnessText = NULL;
    uic_SettingsButtonBrightnessInc = NULL;
    ui_SettingsButtonBrightnessInc = NULL;
    ui_SettingsLabelBrightnessIncText = NULL;
    uic_SettingsPanelVolume = NULL;
    ui_SettingsPanelVolume = NULL;
    uic_SettingsLabelVolumeTitle = NULL;
    ui_SettingsLabelVolumeTitle = NULL;
    uic_SettingsContainerVolumeContent = NULL;
    ui_SettingsContainerVolumeContent = NULL;
    uic_SettingsButtonVolumeDec = NULL;
    ui_SettingsButtonVolumeDec = NULL;
    uic_SettingsLabelVolumeDecText = NULL;
    ui_SettingsLabelVolumeDecText = NULL;
    uic_SettingsLabelVolumeText = NULL;
    ui_SettingsLabelVolumeText = NULL;
    uic_SettingsButtonVolumeInc = NULL;
    ui_SettingsButtonVolumeInc = NULL;
    uic_SettingsLabelVolumeIncText = NULL;
    ui_SettingsLabelVolumeIncText = NULL;
    ui_SettingsPanelAgent = NULL;
    ui_SettingsLabelAgentTitle = NULL;
    ui_SettingsContainerAgentContent = NULL;
    uic_SettingsDropdownAgents = NULL;
    ui_SettingsDropdownAgents = NULL;
    ui_SettingsPanelReset = NULL;
    ui_SettingsButtonResetBtn = NULL;
    ui_SettingsLabelResetBtnText = NULL;

}
