// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: chatbot

#ifndef UI_SCREENSETTINGS_H
#define UI_SCREENSETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSettings
extern void ui_ScreenSettings_screen_init(void);
extern void ui_ScreenSettings_screen_destroy(void);
extern lv_obj_t * ui_ScreenSettings;
extern lv_obj_t * ui_SettingsPanelMain;
extern lv_obj_t * ui_SettingsPanelWifi;
extern lv_obj_t * ui_SettingsLabelWifiTitle;
extern lv_obj_t * ui_SettingsContainerWifiContent;
extern lv_obj_t * ui_SettingsLabelWifiSsidText;
extern lv_obj_t * ui_SettingsPanelBrightness;
extern lv_obj_t * ui_SettingsLabelBrightnessTitle;
extern lv_obj_t * ui_SettingsContainerBrightnessContent;
extern lv_obj_t * ui_SettingsButtonBrightnessDec;
extern lv_obj_t * ui_SettingsLabelBrightnessDecText;
extern lv_obj_t * ui_SettingsLabelBrightnessText;
extern lv_obj_t * ui_SettingsButtonBrightnessInc;
extern lv_obj_t * ui_SettingsLabelBrightnessIncText;
extern lv_obj_t * ui_SettingsPanelVolume;
extern lv_obj_t * ui_SettingsLabelVolumeTitle;
extern lv_obj_t * ui_SettingsContainerVolumeContent;
extern lv_obj_t * ui_SettingsButtonVolumeDec;
extern lv_obj_t * ui_SettingsLabelVolumeDecText;
extern lv_obj_t * ui_SettingsLabelVolumeText;
extern lv_obj_t * ui_SettingsButtonVolumeInc;
extern lv_obj_t * ui_SettingsLabelVolumeIncText;
extern lv_obj_t * ui_SettingsPanelAgent;
extern lv_obj_t * ui_SettingsLabelAgentTitle;
extern lv_obj_t * ui_SettingsContainerAgentContent;
extern lv_obj_t * ui_SettingsDropdownAgents;
extern lv_obj_t * ui_SettingsPanelReset;
extern lv_obj_t * ui_SettingsButtonResetBtn;
extern lv_obj_t * ui_SettingsLabelResetBtnText;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenSettings;
extern lv_obj_t * uic_SettingsPanelWifi;
extern lv_obj_t * uic_SettingsLabelTitle;
extern lv_obj_t * uic_SettingsContainerWifiContent;
extern lv_obj_t * uic_WifiSsidText;
extern lv_obj_t * uic_SettingsPanelBrightness;
extern lv_obj_t * uic_SettingsContainerBrightnessContent;
extern lv_obj_t * uic_SettingsButtonBrightnessDec;
extern lv_obj_t * uic_SettingsLabelBrightnessDecText;
extern lv_obj_t * uic_SettingsLabelBrightnessText;
extern lv_obj_t * uic_SettingsButtonBrightnessInc;
extern lv_obj_t * uic_SettingsPanelVolume;
extern lv_obj_t * uic_SettingsLabelVolumeTitle;
extern lv_obj_t * uic_SettingsContainerVolumeContent;
extern lv_obj_t * uic_SettingsButtonVolumeDec;
extern lv_obj_t * uic_SettingsLabelVolumeDecText;
extern lv_obj_t * uic_SettingsLabelVolumeText;
extern lv_obj_t * uic_SettingsButtonVolumeInc;
extern lv_obj_t * uic_SettingsLabelVolumeIncText;
extern lv_obj_t * uic_SettingsDropdownAgents;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

