/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#define BROOKESIA_HAL_WASM_LOG_TAG "HalWasm"

#ifndef BROOKESIA_HAL_WASM_ENABLE_SYSTEM_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_SYSTEM_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_SYSTEM_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_SYSTEM_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_SYSTEM_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_ENABLE_NETWORK_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_NETWORK_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_NETWORK_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_NETWORK_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_NETWORK_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_ENABLE_AUDIO_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_AUDIO_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_AUDIO_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_AUDIO_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_AUDIO_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_ENABLE_VIDEO_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_VIDEO_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_VIDEO_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_VIDEO_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_VIDEO_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_ENABLE_DISPLAY_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_DISPLAY_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_DISPLAY_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_DISPLAY_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_DISPLAY_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_ENABLE_POWER_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_POWER_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_POWER_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_POWER_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_POWER_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_ENABLE_STORAGE_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_STORAGE_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_STORAGE_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_STORAGE_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_STORAGE_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_ENABLE_WIFI_DEVICE
#   ifdef CONFIG_BROOKESIA_HAL_WASM_ENABLE_WIFI_DEVICE
#       define BROOKESIA_HAL_WASM_ENABLE_WIFI_DEVICE CONFIG_BROOKESIA_HAL_WASM_ENABLE_WIFI_DEVICE
#   else
#       define BROOKESIA_HAL_WASM_ENABLE_WIFI_DEVICE (1)
#   endif
#endif

#ifndef BROOKESIA_HAL_WASM_SYSTEM_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_SYSTEM_DEVICE_PLUGIN_SYMBOL system_wasm_device_symbol
#endif
#ifndef BROOKESIA_HAL_WASM_NETWORK_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_NETWORK_DEVICE_PLUGIN_SYMBOL network_wasm_device_symbol
#endif
#ifndef BROOKESIA_HAL_WASM_AUDIO_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_AUDIO_DEVICE_PLUGIN_SYMBOL audio_wasm_device_symbol
#endif
#ifndef BROOKESIA_HAL_WASM_VIDEO_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_VIDEO_DEVICE_PLUGIN_SYMBOL video_wasm_device_symbol
#endif
#ifndef BROOKESIA_HAL_WASM_DISPLAY_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_DISPLAY_DEVICE_PLUGIN_SYMBOL display_wasm_device_symbol
#endif
#ifndef BROOKESIA_HAL_WASM_POWER_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_POWER_DEVICE_PLUGIN_SYMBOL power_wasm_device_symbol
#endif
#ifndef BROOKESIA_HAL_WASM_STORAGE_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_STORAGE_DEVICE_PLUGIN_SYMBOL storage_wasm_device_symbol
#endif
#ifndef BROOKESIA_HAL_WASM_WIFI_DEVICE_PLUGIN_SYMBOL
#   define BROOKESIA_HAL_WASM_WIFI_DEVICE_PLUGIN_SYMBOL wifi_wasm_device_symbol
#endif
