/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#include "brookesia/system_core/macro_configs.h"

#if !defined(BROOKESIA_APP_SETTINGS_RESOURCE_DIR)
#   define BROOKESIA_APP_SETTINGS_RESOURCE_DIR "brookesia.general.settings"
#endif

#if !defined(BROOKESIA_APP_SETTINGS_PACKAGE_DIR)
#   define BROOKESIA_APP_SETTINGS_PACKAGE_DIR ""
#endif

#if !defined(BROOKESIA_APP_SETTINGS_WIFI_MAX_VISIBLE_APS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_WIFI_MAX_VISIBLE_APS)
#       define BROOKESIA_APP_SETTINGS_WIFI_MAX_VISIBLE_APS CONFIG_BROOKESIA_APP_SETTINGS_WIFI_MAX_VISIBLE_APS
#   else
#       define BROOKESIA_APP_SETTINGS_WIFI_MAX_VISIBLE_APS (5)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_ENABLE_PRELOAD_DOM)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_ENABLE_PRELOAD_DOM)
#       define BROOKESIA_APP_SETTINGS_ENABLE_PRELOAD_DOM CONFIG_BROOKESIA_APP_SETTINGS_ENABLE_PRELOAD_DOM
#   elif defined(ESP_PLATFORM)
#       define BROOKESIA_APP_SETTINGS_ENABLE_PRELOAD_DOM (0)
#   else
#       define BROOKESIA_APP_SETTINGS_ENABLE_PRELOAD_DOM (1)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_LOG_TAG)
#   define BROOKESIA_APP_SETTINGS_LOG_TAG "AppSettings"
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MIN_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MIN_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MIN_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MIN_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MIN_MS (500)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_DEFAULT_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_DEFAULT_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_DEFAULT_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_DEFAULT_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_DEFAULT_MS (1000)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MAX_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MAX_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MAX_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MAX_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MAX_MS (10000)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MIN)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MIN)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MIN \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MIN)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MIN (1)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT (10)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MAX)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MAX)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MAX \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MAX)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MAX (80)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB (1)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB (10)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB (512)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MIN)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MIN)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MIN \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MIN)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MIN (1)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT (20)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MAX)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MAX)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MAX \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MAX)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MAX (80)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB (1)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB (500)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB)
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB (4096)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS (1000)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS (5000)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MAX_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MAX_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MAX_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MAX_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MAX_MS (20000)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS (100)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS (1000)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MAX_MS)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MAX_MS)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MAX_MS \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MAX_MS)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MAX_MS (5000)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MIN)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MIN)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MIN \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MIN)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MIN (1)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_DEFAULT)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_DEFAULT)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_DEFAULT \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_DEFAULT)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_DEFAULT (1)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MAX)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MAX)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MAX \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MAX)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MAX (50)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MIN_BYTES)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MIN_BYTES)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MIN_BYTES \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MIN_BYTES)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MIN_BYTES (64)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_DEFAULT_BYTES)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_DEFAULT_BYTES)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_DEFAULT_BYTES \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_DEFAULT_BYTES)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_DEFAULT_BYTES (128)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MAX_BYTES)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MAX_BYTES)
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MAX_BYTES \
            (CONFIG_BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MAX_BYTES)
#   else
#       define BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MAX_BYTES (8192)
#   endif
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MIN_MS >= \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MAX_MS
#   error "Invalid Settings debug memory sample interval range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_DEFAULT_MS < \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MIN_MS || \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_DEFAULT_MS > \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_SAMPLE_INTERVAL_MAX_MS
#   error "Invalid Settings debug memory sample interval default"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MIN >= \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MAX
#   error "Invalid Settings debug SRAM free threshold range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT < \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MIN || \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT > \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_FREE_PERCENT_THRESHOLD_MAX
#   error "Invalid Settings debug SRAM free threshold default"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB >= \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB
#   error "Invalid Settings debug SRAM largest free block threshold range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB < \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB || \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB > \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_INTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB
#   error "Invalid Settings debug SRAM largest free block threshold default"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MIN >= \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MAX
#   error "Invalid Settings debug PSRAM free threshold range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT < \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MIN || \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_DEFAULT > \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_FREE_PERCENT_THRESHOLD_MAX
#   error "Invalid Settings debug PSRAM free threshold default"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB >= \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB
#   error "Invalid Settings debug PSRAM largest free block threshold range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB < \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MIN_KB || \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_DEFAULT_KB > \
    BROOKESIA_APP_SETTINGS_DEBUG_MEMORY_EXTERNAL_LARGEST_FREE_BLOCK_THRESHOLD_MAX_KB
#   error "Invalid Settings debug PSRAM largest free block threshold default"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS >= \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MAX_MS
#   error "Invalid Settings debug thread profiling interval range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS < \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS || \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS > \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MAX_MS
#   error "Invalid Settings debug thread profiling interval default"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS >= \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MAX_MS
#   error "Invalid Settings debug thread sampling duration range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS < \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS || \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS > \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MAX_MS
#   error "Invalid Settings debug thread sampling duration default"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_DEFAULT_MS >= \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_DEFAULT_MS
#   error "Settings debug thread sampling duration default must be shorter than profiling interval default"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_SAMPLING_DURATION_MIN_MS + 100 >= \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_PROFILING_INTERVAL_MIN_MS
#   error "Settings debug thread profiling interval minimum must exceed sampling duration minimum by 100 ms"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MIN >= \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MAX
#   error "Invalid Settings debug thread idle CPU threshold range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_DEFAULT < \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MIN || \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_DEFAULT > \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_IDLE_CPU_PERCENT_THRESHOLD_MAX
#   error "Invalid Settings debug thread idle CPU threshold default"
#endif

#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MIN_BYTES >= \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MAX_BYTES
#   error "Invalid Settings debug thread stack high water mark threshold range"
#endif
#if BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_DEFAULT_BYTES < \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MIN_BYTES || \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_DEFAULT_BYTES > \
    BROOKESIA_APP_SETTINGS_DEBUG_THREAD_STACK_HIGH_WATER_MARK_THRESHOLD_MAX_BYTES
#   error "Invalid Settings debug thread stack high water mark threshold default"
#endif

/**
 * @brief Enable the Settings app memory/heap trace instrumentation.
 *
 * Profiling-only switch (defaults to disabled). When non-zero, the Wi-Fi list sync path
 * emits [HeapTrace] logs describing slot accounting. The functional Wi-Fi behavior is
 * unchanged regardless of this switch.
 */
#if !defined(BROOKESIA_APP_SETTINGS_ENABLE_MEMORY_TRACE)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_ENABLE_MEMORY_TRACE)
#       define BROOKESIA_APP_SETTINGS_ENABLE_MEMORY_TRACE CONFIG_BROOKESIA_APP_SETTINGS_ENABLE_MEMORY_TRACE
#   else
#       define BROOKESIA_APP_SETTINGS_ENABLE_MEMORY_TRACE (0)
#   endif
#endif

#if !defined(BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG)
#   if defined(CONFIG_BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG)
#       define BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG CONFIG_BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG
#   else
#       define BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG (0)
#   endif
#endif

#if BROOKESIA_APP_SETTINGS_ENABLE_MEMORY_TRACE && !BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG
#   undef BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG
#   define BROOKESIA_APP_SETTINGS_ENABLE_PROFILE_LOG (1)
#endif
