/*
 * SPDX-FileCopyrightText: 2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: CC0-1.0
 */
#pragma once

#include "sdkconfig.h"

#define COZE_AGENT_ENABLE_DEFAULT_CONFIG CONFIG_EXAMPLE_COZE_AGENT_ENABLE_DEFAULT_CONFIG

#if COZE_AGENT_ENABLE_DEFAULT_CONFIG

#define COZE_AGENT_APP_ID                  CONFIG_EXAMPLE_COZE_AGENT_APP_ID
#define COZE_AGENT_DEVICE_PUBLIC_KEY       CONFIG_EXAMPLE_COZE_AGENT_PUBLIC_KEY
#define COZE_AGENT_CUSTOM_CONSUMER         CONFIG_EXAMPLE_COZE_AGENT_CUSTOM_CONSUMER
#define COZE_AGENT_BOT1_ENABLE             CONFIG_EXAMPLE_COZE_AGENT_BOT1_ENABLE
#define COZE_AGENT_BOT2_ENABLE             CONFIG_EXAMPLE_COZE_AGENT_BOT2_ENABLE

#if COZE_AGENT_BOT1_ENABLE
#   define COZE_AGENT_BOT1_NAME            CONFIG_EXAMPLE_COZE_AGENT_BOT1_NAME
#   define COZE_AGENT_BOT1_ID              CONFIG_EXAMPLE_COZE_AGENT_BOT1_ID
#   define COZE_AGENT_BOT1_VOICE_ID        CONFIG_EXAMPLE_COZE_AGENT_BOT1_VOICE_ID
#   define COZE_AGENT_BOT1_DESCRIPTION     CONFIG_EXAMPLE_COZE_AGENT_BOT1_DESCRIPTION
#endif // COZE_AGENT_BOT1_ENABLE

#if COZE_AGENT_BOT2_ENABLE
#   define COZE_AGENT_BOT2_NAME            CONFIG_EXAMPLE_COZE_AGENT_BOT2_NAME
#   define COZE_AGENT_BOT2_ID              CONFIG_EXAMPLE_COZE_AGENT_BOT2_ID
#   define COZE_AGENT_BOT2_VOICE_ID        CONFIG_EXAMPLE_COZE_AGENT_BOT2_VOICE_ID
#   define COZE_AGENT_BOT2_DESCRIPTION     CONFIG_EXAMPLE_COZE_AGENT_BOT2_DESCRIPTION
#endif // COZE_AGENT_BOT2_ENABLE

#endif // COZE_AGENT_ENABLE_DEFAULT_CONFIG
