// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Smartwatch

#ifndef _SMARTWATCH_UI_H
#define _SMARTWATCH_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "esp_brookesia.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen_watch_digital.h"
#include "screens/ui_Screen_watch_analog.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui_Startevents____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_flash_png);    // assets/flash.png
LV_IMG_DECLARE(ui_img_step_png);    // assets/step.png
LV_IMG_DECLARE(ui_img_daily_mission_png);    // assets/daily_mission.png
LV_IMG_DECLARE(ui_img_sec_dot_png);    // assets/sec_dot.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png

// FONTS
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Title);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
