#pragma once

#include "lvgl.h"
#include "base/assets/esp_brookesia_base_assets.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Images */
// Small (Typically 240x240)
LV_IMG_DECLARE(esp_brookesia_image_small_app_launcher_default_98_98);
LV_IMG_DECLARE(esp_brookesia_image_small_navigation_bar_back_24_24);
LV_IMG_DECLARE(esp_brookesia_image_small_navigation_bar_home_24_24);
LV_IMG_DECLARE(esp_brookesia_image_small_navigation_bar_recents_screen_24_24);
LV_IMG_DECLARE(esp_brookesia_image_small_recents_screen_trash_38_38);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_battery_charge_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_battery_level1_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_battery_level2_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_battery_level3_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_battery_level4_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_wifi_close_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_wifi_level1_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_wifi_level2_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_status_bar_wifi_level3_20_20);
LV_IMG_DECLARE(esp_brookesia_image_small_wallpaper_dark_240_240);
// Middle (Typically 480x480)
LV_IMG_DECLARE(esp_brookesia_image_middle_app_launcher_default_112_112);
LV_IMG_DECLARE(esp_brookesia_image_middle_navigation_bar_back_32_32);
LV_IMG_DECLARE(esp_brookesia_image_middle_navigation_bar_home_32_32);
LV_IMG_DECLARE(esp_brookesia_image_middle_navigation_bar_recents_screen_32_32);
LV_IMG_DECLARE(esp_brookesia_image_middle_recents_screen_trash_48_48);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_charge_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level1_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level2_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level3_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_battery_level4_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_close_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_level1_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_level2_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_status_bar_wifi_level3_24_24);
LV_IMG_DECLARE(esp_brookesia_image_middle_wallpaper_dark_480_480);
// Large (Typically 720x720)
LV_IMG_DECLARE(esp_brookesia_image_large_app_launcher_default_112_112);
LV_IMG_DECLARE(esp_brookesia_image_large_navigation_bar_back_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_navigation_bar_home_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_navigation_bar_recents_screen_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_recents_screen_trash_64_64);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_battery_charge_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_battery_level1_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_battery_level2_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_battery_level3_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_battery_level4_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_wifi_close_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_wifi_level1_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_wifi_level2_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_status_bar_wifi_level3_36_36);
LV_IMG_DECLARE(esp_brookesia_image_large_wallpaper_dark_720_720);

#ifdef __cplusplus
}
#endif
