/*
 * SPDX-FileCopyrightText: 2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once

#if defined(ESP_PLATFORM)
#   include "sdkconfig.h"
#endif

#define BROOKESIA_RUNTIME_WASM_LOG_TAG "RtWasm"
#define BROOKESIA_RUNTIME_WASM_BACKEND_NAME "RuntimeWasm"

#if !defined(BROOKESIA_RUNTIME_WASM_ENABLE_AUTO_REGISTER)
#   if defined(CONFIG_BROOKESIA_RUNTIME_WASM_ENABLE_AUTO_REGISTER)
#       define BROOKESIA_RUNTIME_WASM_ENABLE_AUTO_REGISTER CONFIG_BROOKESIA_RUNTIME_WASM_ENABLE_AUTO_REGISTER
#   else
#       define BROOKESIA_RUNTIME_WASM_ENABLE_AUTO_REGISTER (0)
#   endif
#endif

#if BROOKESIA_RUNTIME_WASM_ENABLE_AUTO_REGISTER
#   if !defined(BROOKESIA_RUNTIME_WASM_PLUGIN_SYMBOL)
#       define BROOKESIA_RUNTIME_WASM_PLUGIN_SYMBOL runtime_wasm_backend_symbol
#   endif
#endif

#if !defined(BROOKESIA_RUNTIME_WASM_ENABLE_DEBUG_LOG)
#   if defined(CONFIG_BROOKESIA_RUNTIME_WASM_ENABLE_DEBUG_LOG)
#       define BROOKESIA_RUNTIME_WASM_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_RUNTIME_WASM_ENABLE_DEBUG_LOG
#   else
#       define BROOKESIA_RUNTIME_WASM_ENABLE_DEBUG_LOG (0)
#   endif
#endif

#if BROOKESIA_RUNTIME_WASM_ENABLE_DEBUG_LOG
#   if !defined(BROOKESIA_RUNTIME_WASM_BACKEND_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_RUNTIME_WASM_BACKEND_ENABLE_DEBUG_LOG)
#           define BROOKESIA_RUNTIME_WASM_BACKEND_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_RUNTIME_WASM_BACKEND_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_RUNTIME_WASM_BACKEND_ENABLE_DEBUG_LOG (0)
#       endif
#   endif
#   if !defined(BROOKESIA_RUNTIME_WASM_HOST_IMPORT_ENABLE_DEBUG_LOG)
#       if defined(CONFIG_BROOKESIA_RUNTIME_WASM_HOST_IMPORT_ENABLE_DEBUG_LOG)
#           define BROOKESIA_RUNTIME_WASM_HOST_IMPORT_ENABLE_DEBUG_LOG CONFIG_BROOKESIA_RUNTIME_WASM_HOST_IMPORT_ENABLE_DEBUG_LOG
#       else
#           define BROOKESIA_RUNTIME_WASM_HOST_IMPORT_ENABLE_DEBUG_LOG (0)
#       endif
#   endif
#endif
