name: Push components to Espressif Component Service

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: 'recursive'
      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v1
        with:
          directories: >
            app/brookesia_app_files;
            app/brookesia_app_settings;
            app/brookesia_app_store;
            gui/brookesia_gui_interface;
            gui/brookesia_gui_lvgl;
            hal/brookesia_hal_adaptor;
            hal/brookesia_hal_boards;
            hal/brookesia_hal_interface;
            runtime/brookesia_runtime_elf;
            runtime/brookesia_runtime_js;
            runtime/brookesia_runtime_lua;
            runtime/brookesia_runtime_manager;
            runtime/brookesia_runtime_wasm;
            service/agent/brookesia_agent_coze;
            service/agent/brookesia_agent_manager;
            service/agent/brookesia_agent_openai;
            service/agent/brookesia_agent_xiaozhi;
            service/emulation/brookesia_emulation_nes;
            service/expression/brookesia_expression_emote;
            service/framework/brookesia_service_custom;
            service/framework/brookesia_service_helper;
            service/framework/brookesia_service_manager;
            service/media/brookesia_service_audio;
            service/media/brookesia_service_display;
            service/media/brookesia_service_video;
            service/network/brookesia_service_http;
            service/network/brookesia_service_sntp;
            service/network/brookesia_service_wifi;
            service/system/brookesia_service_device;
            service/system/brookesia_service_storage;
            system/brookesia_system_core;
            system/brookesia_system_super;
            utils/brookesia_lib_utils;
            utils/brookesia_mcp_utils;
          namespace: "espressif"
          api_token: ${{ secrets.IDF_COMPONENT_API_TOKEN }}
